### ISSUE TITLE
Adding keywords in the <teiHeader>

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#10]
Dear all, 

This a possible encoding for keywords as discussed yesterday: 
```
<profileDesc>
	<textClass>
		<keywords>
			<term></term><!-- to be repeated for each keyword -->
		</keywords>
	</textClass>
</profileDesc>
```

Each `<term>`could take the attribute `@scheme` containing an URI declared in DHARMA's OpenTheso vocabulary by @alevivier.  I will need to see with @alevivier how to reach automatically those links inside the OpenTheso system.

**Comment by arlogriffiths** [comment]
looks good to me. so can @alevivier start a Vocabulary for keywords, and make "royal" and "non-royal" (or, Manu: "local"?) the first terms in it? obviously, more reflection is needed on what terms we want to admit as keywords.

**Comment by manufrancis** [comment]
Let's start with "royal" and "non-royal".
I will add suggestions, but need to think about them. E.g. I can identify different agencies (member of Brahmin assembly, member of nāṭu assembly, etc.) under "non-royal".

**Comment by alevivier** [comment]
Here a link to a brainstorming file for keywords: https://docs.google.com/document/d/1gTJyTGuVYmMYIm_NstbDWaAy2yZ5l_tEknWsAbtlPJo/edit?usp=sharing

**Comment by danbalogh** [comment]
Looks like I can't edit or comment there.

**Comment by alevivier** [comment]
Here a (new) link to a brainstorming file for keywords:
https://docs.google.com/document/d/1gTJyTGuVYmMYIm_NstbDWaAy2yZ5l_tEknWsAbtlPJo/edit?usp=sharing

**Comment by arlogriffiths** [comment]
This discussion never got very far. Was it a good idea to close the issue?
