### ISSUE TITLE
implement <list> formatting in commentary

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#100]
At the moment we have list formatting like this in Translation, based on `<list>` and `<item>`:

<img width="969" alt="Capture d’écran 2020-11-22 à 13 01 42" src="https://user-images.githubusercontent.com/835603/99903157-ec9e3180-2cc2-11eb-946d-421300471d17.png">

But the same elements yields a different layout in Commentary:

<img width="973" alt="Capture d’écran 2020-11-22 à 13 01 52" src="https://user-images.githubusercontent.com/835603/99903159-f1fb7c00-2cc2-11eb-9ee5-5933c5cb8c2d.png">

@ajaniak : The examples are taken from Kurungan.xml. Can you please 

1. make sure that the behavior of these elements is consistent irrespective of the `<div>` where they are used?
2. make sure that the behavior corresponds to what is said in EGD 10.2.2, whereby a bulleted list should only appear in display if @rend is used and has the value "bulleted"? (At the moment, my code in Kurungan.xml does not yet have that @rend so I shouldn't be getting any bullets.)

**Comment by ajaniak** [comment]
The application of the new code could take 2 hours to be applied because of the css
