### ISSUE TITLE
mysterious ">"

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#103]
- code:

```
<bibl><ptr target="bib:Damais1952_01"/><citedRange unit="page">42-43</citedRange><citedRange unit="part">A</citedRange><citedRange unit="item">60</citedRange></bibl>
	<bibl><ptr target="bib:Damais1955_01"/><citedRange unit="page">189-191</citedRange></bibl>
<!-- elaborate discussion of the dating formula which defies verification -->
	<bibl><ptr target="bib:Damais1970_01"/><citedRange unit="page">49</citedRange><citedRange unit="item">109</citedRange></bibl>
	<bibl><ptr target="bib:Nakada1979_01"/><citedRange unit="page">85</citedRange>><citedRange unit="item">XLV</citedRange></bibl>
	<bibl><ptr target="bib:Nakada1982_01"/><citedRange unit="page">88-89</citedRange><citedRange unit="part">1</citedRange><citedRange unit="item">69</citedRange></bibl>
	<bibl><ptr target="bib:Eade+Gislen2000_01"/><citedRange unit="page">129</citedRange><note>The book does not seem to contain a discussion of this inscription's date.</note></bibl>
```

- display:

<img width="987" alt="Capture d’écran 2020-11-22 à 15 05 52" src="https://user-images.githubusercontent.com/835603/99905921-3cd1bf80-2cd4-11eb-9daf-bf551c129413.png">

@ajaniak : do you understand why the ">" is inserted in front of Nakada 1979? how to make it go away?

**Comment by ajaniak** [comment]
I don't find any entry for Nakada in the files, can you make sure you have pushed this version of the file please?

**Comment by arlogriffiths** [comment]
done, sorry for forgetting about that step.


Le 23 nov. 2020 à 10:11, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



I don't find any entry for Nakada in the files, can you make sure you have pushed this version of the file please?

**Comment by ajaniak** [comment]
the issue is in your encoding: 

```
<bibl><ptr target="bib:Nakada1979_01"/><citedRange unit="page">85</citedRange>><citedRange unit="item">XLV</citedRange></bibl>
```

the first citedRange est closed by two `>>` that's why you have one displayed in your html.

**Comment by arlogriffiths** [comment]
thanks, sorry!

wouldn't it be possible to ensure that such a mistake makes the file invalid?

**Comment by ajaniak** [comment]
I don't see how I could add such a feature into a schema for the parts allowing CData, since the other parts already invalid the double of the >. However, I can add it as a travis test with a grep command line to identify the pattern.

**Comment by arlogriffiths** [comment]
Please explain what you mean with "since the other parts already invalid the double of the >". My file was not declared invalid when it had double >>. Is that normal?

**Comment by ajaniak** [comment]
Yes, it is. > is character data, so it is normal for parts of the XML allowing character data that it doesn't identify it as invalid.

**Comment by arlogriffiths** [comment]
OK, well then let's just close this issue.
