### ISSUE TITLE
conversion of straight to smart quotes

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#104]
@ajaniak : can you implement conversion of straight quotes to smart quotes through XLST transformation? See e.g. the straight quote in the display of `<note>The book does not seem to contain a discussion of this inscription's date.</note>` in the attached screenshot. We'd like such cases to be displayed as smart quotes. **Do you need further specifications on which quotation marks are to be converted in which contexts?** 

<img width="987" alt="Capture d’écran 2020-11-22 à 15 05 52" src="https://user-images.githubusercontent.com/835603/99906012-cbded780-2cd4-11eb-8a9b-6abd91169031.png">

**Comment by ajaniak** [comment]
I don't understand what you ask me. Can you reformulate please?

**Comment by arlogriffiths** [comment]
In my request, you may read "curly" instead of "smart". Then please read [https://practicaltypography.com/straight-and-curly-quotes.html](https://practicaltypography.com/straight-and-curly-quotes.html).

<img width="367" alt="Capture d’écran 2020-11-24 à 09 05 21" src="https://user-images.githubusercontent.com/835603/100065588-3eb29480-2e34-11eb-8f5f-37bc4eaf4bbb.png">


My question was if the XLST can do the replace of straight ' to curly ’ for us. If it is possible, please also let us know whether you think it is advisable or not.

**Comment by ajaniak** [comment]
That was not my question, but anyway I think I figure what you wanted.

**Comment by arlogriffiths** [comment]
Sorry if I misunderstood your question... (It would really be wonderful if we could both make a conscious effort to avoid misunderstandings.)

As far as I have seen so far, what you have implemented work well. Thanks!



Shall
