### ISSUE TITLE
@rend="noname" in <bibl>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#106]
@ajaniak : this doesn't seem to be implemented yet in `<div type="translation">`. Can you solve that?

**Comment by ajaniak** [comment]
I can't find the value `noname` in the EGD, si I need to know to know its behaviour and how it differs from `omitname`.

**Comment by arlogriffiths** [comment]
sorry, my encoding error, it should be « omitname ». will check later today if the problem disappears once I use that value, and let you know.

Le 23 nov. 2020 à 10:19, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :



I can't find the value noname in the EGD, si I need to know to know its behaviour and how it differs from omitname.
