### ISSUE TITLE
display of line break in foreign language within edition

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#109]
It seems that if an `<lb/>` happens to be inside `<foreign>`, then it is not displayed in the HTML transformation. Thus,

`<foreign xml:lang="tel">Eḻṭayu mrontukaṟtiyu raṇastipūṇḍi<lb 
n="92" break="no"/>yu muyyalakuṭṟu</foreign>`

displays "Eḻṭayu mrontukaṟtiyu raṇastipūṇḍiyu muyyalakuṭṟu", instead of displaying a hyphen, line break and line number.

@ajaniak : can the display be implemented just as it is done for non-foreign text? Or, if it is impractical to do so (e.g. too complex and error-prone technically), should I instead make it explicit in the EGD that `<foreign>` should be broken up into two tags when interrupted by an `<lb/>`, i.e. encode the above as follows?

`<foreign xml:lang="tel">Eḻṭayu mrontukaṟtiyu raṇastipūṇḍi</foreign><lb 
n="92" break="no"/><foreign xml:lang="tel">yu muyyalakuṭṟu</foreign>`

**Comment by ajaniak** [comment]
I have added a `mode` feature on the code  to display `lb` so transformation is applied at several levels of the codes. 
Can you check that the output is matching your expectation ?

**Comment by danbalogh** [comment]
Thanks, this looks perfect. For the above code, I now get the display

Eḻṭayu mrontukaṟtiyu raṇastipūṇḍi-
92yu muyyalakuṭṟu

- as expected.

**Comment by ajaniak** [comment]
Great! I am closing this issue then

**Comment by danbalogh** [comment]
A probably related issue I've just noticed: premodern correction (`<subst>` with `<del>` and `<add>`) also doesn't show when enclosed in foreign.
Code: `<foreign xml:lang="tel">sirip<unclear>odipūṇ</unclear>ḍiyu goṁganavroliyu ḻullayuṁ bottun<subst><del rend="corrected">u</del><add place="overstrike">a</add></subst> kollikuṟṟu</foreign>`
display: ... bottunua ... instead of displaying "u" as deleted and "a" as added, as elsewhere in the edition.
There may be other elements as well that do not display as expected when used within `<foreign>`; I haven't checked.
The issue is not urgent. I'm reopening this thread instead of creating a new one (and will do the same if I find other similar issues), but feel free to close it when it's been dealt with.

**Comment by ajaniak** [comment]
Should be good now. I have added @mode feature for `<add>` and `<del>`. Can you check that the output is matching your expectation ?

**Comment by danbalogh** [comment]
Thanks, indeed, I now get the display: sirip(odipūṇ)ḍiyu goṁganavroliyu ḻullayuṁ bottun{{u}}⟨⟨a⟩⟩ kollikuṟṟu - correct.
