### ISSUE TITLE
List of EpiDoc projects

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#111]
Some of you may have seen the recent call on the MARKUP list for info on projects using EpiDoc. Do you agree that DHARMA should be added to that list?
The information they call for is concise:
title - host institution or location
Documentation (URL):
Source files (URL):
Publications:

and the list-in-progress, with just a few items as yet, is here: https://sourceforge.net/p/epidoc/wiki/Examples/

Given the examples already on the list, multiple links for each of the above categories may be given, e.g. for documentation we can list the EGD, TG, possibly the ZG, and so on. If you'd like me to, I can start compiling the items to add here, but I'm not sure exactly what and how much of our work should be made public at this stage, so please help with suggestions. I'm especially unsure what, if anything, should be mentioned as a publication, about which the original email says, "Publications should be focussed on the markup and project descriptions".

**Comment by manufrancis** [comment]
Thanks, Dan!

Arlo already circulated the information to Axelle and myself.
Axelle will take care of this and she will also clean the readme-s on github.

Axelle had a query (not yet answered by Arlo) about the inclusion of the Campa and EIAD projects on the same page.

Let us compile in the present issue the items to be included ??

    Documentation: EGD, TG, possibly the ZG, and so on ...
    Source files: 
    Publications:

I see for the moment no publication "focussed on the markup and project descriptions" to be included.

**Comment by arlogriffiths** [comment]
Thanks and sorry for being slow rto answer: in my view, EIAD and Campā should not be mentioned as they will intregrate DHARMA and are not documented in any way.





Le 25 janv. 2021 à 10:17, manufrancis <notifications@github.com<mailto:notifications@github.com>> a écrit :



Thanks, Dan!

Arlo already circulated the information to Axelle and myself.
Axelle will take care of this and she will also clean the readme-s on github.

Axelle had a query (not yet answered by Arlo) about the inclusion of the Campa and EIAD projects on the same page.

Let us compile in the present issue the items to be included ??

Documentation: EGD, TG, possibly the ZG, and so on ...
Source files:
Publications:


I see for the moment no publication "focussed on the markup and project descriptions" to be included.

**Comment by ajaniak** [comment]
@danbalogh about your questions regarding what we should made public, I was thinking we should only provide links to what has been official shared for the guide, and so rather than sharing the current google Docs links, I guess we could provide the link EGD version 1 in project-documentation repository.

**Comment by danbalogh** [comment]
I also think it's better if the Documentation link is to the published guides deposited on HAL. Am I right to think that if we share a link to, for instance, EGD v1, and subsequently issue EGD v2, we will not need to update the link, i.e. that the original link will take the user to a page where both v1 and v2 are shown?

**Comment by ajaniak** [comment]
We can provide the HAL without the suffix version, when done it directs people by default to the latest version of a document. 
So https://hal.archives-ouvertes.fr/DHARMA/halshs-02272407 would be the equivalent of https://hal.archives-ouvertes.fr/DHARMA/halshs-02272407v3.

**Comment by danbalogh** [comment]
Thanks, this sounds good.

**Comment by danbalogh** [comment]
Has anything been submitted to the EpiDoc folks about DHARMA? I do not see our project listed as yet under https://sourceforge.net/p/epidoc/wiki/Examples/

**Comment by ajaniak** [comment]
All the cleaning for it has been done, but I understood you would be the one making the submission. Am I wrong?

**Comment by danbalogh** [comment]
Since [Manu above](https://github.com/erc-dharma/project-documentation/issues/111#issuecomment-766672604) said, "Axelle will take care of this and she will also clean the readme-s on github.", I thought you two had discussed this.

**Comment by manufrancis** [comment]
Dear Dan, my mistake ; -)
Could you please email the EpiDoc folks?
Maybe you can share the following link with them: https://erc-dharma.github.io/ ?
Axelle has added links towards the project documentation in the top menu.

![image](https://user-images.githubusercontent.com/905870/120813774-81c19300-c54e-11eb-893c-88a24cd7b5b1.png)

**Comment by danbalogh** [comment]
Done. It seems that this overview page eliminates the need to give separate links to files and documentation, so I've just sent them this:

title - project DHARMA (ERC 809994) – Paris, Berlin and Naples
Documentation and Source files: https://erc-dharma.github.io/
Publications: none concerning the project as a whole

**Comment by ajaniak** [comment]
Thanks

**Comment by manufrancis** [comment]
Thanks both Dan and Axelle !
