### ISSUE TITLE
@resp and @source for div[@type='translation']

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#112]
@danbalogh, 

@arlogriffiths and me are wondering about the attributes `@resp` and `@source` for `<div type="translation">`. 

I understand the 9.2.1, 9.2.2 et 10.6.1 of the EGD as expecting one of the two attributes for each `<div type="translation">` without consideration if the person of the translation is also the author of the rest of the edition. And so I made the mandatory the presence of one of the two attributes in the schema. 
We remember a discussion about deleting the @resp if the author of the edition is the same as the one for the translation. And Arlo though it was already applied. 

So can you let us know where we are on the subject?  and do I need to change the schema?
Thank you!

**Comment by danbalogh** [comment]
That discussion is in #70 and there never was a conclusion or consensus concerning `@resp`, only about `@xml:lang`. I'll be happy to change the EGD in any way that the PIs can agree on, but I don't think I have the capacity to come up with a solution that would respect all, or even most, of the convoluted and sometimes contradictory desires expressed there. My suggestion is that for the time being we stick to what we have in the EGD and the schema. Sometime in the near future, the PIs, in consultation with Adeline and Axelle (and perhaps me), should come to an agreement about what must be encoded in the <respStms> of our editions, and only after that is settled should they (or we) return to the issue of what must be encoded for translations.

**Comment by ajaniak** [comment]
Thank you for your answer. I will keep the schema as it is. 

I will close this issue to only keep #70 in that case.
