### ISSUE TITLE
<title> not yet active in div type="commentary"?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#113]
Dear @ajaniak — the following bit of code comes from my file Palepengan.xml. in `<div type="commentary">`. I was expecting `<title>` to be displayed in italics. (Isn't that the normal behavior we have agreed upon?)

`<p n="10-11">The emendation of <foreign>paja</foreign> to <foreign>pūja</foreign> makes it possible to imagine a meaningful connection with the mention of <foreign>vali</foreign> (Sanskrit <foreign>bali</foreign>) in the next line, as <foreign>pūjā</foreign> and <foreign>bali</foreign> are two fundamental categories of Hindu worship. The term <foreign>lañjān</foreign>, not recorded in OJED, occurs three times in the <ref target="Landa.xml">Landa inscription</ref>, in context which are very comparable to the present one. (Another possible occurrence is found in <ref target="Rumwiga.xml">Rumwiga</ref> 1r3.) While no word <foreign>lañjān</foreign> or base <foreign>lañja</foreign> is recorded in OJED, or even in any dictionary of Modern Javanese that I have been able to consult, the word <foreign>lañja</foreign> is attested in Old Sundanese where it means <q>layer</q> and is also used as verb meaning <q>to layer, to apply as a layer</q>, normally applied to precious metal or gems, as for instance in the <title>Siksa Kandaṅ Karǝsian</title>. But in Modern Sundanese the base <foreign>lanja</foreign> is used in connection with <foreign>sawah</foreign>. See <bibl><ptr target="bib:Hardjadibrata2003_01"/><citedRange unit="entry"><foreign>lanja</foreign></citedRange></bibl>: <q><foreign>vi. ngalanja</foreign> (unc.) add a second layer to the first one, cover in (over/up) st.; repeat a job or action; take a second one to a woman; take a second one to a moneylender/supplier; <foreign>ngalanja sawah</foreign> (of a landowner) get rice-fields under his management in order to sublet them to small farmers; <foreign>ngalanjakeun</foreign> give management of (rice-fields) to sublet them to a third party (esp. by a village head to a trusted person, middleman/agent between the owner and cultivator); <foreign>jual lanja</foreign> s.m. <foreign>tutung duit</foreign> (see <foreign>tutung</foreign>)</q>. It is on this basis, and on the basis of what can be extrapolated from the present context, to I propose to interpret the derived form lañja-an as meaning <q>income from subletting</q>.</p>`

current display:

<img width="974" alt="Capture d’écran 2021-02-04 à 09 40 35" src="https://user-images.githubusercontent.com/835603/106866967-5ed0c080-66cd-11eb-89e9-7ce2e1722876.png">

**Comment by ajaniak** [comment]
It should be good now. It was a depth problem and I added a mode to resolve it. Can you check that the display is as you expect it?

**Comment by arlogriffiths** [comment]
thanks, problem solved!
