### ISSUE TITLE
Display of page breaks in lacuna

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#114]
I have a display transformation problem that I can't figure out. It is not essential and not urgent, but should be dealt with sooner or later.
In Vengicalukya Epigraphy CalE55-Vandram-Amma2, the previous editor did not attempt to transcribe anything for a barely legible stretch of the plates, and did not publish a facsimile so I can't attempt to provide a reading. Hence, I have code like this:

```
<p>... LEGIBLE TEXT BEFORE THIS POINT <pb n="3v" break="no"/><lb n="37" break="no"/>yettham ājñāpayati<g type="ddandaSerif">..</g></p><gap reason="illegible" extent="unknown" unit="character"/> 
<!--page 3v probably had lines 37 to 45--><gap reason="illegible" quantity="8" unit="line" precision="low"/>
<pb n="4r"/><!--page 4r probably had lines 46 to 54--><gap reason="illegible" quantity="9" unit="line" precision="low"/>
<pb n="4v"/><!--page 4v probably had lines 55 to 64--><gap reason="illegible" quantity="6" unit="line" precision="low"/><lb n="61"/><gap reason="illegible" extent="unknown" unit="character"/>
<p>tasmai ... TEXT AGAIN LEGIBLE FROM THIS POINT  </p>
```

For the above code, I get this HTML:
⎘ plate 3v 37yettham ājñāpayati||
[...] [ca. 8 lines illegible] [ca. 9 lines illegible] [ca. 6 lines illegible]
61[...]
tasmai

That is to say, nothing is displayed for <pb n="4r"/> and <pb n="4v"/>

Strangely, if I do a transformation on the following sample code from the EGD (Appendix C Case Study 2B)

```
<pb n="2r"/><!--Although a foliation mark was in all probability present on the lost plate, we do not restore one.-->
<gap reason="lost" quantity="3" unit="line"/>
<!--Individual line beginnings are not reconstructed on a lost page, only recorded as a lacuna of known size. -->
<pb n="2v"/>
<gap reason="lost" quantity="3" unit="line"/>
```

then the page breaks are displayed in the HTML.
I've tried modifying my code to see whether the non-appearance of the page breaks could be linked to the presence of XML comments, to the presence or absence of line breaks next to the page breaks, or to whether or not the breaks and lacunae are enclosed in an `<ab>` - but as far as I can see, none of these result in the page breaks appearing in the HTML.

Can you help me figure out what is wrong? I'm happy to change my encoding if I've missed something. Ideally, I believe my encoding should be permitted, and in transformation it should display the page breaks and the lacunae.

**Comment by ajaniak** [comment]
There are two codes for the pb: one we could say for `<pb/>` anchored in the encoding and another one for floating one. So far, the code for the floating one was really broad, that's why it worked in a not so stable way; especially with the commentary which were creating conflict nodes. 
I have added a more specific rule for scenario with `<pb/>` and `<gap/>` matching both of your examples. It should work with stability now. Can you test it out to make sure I have understand your issue correctly?

**Comment by danbalogh** [comment]
Many thanks for dealing with this so quickly. Whatever you did, it solved the issue at hand, and if I do a transformation on my file, I do see the page breaks now in the HTML.
