### ISSUE TITLE
display of <ab> 

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#116]
`<ab>` is currently displayed indented towards the right.

![image](https://user-images.githubusercontent.com/905870/108202371-4d51d480-7121-11eb-8dad-139d49ddc11b.png)

See https://github.com/erc-dharma/tfa-pallava-epigraphy/blob/master/texts/xml/DHARMA_INSPallava00108.xml

Could it be displayed not indented as follows? (I am not clear if this would interact with other EGD uses of `<ab>`)

![image](https://user-images.githubusercontent.com/905870/108202511-7f633680-7121-11eb-8a6c-0d3c09be7af7.png)

**Comment by ajaniak** [comment]
I think the ident for the `<ab>` element was inherit from Epidoc conventions and was kept as such so far.

**Comment by manufrancis** [comment]
Thought so too the indent was inherited from EpiDoc.
@danbalogh : do you think of any specific use of <ab> that should not be "not indented"?

**Comment by danbalogh** [comment]
No, I agree with Manu that the contents of `<ab>` should not be indented. I've also noticed this before, but considered it a trivial matter that we can leave for later. If it is not too bothersome to solve, then indeed, my preference would be to display `<ab>` in exactly the same way as <p>. (After all, our use of `<p>` is not really EpiDoc compliant - they normally just put an `<ab>` around the whole text of an inscription. We use both `<p>` and `<ab>` segment longer inscriptions into semantic units.)

**Comment by ajaniak** [comment]
It should be good right now.

**Comment by danbalogh** [comment]
Thanks

**Comment by manufrancis** [comment]
Yes, thanks, Axelle!
