### ISSUE TITLE
display of <supplied reason="undefined"/>

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#117]
`<supplied reason="undefined"/>` has currently no specific display, it seems. 

See https://github.com/erc-dharma/tfa-pallava-epigraphy/blob/master/texts/xml/DHARMA_INSPallava00108.xml
Where in line 2 of edition we have `<supplied reason="undefined">parumāṟku</supplied>`

![image](https://user-images.githubusercontent.com/905870/108202914-19c37a00-7122-11eb-9f8f-fe364139160a.png)

Could  `<supplied reason="undefined">parumāṟku</supplied>` be displayed as `[parumāṟku]`?
This display should, I believe, be implemented everywhere.

**Comment by ajaniak** [comment]
It is because by default the `<supplied reason="undefined">` is used in combination with `@evidence` in epidoc. Since it is not our case, it has currently no display.  
I have added it in the codes, it should be good.

**Comment by manufrancis** [comment]
I thought so that it was somehow inherited from EpiDoc schema.
It is now fine. Thanks!!
