### ISSUE TITLE
update ISO639-3 codes

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#118]
Dear Axelle,

Please update all xml files that contain provisional language codes with the new ones now available at [https://iso639-3.sil.org/code_tables/639/data/o](https://iso639-3.sil.org/code_tables/639/data/o), by making the following replacements:

- `ocm` for `x-oldcham`
- `okz` for `x-oldkhmer`
- `omy` for `x-oldmalay` (I don't think you'll find any relevant case)
- `osn` for `x-oldsun`

Thanks!

Arlo

**Comment by ajaniak** [comment]
It has been done
