### ISSUE TITLE
add value "item" to <citedRange>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#119]
Dear Axelle,

EGD 10.4.5 allows value "item", but this is not yet offered by Oyxgen. See screenshot.

<img width="928" alt="Capture d’écran 2021-03-04 à 05 27 05" src="https://user-images.githubusercontent.com/835603/109911532-8d30c400-7caa-11eb-889d-0bb78758292e.png">

Can item be added to the list of allowed values?

**Comment by ajaniak** [comment]
Item is already in the value lists. But since we have kept the Epidoc schema as well you are querying Epidoc values and not Dharma

**Comment by arlogriffiths** [comment]
I am just curious why we cannot be querying DHARMA values. Please close the issue if there is no way to do this while still keeping the EpiDoc schema.

**Comment by ajaniak** [comment]
I have tried something to make Dharma schema have priority over epidoc one.
