### ISSUE TITLE
EpiDoc template v2

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#12]
Points to finalise in the new template:

- `<handDesc>` content - pending finalisation in EG (problem: how do we fit both a general palaeographic description and, in some cases, specific <handNote> elements?)

- `<respStmt>` content - pending finalisation of required and recommended content

Possible minor corrections:

- "encoding" instead of "creation of file" as `<resp>` (but this may be revised anyway along with other responsibilities)

- `<revisionDesc>` - require, optionally permit, or prohibit full stop at end of a `<change>`? decide and harmonise in template.

**Comment by ajaniak** [comment]
I don't think we will use the content of `<revisionDesc>` itself. We might want to display the "latest" date of work and the person in charge of updating the file between official releases, but the content is mostly for DHARMA members. So I am not sure, we need to write a model for editing changes.
