### ISSUE TITLE
merging of gaps not effective in <app>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#122]
code:

`<div type="edition" xml:lang="san-Latn">
<lg n="1" met="uncertain">
   <l><lb n="1"/><gap reason="lost" extent="unknown"/><gap reason="illegible" unit="characters" quantity="1"/><unclear>tatra</unclear>ś<unclear>ī</unclear>tyāyam abhūn mahākra<supplied reason="lost">t</supplied><unclear>u</unclear><supplied reason="lost">ḥ</supplied></l>
</lg>
                    </div>
            <div type="apparatus">
              <app loc="1">
<lem><gap reason="lost" extent="unknown"/><gap reason="illegible" unit="characters" quantity="1"/><unclear>tatra</unclear>ś<unclear>ī</unclear>tyāyam</lem>
<note>It seems impossible to interpret ....</note>
              </app>
            </div>`

display:

<img width="397" alt="Capture d’écran 2021-03-13 à 06 36 37" src="https://user-images.githubusercontent.com/835603/111020506-b64a0680-83c6-11eb-9dac-5273f913cdb0.png">

we should have [...] instead of [][...] also in the apparatus entry.

**Comment by ajaniak** [comment]
Should be good now. Please be aware I had to move some codes that were dealing with the spaces inside the apparatus, I haven't been able to spot one but it might depending the context.

**Comment by arlogriffiths** [comment]
thanks! closing this issue.
