### ISSUE TITLE
Display of <ref> in <note>

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#123]
When a `<note>` contains a `<ref>`, e.g.
`<p rend="stanza" n="20"> ... like a string of flowers <supplied reason="explanation">on a vine</supplied>—<note>Compare verse 15 of the <ref target="DHARMA_INSVengiCalukya00049.xml">Raṇastipūṇḍi grant of Vimalāditya</ref>.</note></p>`
then the contents of the `<ref>` get displayed in the text next to the note anchor, e.g.
 shines evidently like a string of flowers (on a vine)—↓10Raṇastipūṇḍi grant of Vimalāditya.
in the HTML. The note itself is correctly displayed as an endnote, but the contents of the ref should not be duplicated next to the anchor.
This happens in the translation division; I have not checked whether it also occurs elsewhere.
Not an urgent matter.

**Comment by ajaniak** [comment]
should be good now

**Comment by danbalogh** [comment]
It is, thanks.
