### ISSUE TITLE
Permit @part on <ab> in schema

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#124]
This is not urgent. The code 
`<ab part="I">śā<choice><sic>ś</sic><corr>s</corr></choice>an<choice><sic>ā</sic><corr>a</corr></choice>sya li<unclear>kha</unclear></ab>`
returns the error message "attribute "part" not allowed here; expected attribute "n", "rend", "xml:id", "xml:lang" or "xml:space""
The text ends here abruptly, the remainder lost, and I want to use `@part` to indicate this (EGD §2..1.3, §5.4.7).
Thanks.

**Comment by ajaniak** [comment]
Should be good now

**Comment by danbalogh** [comment]
Indeed. Thanks, that was fast indeed.
