### ISSUE TITLE
transformation lacking CSS?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#125]
Dear Axelle,

I have been noticing that Salomé's and my transformations produced in Oxygen seem to have lost the CSS layer. See screenshot attached.

<img width="1146" alt="Capture d’écran 2021-04-08 à 07 26 40" src="https://user-images.githubusercontent.com/835603/113972930-c9bc8600-983b-11eb-8ff7-9d8e1b56d7c2.png">

Do you see what is causing the problem?

**Comment by ajaniak** [comment]
Ps: you need to make sure you have the latest version of the XSLT.

**Comment by arlogriffiths** [comment]
thanks, yes the problem is resolved now
