### ISSUE TITLE
allow file names with prefix DHARMA_DiplEd or create separate template for dipl. editions

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#127]
Dear Axelle,

I have just started my first attempt to edit a manuscript diplomatically, using our EpiDoc template. This leads to a validation error as shown below:

<img width="1171" alt="Capture d’écran 2021-04-18 à 18 40 25" src="https://user-images.githubusercontent.com/835603/115153496-83a2c600-a076-11eb-9d2b-d9c691512a53.png">

Maybe you could change the schema to allow also the file names prescribed by FNC §1.6 and §2.5.4 for diplomatic editions of manuscripts?

But probably better to create a separate template for diplomatic editions of manuscripts, in which 

- the expected file name is as prescribed by FNC for a manuscript-based diplomatic edition
- the `<div>`s with @type="apparatus", @type="translation", @type="commentary" and @type="bibliography" are removed
- the EGC's structure for encoding manuscript-related metadata could be added in the teiHeader

What do you think?

If you agree, could you also update the structure of the other dipl. ed. file we already have, none of which seem to be based on the current version of the EpiDoc template?

Thanks!

**Comment by ajaniak** [comment]
Schema and templates are different things. Please be careful not to confuse them. 
Both have been created for diplomatic editions and I will updated the existing files.

**Comment by arlogriffiths** [comment]
thank you! 

I understand the difference, but a template has to call a schema, and I didn't know what you wanted to do in the case of creating a separate template for dipl. editions: 

- operate with the same schema of epigraphic editions or 
- create a variant suitable for dipl editions based on manuscripts

Especially since we have only one guide for diplomatic editions. 

Could you explain to all of us how the new dipl. ed. schema you ahve created relates to the one we use for epigraphic editions?

I'm adding @danbalogh to the discussion as some specifications for diplomatic editions based on manuscripts may become necessary in the EGD.

**Comment by ajaniak** [comment]
The EGC's structure for encoding manuscript-related metadata could be added in the teiHeader isn't Epidoc compliant. If you add Epidoc and DHARMA schemas into your diplomatic editions, it won't validate. There are also various choice that are making impossible to use all the DHARMA schemas (Relax NG, schematron and SQF).

**Comment by arlogriffiths** [comment]
thanks. but this is partly too technical for me. please give us advice on what to do.

**Comment by ajaniak** [comment]
I would keep a lighter version of the critical editions metadata that can match the one used in Epidoc, and I would reduce its application with a DHARMA specific to diplomatic editions schema when necessary.
