### ISSUE TITLE
<space> inside <unclear>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#128]
This seems to be forbidden by the schema. I have the following code which causes my file to be invalid:

`<unclear>va<space type="descender"/>huta</unclear>`

@ajaniak @danbalogh 
Why should we forbid use of `<space>` inside `<unclear>`? 
Is this rule stated as such in EGD?

**Comment by danbalogh** [comment]
That's the ubiquitous EpiDoc constraint: `<unclear>` can only contain character data and `<g>`. Split your markup:
<unclear>va</unclear><space type="descender"/><unclear>huta</unclear>

**Comment by danbalogh** [comment]
See also EGD §8.2.5: when a different element (other than `<g>`) needs to be nested inside `<unclear>`, then again, `<unclear>` must be split into separate parts

**Comment by arlogriffiths** [comment]
thanks a lot for reminding me!
