### ISSUE TITLE
problem with display of <unclear> inside <num>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#129]
- code: `<lb n="2v12"/><abbr>yu</abbr> <num value="1"><unclear>1</unclear></num> vahuta <gap reason="illegible" quantity="4" unit="character"/> mantyāsi<unclear>ḥ</unclear> si ḍaṁh<unclear>ǝ</unclear>l· vinaiḥ vḍihan· <abbr>yu</abbr> <num value="1"><unclear>1</unclear></num> <unclear>saṁ</unclear> rama I duga-duga gusti`

- display:
<img width="646" alt="Capture d’écran 2021-05-08 à 07 43 13" src="https://user-images.githubusercontent.com/835603/117528168-1cbb6180-afd1-11eb-91e7-3fdd9ce04177.png">

- @ajaniak : the expected opening parenthesis is missing in the display both cases of `<num value="1"><unclear>1</unclear></num>`

**Comment by arlogriffiths** [comment]
The following anomaly with missing closing parenthesis is no doubt related.

- code: `<lb 
n="2r4" break="no"/>da vinaiḥ vḍiha<unclear>n·</unclear> <abbr>yu</abbr> <num value="1">1</num> ma<space type="descender"/>s· <abbr>mā</abbr> <num value="4">4</num> tuhān· I ma<unclear>kudur·</unclear> <num value="2"><unclear>2</unclear></num> `

- display: 
<img width="459" alt="Capture d’écran 2021-05-08 à 11 02 06" src="https://user-images.githubusercontent.com/835603/117533413-00c5b900-afed-11eb-91ec-447e0160bf72.png">

**Comment by arlogriffiths** [comment]
we still have some related problems. see screenshot:

<img width="988" alt="Capture d’écran 2021-05-13 à 06 35 18" src="https://user-images.githubusercontent.com/835603/118078026-967a9300-b3b5-11eb-9e11-0b741c7525db.png">

- problems are apparent in "ma(kudur·) 2)" and in "vḍihan· (yu) 1)"

**Comment by arlogriffiths** [comment]
and none of the colors for encoded `<num>` are showing up in this paragraph:

<img width="982" alt="Capture d’écran 2021-05-13 à 06 38 59" src="https://user-images.githubusercontent.com/835603/118078222-fb35ed80-b3b5-11eb-8259-1bacd8f673a2.png">

**Comment by ajaniak** [comment]
I have stabilized those cases. However, the color is related to issue #129, and that's why no color is yet associated with `num`.
