### ISSUE TITLE
problem with display of <pb n="..." break="no"/>?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#130]
I assume that the repetition of the indication of plate 2v in the following display is due to a bug:

<img width="987" alt="Capture d’écran 2021-05-08 à 11 07 36" src="https://user-images.githubusercontent.com/835603/117533539-aaa54580-afed-11eb-996e-f436fd4dcf34.png">

Corresponding code:

`Aṅ<supplied reason="lost">i</supplied>nn-a
<pb n="2v" break="no"/><lb n="2v1" break="no"/>ṅin· si basu,`

We want the hyphen to appear immediately at the of the last line before `<pb>`, like this: Aṅ[i]nn-a-

**Comment by ajaniak** [comment]
Should be good now.
