### ISSUE TITLE
using <supplied> inside <fw>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#132]
- code 
`Anakta hyaṁ kālamr̥tyu gaṇa bhūta, kita pra<pb 
n="3v" break="no"/><pb 
n="4r" break="no"/><fw place="left" rend="tb-rotated" n="4r"><supplied reason="lost"><num value="4">4</num></supplied></fw><lb 
    n="4r1" break="no"/><supplied reason="lost">siddha</supplied> ma<unclear>ṁ</unclear>rakṣa ka<unclear>ḍatvan·</unclear> śrī mahārāja I mḍaṁ Iṁ bhūmi matarām· kita Umilu manarīra Umasuk iṁ sarbaśarīra kita sakala sākṣībhūta`

- display:

<img width="373" alt="Capture d’écran 2021-05-30 à 07 45 56" src="https://user-images.githubusercontent.com/835603/120093515-1aa17a00-c11b-11eb-8ca5-4f8b6fcfba08.png">

- I have discovered that our system is smart enough not to display the `<lb n="3v"/>` for the empty page that comes between 3r and 4r in this set of plates engraved on only one side: great!
- however, something is going wrong with the display of `<fw>`: we don't want to see [4] to be inserted within pra-, and ideally our display of `<fw>` would make it possible to work with square brackets for @reason="lost" as elsewhere 
- or do we have a rule forbidding use of `<supplied @reason="lost">` inside `<fw>`?
- I suggest getting rid of quare brackets in display of normal `<fw>` so that in a case like this the display could be "plate 4r fw: [4]"

**Comment by ajaniak** [comment]
It should work now.

**Comment by arlogriffiths** [comment]
Thanks. But the appearance of square brackets still needs to be removed from cases not affected by `<supplied`>:

- code: `<fw place="left" rend="tb-rotated" n="1v"><num value="1">1</num></fw><lb n="1r1"/>`
- display: 
<img width="157" alt="Capture d’écran 2021-05-31 à 11 53 31" src="https://user-images.githubusercontent.com/835603/120176007-1488c780-c207-11eb-9828-2164a36da80f.png">

**Comment by ajaniak** [comment]
Ah no mean no square brackets at all for the regular cases?

**Comment by arlogriffiths** [comment]
Indeed, no square brackets at all

**Comment by ajaniak** [comment]
it was been done

**Comment by arlogriffiths** [comment]
Thanks. This is an example of what we have now:

<img width="118" alt="Capture d’écran 2021-05-31 à 18 44 32" src="https://user-images.githubusercontent.com/835603/120222479-48ccaa00-c240-11eb-8aaf-a5b8e5350c63.png">


It might be nicer to insert a space between the display of `<fw>` and the following `<lb>`.

**Comment by ajaniak** [comment]
done

**Comment by arlogriffiths** [comment]
tested successfully! thanks!
