### ISSUE TITLE
Display of description lists

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#133]
Dear @arlogriffiths,

is it what you meant for the display of label inside a description list with  
> with hanging indent and display the bold label at the same height as the first line of the following `<item>`

<img width="967" alt="Capture d’écran 2021-05-31 à 15 00 15" src="https://user-images.githubusercontent.com/33328906/120197129-f16b1180-c220-11eb-83aa-c44b2f4f3717.png">

or you meant something more like this:
<img width="977" alt="Capture d’écran 2021-05-31 à 14 50 07" src="https://user-images.githubusercontent.com/33328906/120197200-021b8780-c221-11eb-80f9-fb2a3d497953.png">

I am not sure how to interpret the hanging indent.

**Comment by arlogriffiths** [comment]
The first format is exactly what I had in mind!

Let me know if I can already use `<label>` in my code and what kind of @rend to apply to the `<list>`.

**Comment by ajaniak** [comment]
You can use it. I have kept things simple. You just have to use `<label>` and `<item>` together inside `<list>`, no need for `@rend` but I can update this, if @danbalogh and you would like it better. The CSS is set on the first solution, but it might not be working yet on the server.

**Comment by arlogriffiths** [comment]
I have done a pull on project documentation but the schema doesn't yet seem to allow use of `<label>` insides `<list>`... Am I overlooking something?

**Comment by arlogriffiths** [comment]
Ignore that last comments! It looks good now!
