### ISSUE TITLE
<note> inside <list> and display of <supplied reason="explanation">

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#134]
It seems that `<note>` is not yet configured to show its normal behavior within `<list>`. 

- code: `No one is left behind in taking part in feasting <supplied reason="explanation"><foreign>manaḍah</foreign></supplied> on the market place of Ālasantan: 
<list>	<item>being regaled,</item>
	<item>being offered dressed-up rice <supplied reason="explanation">? <foreign>skul dāndānan</foreign></supplied>,</item> 
	<item>being ladled <supplied reason="explanation"><foreign>hinirusan</foreign></supplied>:<note><bibl><ptr target="bib:Zoetmulder1982_01"/><citedRange unit="entry"><foreign>irusan</foreign></citedRange></bibl> is in need of correction, as it is based on a single passage from a reissued inscription. An entry needs to be added for the verbal derivation <foreign>aṅirusi</foreign> of which <foreign>hinirusan</foreign> is the passive form.</note>
	<list rend="bulleted">
		<item>cooked foods <supplied reason="explanation"><foreign>kǝla-kǝla</foreign></supplied>,</item>
		<item>snacks <supplied reason="explanation"><foreign>ambil-ambil</foreign></supplied>, </item>
		<item><foreign>kasyan</foreign>,</item> `

- display: 
<img width="978" alt="Capture d’écran 2021-06-05 à 16 59 14" src="https://user-images.githubusercontent.com/835603/120895931-75593b00-c61f-11eb-86ea-dec6f0587655.png">

**This is not all. See also how `<supplied reason="explanation"><foreign>manaḍah</foreign></supplied>` is failing to insert (...) in the example above, right before the `<list>` begins. But then, inside `<list>`, `<supplied reason="explanation">? <foreign>skul dāndānan</foreign></supplied>` does get (...) in display.**

**Comment by arlogriffiths** [comment]
In fact the problem also seems to involve `<bibl>`, as I notice only now that the notes are displayed below, but with a bug concerning display of `<bibl>`:

<img width="1036" alt="Capture d’écran 2021-06-05 à 17 07 22" src="https://user-images.githubusercontent.com/835603/120896168-9d956980-c620-11eb-9dc9-a69cd31bbc9b.png">

**Comment by arlogriffiths** [comment]
a case `<title>` is not being displayed in note 3

**Comment by ajaniak** [comment]
Ok, I think I have updated all the necessaries elements. Can you check?

**Comment by arlogriffiths** [comment]
Thanks. The problems seem to be resolved. One small fine-tuning remains: the "appels de note" should never be italicized. See screenshot.

<img width="421" alt="Capture d’écran 2021-06-07 à 10 31 18" src="https://user-images.githubusercontent.com/835603/120985176-a6e71900-c77b-11eb-8990-1e3deb86202c.png">

**Comment by arlogriffiths** [comment]
One more thing. The screenshot shows that `<supplied>` is still not being correctly displayed, becuase we expect (...) around _hinirusan_ .

code: `<item>being ladled <supplied reason="explanation"><foreign>hinirusan</foreign></supplied>:<note>....</note>`

**Comment by ajaniak** [comment]
Should be good now

**Comment by arlogriffiths** [comment]
the appels de note are still shown in italics:

<img width="414" alt="Capture d’écran 2021-06-07 à 11 04 35" src="https://user-images.githubusercontent.com/835603/120989775-2f67b880-c780-11eb-90c5-6f10dc778232.png">

**Comment by ajaniak** [comment]
that should work too now

**Comment by arlogriffiths** [comment]
thanks!
