### ISSUE TITLE
display of <citedRange> without @unit

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#135]
See our discussion in the draft for new edition of EGD, §10.4.5, concerning use of `<citedRange>` without unit.

Currently, the display is not yet as we want it:

-code: `Zoetmulder  (<bibl rend="omitname"><ptr target="bib:Zoetmulder1982_01"/><citedRange><foreign>s.vv.</foreign> <foreign>adhikāra</foreign> I.2 and <foreign>tan adhikara</foreign></citedRange></bibl>) has not precisely understood`

- current display:
<img width="982" alt="Capture d’écran 2021-06-07 à 11 41 43" src="https://user-images.githubusercontent.com/835603/120995073-5c6a9a00-c785-11eb-8f15-64cb05c7a2f8.png">

- expected display: "Zoetmulder  (1982: _s.vv._ _adhikāra_ I.2 and _tan adhikara_) has not precisely understood"

**Comment by ajaniak** [comment]
just to be sure : you want me to delete the link and have a different dealing of italics, is that it?
