### ISSUE TITLE
display of <supplied> in translation

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#136]
the expected behavior is still sometimes not shown

- code: `<foreign>dyah</foreign> Ghoṣa, teaming up with <supplied reason="explanation">? amasaṅakan i</supplied>`
- display: 
<img width="512" alt="Capture d’écran 2021-06-10 à 09 45 20" src="https://user-images.githubusercontent.com/835603/121485583-99769c80-c9d0-11eb-8645-2c6ad7c35f2f.png">

maybe the fact that the context is `<list>` is relevant

**Comment by ajaniak** [comment]
Should be good

**Comment by arlogriffiths** [comment]
the same problem is back.

- code: `<p n="1r14-1r16">Likewise the <supplied reason="subaudible">payments for</supplied> <q>harms and compensations</q> <supplied reason="explanation"><foreign>sukha-duḥkha</foreign></supplied>, such as:<note>I adopt the interpretation of the term <foreign>sukha-duḥkha </foreign> itself, and of the meanings of the items in the following list, from work in progress by Timothy Lubin.</note>
<list>...</list>`
- display:
<img width="984" alt="Capture d’écran 2021-06-12 à 08 17 56" src="https://user-images.githubusercontent.com/835603/121767130-c05edb00-cb56-11eb-840d-e2382f89dd95.png">


- note that `<supplied reason="explanation"><foreign>sukha-duḥkha</foreign></supplied>` is displayed without (...)
- note also that `<note>` is not displayed as it should be (cf. #138)

**Comment by ajaniak** [comment]
I have tried a new solution for supplied as well as for note. Not sure if it will be stable enough though

**Comment by arlogriffiths** [comment]
looks good, thanks!
