### ISSUE TITLE
<note> not correctly displayed (interference from <list>?)

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#138]
- file DHARMA_INSIDENKAlasantan.xml
- code: `<p n="1r3-1r8">Its total: 13 <foreign>tampah</foreign>, in addition to the housing-premises and orchards, the price for them being 12 <foreign>kāṭi</foreign> <supplied reason="explanation">of gold</supplied>. The headmen of Ālasantan together with the inhabitants of the village sold the land. Every headman received gold:<note>The headword of each entry in the list (<foreign>vinkas</foreign>, <foreign>apkan</foreign>, <foreign>gusti</foreign>, etc.) is directly followed by a name, further names separated by median dots.</note> 
<list>...</list>`
-  attached to preceding text without any differentiation in display:
<img width="1009" alt="Capture d’écran 2021-06-11 à 22 10 58" src="https://user-images.githubusercontent.com/835603/121743625-ec9c3c80-cb01-11eb-9451-ca72ef43e398.png">

@ajaniak: can you fix this?

**Comment by arlogriffiths** [comment]
The problem seems to be associated with `<list>`. In the transformation of file DHARMA_INSIDENKAlasantan.xml, several cases of `<note>` are correctly displayed, but not those which occur near `<list>`. (I think that is the pattern, but I am not entirely sure.)

**Comment by ajaniak** [comment]
I have tried a new solution as said in #136 - seem stable enough in DHARMA_INSIDENKAlasantan.xml but not sure it will be with other files

**Comment by arlogriffiths** [comment]
Thanks! So far, the solutions seem to work!

Re. our brief discussion with @manufrancis  yesterday, here is an example of how I am now trying to implement `<note>` as well as `<list>` with `<item>` and `<label>` in some inscriptions:

<img width="772" alt="Capture d’écran 2021-06-23 à 13 54 29" src="https://user-images.githubusercontent.com/835603/123092244-947f0780-d42a-11eb-94d2-38ec95049372.png">
