### ISSUE TITLE
display of <ref>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#139]
- code: `<note>Regarding the term <foreign>pakaraṇān</foreign>, see our commentary on the <ref target="DHARMA_INSIDENKWuruduKidul.xml">Wurudu Kidul</ref> inscription.</note>`
- display: 
<img width="506" alt="Capture d’écran 2021-06-12 à 08 41 29" src="https://user-images.githubusercontent.com/835603/121767697-2f89fe80-cb5a-11eb-9812-94a8f7a71ebd.png">

- is it possible get the contents of `<ref>` displayed even if the hyperlink cannot yet be applied (in case the xml file in question is in a different folder)?

**Comment by arlogriffiths** [comment]
The problem is clearly associated with occurrence of `<note>` — `<ref>` does seem to work in environments where there is no `<note>`.

**Comment by ajaniak** [comment]
I have enable ref everywhere. It should be ok now

**Comment by arlogriffiths** [comment]
Thanks!
