### ISSUE TITLE
Dharma cheatsheet reshuffled

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#14]
Here is the link (same as before) to the DHARMA cheatsheet:
https://drive.google.com/file/d/1k45HLD0WecpYjnMMN9GFCXV4jLLRSEr9/view?usp=sharing

Dan, I have put your suggestions for more colours in a dedicated column (suggestions).
I am not in favour of too much colours. I suggest we concentrate for the moment on a display corresponding to black and white print.

**Comment by danbalogh** [comment]
I have no problem with using few or no colours; whatever you prefer is OK.
