### ISSUE TITLE
section headers within <div type="commentary">

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#141]
At the moment, we only allow sectioning of commentary with `<p>`. But @amandinebricout has found, while encoding some BengalCharters, that she needs to be able to introduce `<head>` which is impossible with `<p>`. 

Could we either allow use of `<head>` with `<p>`, or else introduce a new `<div @type="section">` available to be used within `<div type="commentary">` (and maybe also in `<div type="translation">`)?

**Comment by ajaniak** [comment]
`<head>` can't be used with `<p>`, only as first child of `<div>` or `<list>`. But she could use the element `<title>` even if it is not strictly its intended use. 

I am not against introduction `<div>`  with a new value @type to structure the commentary part. But is it really necessary? At least, from what I understood of the EGD, Amandine could use `<div type="textpart">` to "break up a long commentary into sections (chapters)", those one working autonomously from the other `<div type="textpart">` in the file.  See EGD, §9.3.2, part on textpart division.

**Comment by arlogriffiths** [comment]
@ajaniak : thanks a lot. I had totally forgotten that we allow this use of textpart. it means the problem disappears!

@amandinebricout : no need to change the encoding you had (rightly) implemented! (and Axelle has already solved the problem with `<foreign>`.)

I am closing this issue.
