### ISSUE TITLE
[editorial conventions] make insertion of space after : language dependent

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#143]
- code: 
```
<div type="edition" xml:lang="kaw-Latn">
<p> ...
<lb n="4r9" break="no"/>ṅin-aṅinan· ṅuniveḥ kǝbvanya blaḥ <num value="1">1</num> yathānya tan pamuhara pramāda magǝ:ṁ I sira, ... </p>
         </div>
```

- display after application of editorial conventions: 
<img width="589" alt="Capture d’écran 2021-07-21 à 20 14 17" src="https://user-images.githubusercontent.com/835603/126495035-1458b633-71ca-4cdc-b227-9c80c3bfeb3a.png">

- @ajaniak : can you modify the editorical conventions so that insert of space after ":" either (a) applies only when language is English, French or German, or (b) does not apply when `xml:lang="kaw-Latn"` or `xml:lang="kaw-osn"`?

Thanks!

**Comment by arlogriffiths** [comment]
sorry, as this may not be evident for you, I explain that ":" is part of the (strict) transliteration system and should not be considered a "colon" in that context. see TF §2.5.

**Comment by ajaniak** [comment]
If I understood correctly this rule should be applied on the edition div and not only for `@xml:lang="kaw-Latn"` or `@xml:lang="kaw-osn"` right?

**Comment by arlogriffiths** [comment]
Maybe not only in div type=edition, because the use of ":" as element of our transliteration system might also occur in div type=apparatus, and conceivable even in div type=commentary . 

The only languages where this use of ":" is liable to occur are @xml:lang="kaw-Latn" or @xml:lang="kaw-osn".

By the way, is the default language in aaparatus that of the edition or of the root of the file?

**Comment by ajaniak** [comment]
Ok, so I will linked it to those two values of the `@xml:lang`

The apparatus works with the default language declared at the root of the file.

**Comment by arlogriffiths** [comment]
If that is the case in apparatus, then linking the rule concerning non-insertion of space after ":" to the values of `@xml:lang` will not work, because we are liable to have some cases of ":" in apparatus for editions of texts in @xml:lang="kaw-Latn" or @xml:lang="kaw-osn", but those language values are not declared in the apparatus were the machine thinks the current language is the one declared at the root of the file.

Why not scrap the space-insertion rule altogether? Is it that common for people who write in English, French or German to forget to insert a space after a colon?

**Comment by ajaniak** [comment]
I think another solution would be better: taking the apparatus following the edition with ` @xml:lang="kaw-Latn" or @xml:lang="kaw-osn"`and applying the rules to the descendant, i.e. `lem`and `rdg`. It allows to keep both set of rules and coverts all the cases.

**Comment by arlogriffiths** [comment]
Will that not be difficult to implement, at least in theory, given the fact that the value of xml:lang may change in the course of the edition and even within a line of text? If I am not mistaken, this means that at any time the relevant language at a @loc cannot be known unless it is encoded manually into the `<app>`.

That said, in practice the number of multilingual texts involving any parts with `@xml:lang="kaw-Latn"` or `@xml:lang="kaw-osn"` where those languages are not the value assigned to the `<div type="edition">` will be extremely small, if not non-existent. So practically, your solution could work.

**Comment by arlogriffiths** [comment]
As this time, code like `Umaṁsə: taṁ jnu skar·` still leads to display like this:

<img width="169" alt="Capture d’écran 2022-12-27 à 06 59 25" src="https://user-images.githubusercontent.com/835603/209618771-f913b7e2-5cc8-48ed-a754-3eed54236039.png">

have your tweaks of August 2021 failed to work? 

I am still inclined to advise to drop the space removal rule altogether.

**Comment by ajaniak** [comment]
I have remove the rule.
