### ISSUE TITLE
<supplied> brackets not displayed in translation

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#144]
- code:  `to have the position of <supplied reason="subaudible"><foreign>rakai/samgat</foreign> of</supplied> Girim Baṅi,`
- display: 
<img width="324" alt="Capture d’écran 2021-07-22 à 20 33 37" src="https://user-images.githubusercontent.com/835603/126647665-55f89961-1b7b-4502-aa30-a3de45f583a2.png">

- the presence of `<foreign>` inside `<supplied reason="subaudible">` seems to cancel the display of the expected brackets [...]
- @ajaniak : could you fix this?

**Comment by ajaniak** [comment]
should be good now
