### ISSUE TITLE
Cheatsheet: <g type="symbol" subtype="abc"/>

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#15]
`<g type="symbol" subtype="abc"/>` 
The present suggestion is
---> _abc_ (plus colour? maroon? teal?)

I would avoid italics and concur with Daniel that we need something around "abc".

Axelle, would it possible to have something like an Egyptian "cartouche" around the subtype value?

![final gomutra](https://user-images.githubusercontent.com/905870/77415494-dd2cb880-6dc2-11ea-8b38-7abaf5f87ffe.png)

**Comment by arlogriffiths** [comment]
yes, I had thought of the same but without mentioning it because I thought it would pose technical challenges. if Axelle can do it, then it has my preference.

**Comment by ajaniak** [comment]
I have added a black border around the text for now with an inline CSS. 
I will be able to beautify it later once I have settled the handling on the external CSS through github.

**Comment by ajaniak** [comment]
It has been implemented
