### ISSUE TITLE
[editorial conventions] space swallowed before apostrophe

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#152]
There's a problem with one of the editorial conventions rules that is being applied to our files, that causes unwanted disappearances of space before apostrophe.

- code: `<l n="a">yathā samudro ’timahān</l>`
- display: 
<img width="163" alt="Capture d’écran 2021-11-12 à 09 35 48" src="https://user-images.githubusercontent.com/835603/141436315-e45fe2fa-87c8-4983-8eec-7285d353d8b3.png">

We don't want spaces to disappear in such cases. 

This issue probably to be dealt with in conjunction with #143.

**Comment by ajaniak** [comment]
I have made a specific transformation for critical editions, since languages aren't declared at the same level for critical editions and inscriptions

**Comment by ajaniak** [comment]
It was among the rules you wanted me to apply on the XML files. I can delete it, if you think it creates more issues than it resolves. Anyway, I will still need to keep two distincts files because to edit the inscriptions and the critical editions.

**Comment by arlogriffiths** [comment]
Please delete this rule in both transformations, crit. and dipl.

**Comment by ajaniak** [comment]
I have made changes, but it will need review
