### ISSUE TITLE
display of metrical patterns

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#153]
In our editions of critical and diplomatic editions, we often have to display metrical symbols.

Here are two examples:

<img width="302" alt="Capture d’écran 2021-11-12 à 14 23 02" src="https://user-images.githubusercontent.com/835603/141474085-20ba331d-fdfa-415c-b7f4-8ce2118cfa11.png">
<img width="183" alt="Capture d’écran 2021-11-12 à 14 24 01" src="https://user-images.githubusercontent.com/835603/141474090-c45c16d4-4488-4e57-bb0c-a323d1f67062.png">

It is disturbing for me that the symbols "–" for long syllables stick together in display. This makes counting them more complicated.

Therefore I request insertion of a tiny amount of blank space between all symbols in such displays of metrical patterns.

**Comment by ajaniak** [comment]
I have updated the patterns, it might take up to 24 to be applied for critical editions since we use an exterior file to generate the pattern.

**Comment by arlogriffiths** [comment]
At the moment, I don't see the effect yet in our epigraphic editions. Here's an example from tfc-khmer-epigraphy:

<img width="474" alt="Capture d’écran 2021-11-30 à 07 43 22" src="https://user-images.githubusercontent.com/835603/143998711-257d1004-745c-46a9-ab6a-6d0385e707f9.png">

Meanwhile, @met is not being displayed at all in such cases as `<div type="canto" n="1" met="jagaddhita">` (from DHARMA_CritEdKakavinParthayajna.xml)

<img width="527" alt="Capture d’écran 2021-11-30 à 07 46 00" src="https://user-images.githubusercontent.com/835603/143999291-2fb9114c-cc3a-4779-b1e8-11d79039b70d.png">


Should we apply @rend="met" to make it be displayed? (I thought the default behavior was to display it in case of `<div>`....)

**Comment by ajaniak** [comment]
I have changed all the system if should be stable enough now for both your points

**Comment by arlogriffiths** [comment]
The display in Kakavin Parthayajna now looks nice, thanks!

The display in DHARMA_INSCIK00419, from which I took the epigraphic example, does not seem to have changed.

**Comment by ajaniak** [comment]
No updates have been made on tfc-khmer-repository to apply the new transformation on the files. Once someone does, it will appear

**Comment by arlogriffiths** [comment]
I am confused. There have been commmits to that repository in recent hours and yet the display has not changed.

![Uploading Capture d’écran 2021-12-03 à 17.50.38.png…]()

**Comment by ajaniak** [comment]
It should be good now. I have reverted to the initial set up of the workflow that will transform all the files rather than just the updated.
