### ISSUE TITLE
Jihvāmūlīya as independent "character"

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#154]
So far, I've only ever seem upadhmānīya and jihvāmūlīya conjoined to the following akṣara, but I know that some modern scripts use these signs (when they use them at all) in a semi-independent way, so that they appear, like visarga, after the preceding akṣara. Now for the first time, I've come across a jihvāmūlīya used in this way in a late (11th-century) Eastern Cālukya plate:
![yoxka](https://user-images.githubusercontent.com/31253927/142642566-dda335d5-174f-4389-a18b-5cf3e5b9754a.png)
(yoẖ ka).
I propose that I add this under TG '3.3.8, "Unusually composed complex characters", with an optional transliteration yo=ẖ ka (and perhaps also in the EGD, §4.1.1, with the encoding <seg type="aksara">yoẖ</seg> ka), in case someone wishes to make it explicit that an upadhmānīya or jihvāmūlīya is not part of a conjunct with the next character which should, imo, remain the default interpretation.
Arlo, please let me know what you think of this. It may be an unnecessary complication, which I normally tend to avoid, so if you wish to, it will be easy to persuade me to drop this and just mention the issue in the palaeographic description.

**Comment by arlogriffiths** [comment]
As a matter of curiosity, what would a normal visarga look like? The figure 8 cannot be read as a plain visarga?

I have never seen anything like this. But If you are sure of your interpretation then, yes, I would like our TG to allow making a distinction from the normal use of jihvāmūlīya, and the manner you propose seems good.

**Comment by danbalogh** [comment]
A normal visarga would be just a pair of plain dots. That is so in all EC plates I've ever seen, including elsewhere in this one. I too have never seen anything like this, but it does resemble a Kannada jihvāmūlīya,  ೱ. And a visarga is expected here, so I'm as sure as one can be: can't think of anything other than a jihvāmūlīya that it could plausibly be.

**Comment by arlogriffiths** [comment]
Thanks. Then's say go for it, and cite the Kannada jihvāmūlīya, ೱ, in the new TG item.

**Comment by danbalogh** [comment]
Thanks for the opinion. Done in the TG.
