### ISSUE TITLE
definition of <space type="binding-hole">

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#155]
@danbalogh  — could you make the necessary clarirications in EGC and TG to ensure that encoders understand that this type of `<space>` may also be used if, in a manner that is standard in Indonesian palmleaf manuscripts, and is occasionally immitated in copper-plates, there is only a small physical hole that interrupts only one line but a substantial rectangular space around it left open that interrupts the surrounding lines?

See screenshot attached.

<img width="352" alt="Capture d’écran 2021-12-07 à 06 27 14" src="https://user-images.githubusercontent.com/835603/144972311-7478b2d2-e4c9-4fad-ba53-8ff0a7c80c3f.png">

**Comment by danbalogh** [comment]
Done in the EGD (§4.3.5), which I suppose you meant by EGC. The TG has no discussion, only a reference to the EGD.
