### ISSUE TITLE
swallowed spaces

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#158]
- code examples: `<lb n="1"/><g type="spiralR"/> svasti` and ` vappaghoṣavāṭa-grāma <choice><sic>Ā</sic><corr>A</corr></choice>kṣayaṇī<supplied reason="omitted">vī</supplied>-dharmmaṇā pradattaḥ`
- display: 
<img width="107" alt="Capture d’écran 2021-12-25 à 08 42 39" src="https://user-images.githubusercontent.com/835603/147380190-b3b9b10f-d3da-49d3-a33b-3c3bae9c0c43.png">
<img width="480" alt="Capture d’écran 2021-12-25 à 08 42 53" src="https://user-images.githubusercontent.com/835603/147380192-4169a59d-5b0d-43ea-9f20-00f376bdaa9a.png">
- why are the spaces being swallowed?

**Comment by arlogriffiths** [comment]
the problem is quite widespread at the moment. see around the blue sigla and around italics and in gthe translation heading in this screenshot:

<img width="837" alt="Capture d’écran 2021-12-28 à 07 27 37" src="https://user-images.githubusercontent.com/835603/147535376-5885d45a-f255-4b7c-aab4-3d2144235aa2.png">

**Comment by ajaniak** [comment]
I have updated the code, it should be good for most space issues.
