### ISSUE TITLE
display layout: transition from verse to prose in middle of physical line

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#159]
The following display doesn't seem perfect to me. I'd say we want the same amount of white space after the stanza as between stanza and prose if the prose begins on a new physical line.

<img width="809" alt="Capture d’écran 2022-01-07 à 12 33 24" src="https://user-images.githubusercontent.com/835603/148538495-c0d9ec11-314d-4bf7-b2c8-f6737219ea67.png">

**Comment by arlogriffiths** [comment]
by the way, in the same inscription I find an apparently identical scenario which does have space between verse and prose:

<img width="821" alt="Capture d’écran 2022-01-07 à 12 41 57" src="https://user-images.githubusercontent.com/835603/148539318-ff63fab0-ac56-4717-b0de-2c86b48b944b.png">

**Comment by ajaniak** [comment]
It is done
