### ISSUE TITLE
cheatsheet: <hi rend="grantha">svasti śrī</hi>

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#16]
This tag is used by TFA.
The current display is just red.
This need to be changed since `<sic>` is now red-coloured.

I usually mark Grantha in bold.
I suggest thus
`<hi rend="grantha">svasti śrī</hi>` ----> **svasti śrī**

Arlo, can we display `<lem>` as roman (not bold, as it is currently)?
`<lem>` would still be differentiated from `<rdg>`, which is currently coloured.

Furthermore, we have to decide whether `<rdg>` would be mono-coloured (my preference) or if we would like the different colours (`<orig>`, `<sic>`, etc.) displayed (which might be confusing, since there is the colour-layer of `<rdg>` also at play there).

**Comment by danbalogh** [comment]
All very good points. I think there should be no problem retaining bold for Grantha. I concur that it may be best not to colour editorial markup in the apparatus; maybe not colour anything, just keep it black and white? How about displaying lemmas as Roman regular and readings as italic? Plus display a character, e.g. ⟧ after the lemma.

**Comment by arlogriffiths** [comment]
Sorry, I am against any bracket-like sign, such as ⟧, to delimit the lemma. I consider that my experiments in the Campā site (with delimiter ◇) and esp. in EIAD (where mix of bold+color is used to differentiate lem, rdg and source) are important advances on the paper-print conventions, because they avoid use of yet another bracket, and entirely avoid any symbol in the EIAD case. For the latter reason, I find the EIAD solution best.

I can live without bold on the lemma, though I do find it essential to let the lemma stand out very clearly by some kind of typographic device. Of course we can initially experiment, Manu, with only colors distinction, as you propose.

I also agree with not using editorial color markup in apparatus (and wonder whether we should have it in text).

**Comment by danbalogh** [comment]
The delimiter ◇ is perfectly OK as far as I'm concerned; my only point was that we should have a sign, and I agree that avoiding yet another bracket is a good idea.

**Comment by arlogriffiths** [comment]
I would not object reverting to the delimiter ◇ (with surrounding spaces) to ensure a clear distinction between lemma and reading.

**Comment by manufrancis** [comment]
OK, let me summarise.

Settled:
`<hi rend="grantha">svasti śrī</hi>` ----> **svasti śrī**
`<lem>` ----> Roman, black
`<rdg>` ----> Monocoloured green  @ajaniak: could you set the transformation so that markup inside `<rdg>` is also green?
No bracket-like sign, such as ⟧, to delimit the lemma, but delimiter ◇.

To be settled:
How to make `<lem>` typographically standing out compared to `<rdg>`?
I like Daniel's suggestion: `<rdg>` italicised.

**Comment by arlogriffiths** [comment]
here is my proposal with somewhat standardized presentation, addition of a line concerning @source, and modifiation on rdg

`<hi rend="grantha">abc</hi>` ----> **abc** (bold, black)
`<lem>abc</lem>` ----> abc (roman, black) followed by ◇
`<rdg>abc</rdg ----> _abc_ (italic, light green — as in EIAD, see screenshot attached)
`@source="AbCd"` ----> AC (roman, darkblue, mous-over displays further bibliographic data if possible in html — as in EIAD, see screenshot attached)


<img width="837" alt="Capture d’écran 2020-03-24 à 13 52 37" src="https://user-images.githubusercontent.com/835603/77427596-f475a100-6dd6-11ea-8a06-309a45b667b5.png">



To be settled:
How to make <lem> typographically standing out compared to <rdg>?
I like Daniel's suggestion: <rdg> italicised.

**Comment by arlogriffiths** [comment]
NB: I have had a separate discussion with @ajaniak who proposed to generate the siglum ('AC' in my previous message) by some automated process.

**Comment by danbalogh** [comment]
Generating sigla like that sounds great.

**Comment by ajaniak** [comment]
All have been implemented.

**Comment by danbalogh** [comment]
Is there anything still awaiting a resolution in this issue?

**Comment by manufrancis** [comment]
Everything solved!
