### ISSUE TITLE
bhramaravilasita and Apte

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#161]
@danbalogh : 

1. I have added bhramaravilasita to the prosodicPatterns, with two small questions for you in the xml file. You probably want to add this meter to EGD as well.

2. If you have time, could you add all the Apte references to the prosodicPatterns file, making sure the same pattern of `<citedRange> @unit  is applied throughout?

Thanks! Arlo

**Comment by danbalogh** [comment]
I've sorted Bhramaravilasita out. My replies are in comments in the file, plus two more comments on the other changes I've made there. Please delete all comments when you've seen them, unless you disagree with something in them.
I'll add the Apte references, but unless it's urgent, I'd rather leave it till after Easter and the spring break. I'm setting myself a reminder, but do let me know if you'd rather have them sooner.
