### ISSUE TITLE
edited mr̥dukomala

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#166]
@danbalogh : could you check this entry in the prosodicPatterns?

@andreaacri : the xml and prosodic codes in the `<item>` for this meter that were in the "from Andrea's file" part contained some errors that have now been corrected. the whole item has been moved among the items with 18 syllables in the main part of the prosodicPatterns file. please check the relevant canto(s) in Pārthayajña for conformity with the mr̥dukomala pattern.

**Comment by danbalogh** [comment]
I've checked; not attested in Apte. I've made some changes in the XML file (see comment there) and added it to the EGD appendix. I'll leave it to Andrea to close this thread when he is done.

**Comment by andreaacri** [comment]
Corrected PYñ file (changed mṛdukomala to candravartma)

**Comment by arlogriffiths** [comment]
I am confused. Looking briefly at the cantos in question, the meter in canto 38 is indeed 12-syllabic and seems to show the candravartma pattern. But the meter in canto 39 is 18-syllabic so candravartma cannot be correct (and anyhow we do not expect the same meter in two consecutive cantos). are you sure it is not mr̥dukomala? please check again.

**Comment by andreaacri** [comment]
39 is Mṛdukomala indeed—I've corrected that

**Comment by arlogriffiths** [comment]
I see this in your latest commit. You seem to have forgotten the final a.

<img width="743" alt="Capture d’écran 2022-04-14 à 09 29 25" src="https://user-images.githubusercontent.com/835603/163336019-35cd99f9-c3d5-4ea0-a4ae-b669b7f9f3dc.png">

**Comment by andreaacri** [comment]
corrected!
