### ISSUE TITLE
Using <orig>

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#17]
Here is how <orig> has been so far used by the TFA:

_dhamma_ instead of expected _dharmma_ (_repha_ missing consistently throughout the record)
`<orig>dhamma</orig>`
― when an element is missing, the entire word is tagged

_eṉṉ eḻuttu_ instead of expected _eṉ eḻuttu_ (unstandard _sandhi_)
`e<orig>ṉ</orig>ṉ eḻuttu`
― when an element has been added, this element only is tagged

_nikki_ instead of expected _nīkki_ (in inscriptions not clearly distinguishing _i_ and _ī_)
`n<orig>i</orig>kki`
mola instead of expected maula
`m<orig>o</orig>la`
― when an element has been changed, this element only is tagged

**NB:** I am seriously considering not to be lazy anymore and, instead of using `<orig>` only, to systematically us `<orig>` only within `<choice>` with `<reg>`.

@danbalogh: This tagging policy should already be clear to the TFA encoders. Anyhow, I think that adding a summary of specific instructions on missing/added/changed characters to the EG would help.

**Comment by danbalogh** [comment]
Manu, I think this issue can now be closed.
