### ISSUE TITLE
checked and moved kusumavilasita / merged rajanī with narḍataka

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#170]
The kusumavilasita meter was in the bottom part of the prosodicPatterns file based on import from Andrea's Pārthayajña file. I have moved it up into the main list and checked conformity with Zoetmulder, and added the reference.

The rajanī meter was in the bottom of the file and its identity with narḍataka had not yet been noted. I have now removed the separate rajanī entry but rather added this as a kaw-Latn name under the narḍataka pattern, and added the Zoetmulder reference.

@danbalogh : please to another check on both items.
@andreaacri : the name imported from your file was Kusumavilasitā with final ā, but I am using Zoetmulder's spelling as authoritative for "kaw-Latn" names. Please modify your PY XML file to have @met="kusumavilasita"

**Comment by danbalogh** [comment]
Both look good to me. I've added the gaṇa code for kusumavilasita. I'm leaving it to Andrea to close this thread when he is done.

**Comment by andreaacri** [comment]
Changed kusumavilasitā to kusumavilasita
