### ISSUE TITLE
space being swallowed after ":"

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#171]
I know I have raised this issue before but it doesn't seem to have been fully solved yet.

Code: `tan pilihən <app><lem wit="#M">sākṣya ika kabeh</lem><rdg wit="#L">hika: sa<lb n="08-15"/>kṣya kabeḥ</rdg><rdg wit="#K">sakṣya, hika ta kabeḥ</rdg></app>.`

display of edition (correct)
<img width="602" alt="Capture d’écran 2022-04-28 à 10 18 34" src="https://user-images.githubusercontent.com/835603/165709240-8101a071-f8d8-4ed5-ad82-5d6ca994f5d8.png">

display of apparatus (space is swallowed in #L reading):

<img width="248" alt="Capture d’écran 2022-04-28 à 10 17 22" src="https://user-images.githubusercontent.com/835603/165709350-3fb63e8b-0cbb-4e6d-b7a0-f3974016d05c.png">

**Comment by ajaniak** [comment]
I deleted the rule regarding transliteration in Javanese stating that `:` can't be followed by a space.
