### ISSUE TITLE
added mr̥gāṅkacarita = mattarāga

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#172]
Could you check this item? I think it should be in Apte.

By the way, in furthjer checking, please make sure to assign the @xml:lang san-Latn if a name is identically attested in Sanskrit and Old Javanese. I think we have some `<name>`s labelled as kaw-Latn while the label should be san-Latn.

Also, in `<seg type="prosody">` the gurus are very often represented by plain hyphen (-) whereas the sign should be the proper length mark (–).

**Comment by danbalogh** [comment]
Mr̥gāṅkacarita is by a similar but different name in Apte (added) and the gana code had an error (corrected). I've also checked and corrected hyphens in the prosodic code.
