### ISSUE TITLE
possibility of recording an alternative lemma in case of multiple recensions of a text

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#175]
@ajaniak : if a text is transmitted in clearly identifiable recensions which frequently have variant readings, the one from the other, which both make sense, it is possible to allow displaying both recensions, maybe with buttons "show me that text of recension A" and "show me that text of recension B" ?

Let's discuss when you are back at work.

**Comment by ajaniak** [comment]
Digital Latin uses the element `<join>` to do so. They have used it in the second example of 12.12.4.2 regarding the half lines. This element allows aggregation. I am not sure this is exactly what you expect though. 
```
The use of [<join>](https://digitallatin.github.io/guidelines/LDLT-Guidelines.html#TEI.join) to represent the conflated lines in H and M allows the text of the two lemmata in question to be copied and displayed or printed together.
```

In theory, the quantity of `<lem>` isn't unlimited, so we could put 0 as well as several into an `<app>`. I guess we could decide in favor of an app containing two lemmata and the other variant readings. Maybe adding an  attribute @synch to underline that both are working together and not exclusively. 

Whatever solution we foresee, known that the current technical state might not allow what you describe to work with the static website page. I will see if I can come up with an easy solution with javascript. But I don't see any issue with doing it in the XML database which will allow more interaction with the reader.
