### ISSUE TITLE
new value for @cause on <rdg>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#178]
@ajaniak —

Is there a commonly agreed upon meaning of the value "syntactic" or are the interpretations of such values totally up to the editor (or to the authors of our EGC)? If the latter, then I'd like to introduce a new value "order" for cases like these, where the only significant difference between the rejected reading and the lemma is that the same words are arranged differently.

<img width="1157" alt="Capture d’écran 2022-05-19 à 22 27 31" src="https://user-images.githubusercontent.com/835603/169399389-b9514ad8-2a24-4b8a-8c63-10d318c7f9e2.png">

<img width="1061" alt="Capture d’écran 2022-05-19 à 22 34 42" src="https://user-images.githubusercontent.com/835603/169399910-3177ce1f-428d-468c-9086-6304d2edc760.png">

**Comment by arlogriffiths** [comment]
I meant to say that I could use "syntactic" if its commonly agreed upon definition covers variant readings like `<rdg>butter, bread and jam</rdg>` besides `<lem>bread, jam and butter</lem>`.

**Comment by ajaniak** [comment]
We already have syntactic in the EGC as well as the schema. But I have added an example of this in the EGC, under §5.5.3.

**Comment by arlogriffiths** [comment]
Thanks. I see at [https://digitallatin.github.io/guidelines/LDLT-Guidelines.html](url) §12.15 that "syntactic" means "the reading differs from the lemma in its grammatical construction or arrangement". This means the label might be suitable for the case at hand. But now I see we also have "ordinal", which is even better. I don't know why I didn't see this previously... Sorry about that.
