### ISSUE TITLE
Cheatsheet : rendering of the <lb/>

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#18]
Dear all, 

Could you tell give me your expectation concerning the `<lb/>`? 
So far with Manu, we have tested: bold and superscript.

Best,

**Comment by arlogriffiths** [comment]
What you have so far suits me very well!
________________________________

**Comment by manufrancis** [comment]
What we have is actually quite hybrid:
Bold in edition
Superscript in apparatus.
I suggest bold also in apparatus and everywhere else

**Comment by arlogriffiths** [comment]
I was only alluding to one of the provisional html's shared with me by Axelle 1/2 weeks ago.

Indeed, I suggest that the display be identical in text and in apparatus, and that we retain

- number in parentheses
- in bold and in superscript

**Comment by manufrancis** [comment]
Fine with me.

**Comment by ajaniak** [comment]
So far, it has been implemented for line numbers in prose and those in the apparatus.

**Comment by arlogriffiths** [comment]
Can you implement it in verse context too?

**Comment by ajaniak** [comment]
Yes, but I need time to do so.

**Comment by ajaniak** [comment]
I deleted the purple color associated for the `<lb/>` in verse context.
