### ISSUE TITLE
check vaṁśapatrapatita

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#181]
<img width="1449" alt="Capture d’écran 2022-06-01 à 16 55 31" src="https://user-images.githubusercontent.com/835603/171435745-190cbab9-9eb7-435e-96b1-23aebd9493bc.png">

@zakariyaaminullah : it seems you have just removed two vertical bars form the `<seg type="prosody">` for this meter. I am not sure you should have. These bars indicate the caesura which is inherent in this meter in the Sanskrit tradition. See the top of the file at [https://erc-dharma.github.io/output/display-prosody.html](url). Even though such caesura may not be observed in the Old Javanese usage of the same prosodic patterns, the bars should remain in the definition.

@danbalogh : so unfortunately, you'll have to check this one again...

**Comment by danbalogh** [comment]
Done, no problem.
