### ISSUE TITLE
display of "Editors"

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#189]
dear @ajaniak : the display current seems to be generated from the contents of `<p>Copyright (c) 2019-2025 XYZ</p>`. is it not possible/desirable to generate it rather from `<respStmt>` and more particularly from `<resp>intellectual authorship of edition</resp>`? in that case, the display could also be made sensitive to whether there is only one **Editor** or multiple **Editors**.

<img width="1000" alt="Capture d’écran 2022-11-26 à 19 29 14" src="https://user-images.githubusercontent.com/835603/204089112-9260d4c7-aa7a-45c6-8306-ee94caab72d2.png">

**Comment by ajaniak** [comment]
I have added several possible scenario: depending on the number of editors, the position of the name and the way it is encoded. 
<img width="653" alt="Capture d’écran 2022-11-28 à 11 42 54" src="https://user-images.githubusercontent.com/33328906/204259741-a58a80ea-0042-4473-8073-2d53fcf004eb.png">
<img width="386" alt="Capture d’écran 2022-11-28 à 11 43 00" src="https://user-images.githubusercontent.com/33328906/204259744-91ee0218-4b67-448e-a21e-d3cce0f2a4ea.png">
<img width="405" alt="Capture d’écran 2022-11-28 à 11 43 25" src="https://user-images.githubusercontent.com/33328906/204259750-9503d595-1ebc-4d33-a450-4b8bc4736f85.png">
<img width="601" alt="Capture d’écran 2022-11-28 à 11 50 14" src="https://user-images.githubusercontent.com/33328906/204259754-c61ff222-7145-4aa4-abb3-5fd5915f30ae.png">

However, the currently several files are not encoding correctly regarding the `<respStmt>` and it will make the transformation fail.

**Comment by arlogriffiths** [comment]
Thanks. Those examples all look good. However, I don't think we need to use small caps here (nor for the display of the @resp or @source on `<div type="translation">`, because use of small caps in such contexts is more a French and German than an English thing. I recommend avoiding all small caps in our transformation scenarios, unless it is hard-coded with `<hi>`.

Can you generate a list of xml files and the respective part: responsible for TEI encoding where `<respSmt>`  are not correctly encoded, so we can ask the relevant participants to correct their files?

**Comment by ajaniak** [comment]
Someone ask explicitly for the small caps. I guess it was @manufrancis, but I am not sure. Can I let you two discuss the relevance of those?

I will try to figure something to control them. Currently, I am not sure how though... but it is the reason behind the failure of tfc-nusantara, you have asked about by email today.

**Comment by manufrancis** [comment]
I don't remember if I asked for small caps.
I have no preference. No caps, small caps is bit OK for me.

**Comment by ajaniak** [comment]
I have deleted the small caps for names.

**Comment by arlogriffiths** [comment]
Thanks. I am closing this now. Anyone who insists on small caps can reopen this issue.
