### ISSUE TITLE
display of non-apparatus <note>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#190]
I have the vague recollection that we have discussed this before and I have the impression that the display has evolved.

At the moment, `<note>`s to Translation are shown as a separate block at the bottom of the section, while `<note>`s to Commentary are shown in parentheses and italics at the place where the notes are inserted. See screenshot, where "(Cf. the way ... line 3.)" in Commentary is encoded as a `<note>`.

I would prefer a single block of Notes at the very bottom of the html, combining all `<note>`s (except those contained in `<div type="apparatus">`) and treating them in the same way.

@ajaniak : is this possible?

<img width="831" alt="Capture d’écran 2022-11-27 à 07 54 45" src="https://user-images.githubusercontent.com/835603/204114455-39941c70-f392-4904-9be9-283b093fe308.png">

**Comment by ajaniak** [comment]
No, it was never discussed for the inscription. Just to be clear, you want notes from translations, commentaries and bibliographies to be moved to a bottom apparatus, right?

**Comment by arlogriffiths** [comment]
Yes, that's right. There might also be notes from the teiHeader that could be displayed at the bottom of the html as well.

**Comment by ajaniak** [comment]
A first draft have been pushed, it might require some refining once fully tested against all the possible context for notes. 
<img width="1009" alt="Capture d’écran 2022-11-29 à 11 21 00" src="https://user-images.githubusercontent.com/33328906/204503709-43900945-ff07-49c8-8182-6741243e19db.png">
<img width="1031" alt="Capture d’écran 2022-11-29 à 11 20 21" src="https://user-images.githubusercontent.com/33328906/204503721-2c43f0b7-bfa9-467b-b175-5404138a0040.png">

**Comment by arlogriffiths** [comment]
looks perfect! thanks!

Le 29 nov. 2022 à 17:24, ajaniak ***@***.******@***.***>> a écrit :



A first draft have been pushed, it might require some refining once fully tested against all the possible context for notes.
[Capture d’écran 2022-11-29 à 11 21 00]<https://user-images.githubusercontent.com/33328906/204503709-43900945-ff07-49c8-8182-6741243e19db.png>
[Capture d’écran 2022-11-29 à 11 20 21]<https://user-images.githubusercontent.com/33328906/204503721-2c43f0b7-bfa9-467b-b175-5404138a0040.png>

**Comment by arlogriffiths** [comment]
I am closing this now.

Anyone who doesn't approve of the presentation viewable at `<https://erc-dharma.github.io/tfc-nusantara-epigraphy/workflow-output/html/Java10Majapahit/DHARMA_INSIDENKKedungwangi.html>` can reopen the issue.
