### ISSUE TITLE
EGD: more permissive rules for textpart, encoding DHARMA_INSIDENKHampran.xml

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#193]
moved here from an EGD Gdoc comment.

**Originally raised by @arlogriffiths on 6 Feb 2021**
I am now resuming my work (dropped after April 2020) on DHARMA_INSIDENKHampran.xml. It has clearly distinct zones, but does not specifically satisfy any of the above criteria warranting use of textpart. Nevertheless, in §3.5 I don't find explicit acknowledgement of the fact that our rule stated here to avoid use encoding boxlike partitions even when it would be natural to do so, generates a bunch of leftovers that don't really fit the ideal type of a pagelike partition formulated in §3.5.

**Reply from @danbalogh on 8 Feb 2021**
I don't really understand what the problem is and what you would like me to do about it. When would it be "natural" to encode boxlike partitions? What is it that you want to find explicit acknowledgement of? That some cases will not be clear-cut for "pagelike" or "boxlike" handling? I find that the implicit acknowledgement of that in the sentence "when encoding a structurally complex inscription..." is sufficient, but we can make it more explicit if that is your wish. The choice of encoding method will never be mechanistic, and there will always be cases for which we cannot prepare by giving encoders an algorithmic decision process. They'll have to make a decision.

What are you inclined to do in the particular case of Hampran? I gather that you are inclined to use textpart divs. There is nothing forbidding you from that in the text; the EGD only asks you to consider carefully whether this encoding method is essential.
I'm not sure I visualise your inscription correctly, but it seems to me that the main problem is the line in a possibly much later script. To my mind, that would be a separate inscription, but I can see how it is desirable to encode it together with the rest. If so, why don't you create three textparts: 1) for A and the part of B with the legible and presumably older text; 2) for the illegible and presumably later text in B; and 3) for C? I would then create a page break for textpart 1 at the boundary of A and B, and more page breaks for each separate part of C. But your idea of just using line breaks for the bits of C is also perfectly OK by me. Conversely, if you want to go a step further, you could even create 7 textpart divs, so that each of the little bits of C get a separate textpart of their own.

**Additional comment by @danbalogh just now:**
Regardless of the actual complicated nature of that particular inscription, if the general direction of your comment was that you would like a wider range of arrangements to explicitly permit (or call for) the use of textpart divisions, I would be amenable to changing the EGD to permit or suggest using boxlike divisions for chunks of text that are both visually and semantically distinct. This could be made a generic rule of which the present provision for "visually distinct parts that convey the same message in two (or more) languages" would be a special case. Would that address your concerns about where it is natural to use textparts and about the leftovers that don't fit the idealtype of a pagelike partition?

**Comment by arlogriffiths** [comment]
I propose zoom discussion of this case and my comments originally made in the gdoc. I need to refresh my memory of what the EGD actually says that I was reacting to.

Here's currently display of the inscription in question: [](https://erc-dharma.github.io/tfc-nusantara-epigraphy/workflow-output/html/Java02Sanjaya2Kayuwangi/DHARMA_INSIDENKHampran.html).

I must have meant that using box-like partitions is natural here as the inscription itself uses cartouches.

Here is the esampage:

![EFEOB-est n2308](https://user-images.githubusercontent.com/835603/209061199-7956df93-f5c6-4963-a731-0d5db9f9bfe3.jpg)

**Comment by danbalogh** [comment]
I'm available today to discuss this on Zoom. But it may not be necessary. Having seen the image, I am perfectly happy with your encoding of A, B and C as textparts. I would probably be happier if you treated B5 as yet another textpart, since it seems pretty certain that it is not an integral part of what you now call textpart B.
As I said in my original comment, there is nothing in the EGD that would forbid you from using textparts. As the overview (§3.1) says, you must ask yourself the question, "what does the text do as it reaches the boundary of one zone?" And "if it stops (scheme A), you have a boxlike partition". This is further specified in §3.4.1 as: "there is a semantic discontinuity between the two zones, and there is no unit of intrinsic structure commencing in one and ending in another" - all true in your case. The following cautions only ask you to "consider carefully whether this encoding method is essential" and suggest either encoding the inscriptions in separate documents (if the texts in each box only have a weak connection to one another), or encoding it with pagelike milestones (if there is a strong connection between the texts, and especially if it makes sense to read them in a particular sequence).

So, specifically in your encoding: keep as is, or introduce a new textpart for B5.
And generally in the EGD: if you wish, in §3.4.1 we can change "consider carefully whether this encoding method is essential" to "consider carefully whether this encoding method is **ideal**".

**Comment by danbalogh** [comment]
@arlogriffiths I've made some change suggestions in EGD §3.4.1. If you find them sufficient and you've made your final decision on whether you encode B5 as a separate textpart, then this issue can be closed; otherwise, leave a comment for me.

**Comment by arlogriffiths** [comment]
I think it would be good to include also an explicit mention of a case such as [Sangguran](https://erc-dharma.github.io/tfc-nusantara-epigraphy/workflow-output/html/Java04Balitung2Sindok/DHARMA_INSIDENKSangguran.html) as a possibly occasion for encoding box-like partitions.

**Comment by danbalogh** [comment]
Perhaps as a case study in the appendix; definitely not in the main text of the guide imo. There will always be complex special cases and I see little advantage in trying to come up with complex rules (or even recommendations) for any particular case. It's the general rules of thumb that need to be explained, so that people can make a decision in any particular case. I'll make a note for myself in the guide about this.

**Comment by arlogriffiths** [comment]
I never actually got around to encoding textparts in DHARMA_INSIDENKHampran.xml so reopening this as a reminder to myself.
