### ISSUE TITLE
EGD: faces and facets of objects

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#194]
Issue created from a comment in the EGD.

Context: EGD §3.5.4,
the @unit of a milestone encoding a pagelike partition shall be a single word describing the nature of the transition in the same way as the @subtype of textpart divisions (§3.5.4)
we recommend using values that describe the general nature of a unit rather than its function or appearance; preferably, use one of the following:
"face" for the surfaces of an object with no more than 4 sides
"facet" for the surfaces of an object with a polygonal cross-section
"faces" and "facets" in texts where each line of a pagelike zone runs across two or more surfaces such as the frontal and lateral face of a four-sided stele

**Originally raised by @arlogriffiths, 24 Nov 2022**
what about stelae with both upward and sideways facing lateral faces, where the face count is 6?

**Reply by @danbalogh, 24 Nov 2022**
The best I recall, facet was meant for octagonal (etc.) columns. "polygonal cross-section" in the text means a section crosswise to the inscribed faces. Your stelae then still have a rectangular cross-section (on the horizontal plane), so their sides are faces.
But to be honest, I'm pretty sure the distinction between faces and facets was put in here at your insistence; I would be perfectly happy to use just "face" for all shapes of object.

Current opinion, @danbalogh :
we should discard "facet" and "facets", changing any instances already present in the corpus to "face" / "faces" respectively.
Define "face" as "a physically contiguous surface of a three-dimensional object of any shape and any number of sides"

**Comment by danbalogh** [comment]
@ajaniak , I've had a discussion with Arlo and we are inclined to adopt what I suggest above, i.e. get rid of the token "facet" and "facets". In addition to the context mentioned above (EGD §3.5.4, values of `@unit` on `<milestone>`), this could potentially also be used as a value of `@subtype` on `<div type="textpart">`. Could you give me a list of files in the project that use "facet" or "facets" in either of these contexts? [Or, more simply, as attribute values anywhere, since if they are used at all, they will be in one of these contexts.]
I will see how many there are, and have a look at some or all of them to see if there are any unforeseen situations where the distinction of "facet" is really essential. Probably it is not, in which case I will then later ask you to replace attribute values of "facets" to "faces" and "facet" to "face" throughout the corpus.

**Comment by ajaniak** [comment]
for `<milestone unit="facet"/>`
only tfa-pallava-epigraphy/texts/xml/DHARMA_INSPallava00154.xml

for `<milestone unit="facets"/>`
only tfa-pallava-epigraphy/texts/xml/DHARMA_INSPallava00080.xml

for `<div subtype="facets"/>` and `<div subtype="facet"/>` no files.

**Comment by danbalogh** [comment]
Thanks. I've looked at the inscriptions; the physical arrangement is not entirely clear, but I am certain that "facet" does not describe it better than "face". So,
@ajaniak , please change those two instances to "face" (DHARMA_INSPallava00154.xml) and "faces" (DHARMA_INSPallava00080.xml).

@manufrancis , please note this change; we are getting rid of "facet" and "facets" in encoding extrinsic structure and in future want to use "face" and "faces" regardless of how many sides an object has and in precisely what sort of topography.

**Comment by manufrancis** [comment]
Noted!
Useful simplification!
DHARMA_INSPallava00154.xml and DHARMA_INSPallava00080.xml updated accordingly.
