### ISSUE TITLE
"Tamil with Grantha" script class: redundant?

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#197]
Dear @manufrancis and @alevivier , it seems to me that in our Open Theso for scripts, the class "Tamil with Grantha" (https://opentheso.huma-num.fr/opentheso/?idc=57475&idt=th347) is redundant and should be discarded. An inscription in a mix of those scripts would be encoded using both 38776 Tamil and 36768 Grantha in the metadata, and in the edition itself, it would have 38776 Tamil on the edition div, and 36768 Grantha on `<seg>` elements wherever necessary. See EGD §7.5.5.
Am I right?

**Comment by manufrancis** [comment]
Dear Dan,
Sorry my very very slow answer on this issue.
As far as I remember we devised this class "Tamil with Grantha" for inscriptions in Tamil script where words or syllables appear in Grantha (and thus tagged `<hi rend="grantha">`).
I guess we can dispense with this class "Tamil with Grantha".
BUT
What to do with the text tagged `<hi rend="grantha">`?
Allow the @rendition with `<hi>`? Thus `<hi rend="grantha" rendition="class:38768 maturity:83213">`?
Change `<hi rend="grantha">` to `<seg rend="grantha" rendition="class:38768 maturity:83213">`?

@danbalogh 
@michaelnmmeyer 

What do you think?

**Comment by danbalogh** [comment]
The EGD (§7.5.5) has already been revised so that instead of `<hi rend="grantha">` the correct encoding is now `<seg rend="grantha" rendition="class:38768 maturity:83213">`.  This applies to an edition, whereas (EGD §10.2.1) outside an edition (e.g. in original text cited in a discussion), `<hi rend="grantha">` remains available. This is because script is not encoded with rendition outside the edition, but I assume you still wanted a way to display transliterated grantha characters differently.
I do not recall when this revision was made, but certainly not recently. Probably around the time we were discussing the script codes. It was certainly meant to replace the original usage of `<hi rend="grantha">` (I have just now corrected a typo caused by incomplete revision: the example `<seg rend="grantha" rendition="class:38768 maturity:83213">` was closed by `</hi>`), and I am sure that this revision would not have taken place without your approval.
So can we keep the EGD as it is now?
If any files still use `<hi rend="grantha">` in the edition div (or in apparatus lemmas or readings), these can be mechanically changed to `<seg rend="grantha" rendition="class:38768 maturity:83213">`.

**Comment by manufrancis** [comment]
Dear Dan,
Fine! Let us keep the EGD as it is now.
I will see with Michaël for the automatic change and the specific display (bold) of transliterated Grantha.
PS: I think you have somewhere a list of automatic changes to be implemented on the DHARMA files; maybe add to this list the change of `<hi rend="grantha">` to the correct encoding `<seg rend="grantha" rendition="class:38768 maturity:83213">` in `<div type="edition">` as well as in `<div type="apparatus">`, as I might still use `<hi rend="grantha">` as a short-hand encoding.

**Comment by danbalogh** [comment]
Sorry, I copied and pasted mechanically. The correct form is `<seg rendition="class:36768 maturity:83213">` (no `@rend="grantha"`).

**Comment by manufrancis** [comment]
Thanks! Noted!
