### ISSUE TITLE
display of <header> of Textpart

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#198]
@ajaniak : according to EGD 3.4.3, "the content of editorial headers will replace the title auto-generated from @n (and @subtype, if present) in display (see Example 3.4.3.B to Example 3.4.3.D below)". 

however, this replacement does not yet seem to be implemented.

the following code 

`<div type="textpart" subtype="zone" n="1"><head xml:lang="eng">Originally planned layout</head>`

is displayed like this

<img width="306" alt="Capture d’écran 2022-12-23 à 14 20 45" src="https://user-images.githubusercontent.com/835603/209342923-85013b01-ef42-491b-a333-6a4ad4b3acb2.png">

I think we intended for the diplay to be only this:

<img width="298" alt="Capture d’écran 2022-12-23 à 14 19 45" src="https://user-images.githubusercontent.com/835603/209342796-6950c8b0-0400-4963-a501-b8bff81db031.png">

Also, whenever there is no `<header>` to replace the attributes on `<div type="textpart">`, there should not be a space inserted between "Textpart" and the following ":" in the display. (That's a French habit, not an English one.)

**Comment by danbalogh** [comment]
Actually, the word "Textpart" should never be displayed (so the colon after it should not exist either). "Textpart" is not a proper English word but an EpiDoc technical term that should not be visible to the end user, just as we don't display e.g. "Milestone" as such. When there is no `<header>`, then the label should contain only the value of `@subtype` when present, preferably converted to an uppercase initial, and the value of `@n`, without any conversion. See Example 3.4.3.A in the EGD, and the rest of the examples under 3.4.3 for what Arlo is suggesting here.
