### ISSUE TITLE
<corr> displayed twice

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#20]
Chère Axelle,
<corr> is displayed twice, in green and in black. We need just the green

![image](https://user-images.githubusercontent.com/905870/77661312-c204a900-6f7a-11ea-8af9-b92db6647ef0.png)

**Comment by ajaniak** [comment]
Should be resolved, can you confirm please ?

**Comment by manufrancis** [comment]
Bingo!
Yes, confirmed.
Thanks
