### ISSUE TITLE
why does note number 9 appear in italics?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#202]
`<p>This, the oldest dated inscription of East Java, is of great historical interest and has been edited several times. After the discovery of the main fragment, a posthumously published provisional transcription by J. L. A. Brandes (<bibl rend="omitname"><ptr target="bib:Brandes1913_01"/></bibl>), and a more thorough study by F. D. K. Bosch (<bibl rend="omitname"><ptr target="bib:Bosch1916_01"/></bibl>, with numerous corrections and additions in <bibl rend="omitname"><ptr target="bib:Bosch1923_02"/></bibl>), discovery of further fragments necessitated a revised edition by Bosch (<bibl rend="omitname"><ptr target="bib:Bosch1924_02"/></bibl>).  However, the most reliable, indeed virtually flawless, edition is that of J. G. de Casparis (<bibl rend="omitname"><ptr target="bib:Casparis1941_01"/></bibl>). Thirty years later, H. B. Sarkar (<bibl rend="omitname"><ptr target="bib:Sarkar1971-1972_01"/></bibl>), and also in an article published separately, just one year earlier (<bibl rend="omitname"><ptr target="bib:Sarkar1970_03"/></bibl>) pretended to give a more reliable interpretation than that of his predecessors, but at least his decipherment is not more reliable at all.<note>Sarkar’s readings normalize the spelling and are unreliable especially in the matter of final consonants (notably <foreign>ṁ/m</foreign>).</note> A photo of an excellent inked estampage, showing large parts of lines 10–21, was included as plate 1 in <bibl><ptr target="bib:Brandes1913_01"/></bibl>; both of Bosch' publications also photographic reproductions, but De Casparis (<bibl rend="omitname"><ptr target="bib:Casparis1941_01"/><citedRange unit="page">498</citedRange><citedRange unit="note">7</citedRange></bibl>) has warned that they are often misleading. A useful photograph of the main fragment is available as OD 743. Moreover, the stone is accessible at the National Museum in Jakarta (stone D.113), where I was able to verify the published readings on 6 July 2011. Only variant readings from De Casparis' edition are systematically noted in my apparatus, and I have also recorded all the philological observations made by L.-Ch. Damais (<bibl rend="omitname"><ptr target="bib:Damais1952_01"/></bibl>). I refer for the sake of convenience only to Sarkar's 1970 publication, not to the one of 1971.</p>`

<img width="940" alt="Capture d’écran 2023-01-08 à 09 42 51" src="https://user-images.githubusercontent.com/835603/211178180-578dccab-e11a-4644-9cef-864ae4850b88.png">

**Comment by ajaniak** [comment]
<img width="961" alt="Capture d’écran 2023-01-09 à 11 19 31" src="https://user-images.githubusercontent.com/33328906/211286143-202d6ca0-8963-4aff-ad81-fbcb2637208a.png">
It should be good
