### ISSUE TITLE
display of lost medial plates

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#203]
As per EGD §3.5.5, @wayanjarrah and I encode a missing fifth plate as follows:

```
<lb n="4v6" break="no"/>han· raṅga hle, 1, sovaṁ-so<supplied reason="omitted">vaṁ</supplied>, si hujuṁ, si runda, si lalu, si tanayan·, si nāmanta, vahuta rā<add place="below">ma</add>, si darmmā,</p>
                         <pb n="5r"/><gap reason="lost" quantity="6" unit="line"/>
                         <pb n="5v"/><gap reason="lost" quantity="6" unit="line"/>
<p part="F"><pb n="6r"/><lb n="6r1"/> ken· blaḥ, 1, sovaṁ-sovaṁ, tlas· kabyāpāran· taṇḍa rakryān·, muAṁ piṅhai vahuta rāma, tinana
```

The display is like this:

<img width="867" alt="Capture d’écran 2023-01-11 à 11 51 51" src="https://user-images.githubusercontent.com/835603/211720542-3e0086a7-390e-4ebf-8dc9-d93e791305d8.png">

I'd expect there to be indications for "plate 5r" and "plate 5v", as we gave for "plate 6r", and the gap of six lines to be stated for each face.

**Comment by danbalogh** [comment]
I agree that this is how the display should happen. I suppose this is simply a small anomaly caused by the process of merging adjacent lacunae (e.g. lost and illegible bits) into a single set of brackets, and that Axelle can sort it out easily.

**Comment by danbalogh** [comment]
Clarification: I agree that the display should happen as Arlo expects.

**Comment by ajaniak** [comment]
The lack of display is inherited from Epidoc since their model is based on <lb/> and not  on <pb/>
