### ISSUE TITLE
small imperfections in display of dipl. ed. in tfd-sanskrit-philology

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#204]
- [x]  in cases of double `<fw>`, the second doesn't get properly displayed, because we had not expected folio numbers displayed both right and left (**this is something that might also occur in inscriptions, so all also our epigraphic transformation needs to be adjusted to make it possible to display such a scenario**)

<img width="206" alt="Capture d’écran 2023-01-31 à 12 41 25" src="https://user-images.githubusercontent.com/835603/215691271-44a688af-11bd-4062-8d23-63275b46c3f4.png">

- [x] italics for `<foreign>` should not be applied to the display of intervening milestone tags (**this problem was recently solved in the display of epigraphic editions**)

<img width="978" alt="Capture d’écran 2023-01-31 à 12 44 18" src="https://user-images.githubusercontent.com/835603/215691945-7fe6d9d1-0f2b-462f-9851-da77eeed5f77.png">

**Comment by ajaniak** [comment]
a provision have been added in the css. it will take some time to be applied

**Comment by ajaniak** [comment]
<img width="978" alt="Capture d’écran 2023-02-01 à 12 33 10" src="https://user-images.githubusercontent.com/33328906/216031748-94f24204-c1b7-459f-95cf-a0a8b7c3a272.png">

**Comment by arlogriffiths** [comment]
what about displaying the contents and place(s) of `<fw>` all immediately to the right of the square brackets for `<pb>` (so we can apply colors in case editorial tages like `<choice>` are applied to the contents of `<num>`) and stating explicitly the value of @place?

in the example above, it would like like this:

[Folio 153v] left: 153 right: 153

everything would be grey except the values of `<num>` which would be black in this (simple) case.

**Comment by arlogriffiths** [comment]
ok, the display could be something like this

[Folio 153v] #1 153 #2 153

and if only one fw is present then 

[Folio 153v] 153

**Comment by ajaniak** [comment]
the codes have been made
<img width="782" alt="Capture d’écran 2023-02-02 à 09 37 34" src="https://user-images.githubusercontent.com/33328906/216273266-ed5465ae-6dfb-4af6-92ec-e771d0aaa867.png">
