### ISSUE TITLE
@value of <num> if a number needs correction

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#208]
In case there is an error to correct in a number, should the @value be the one actually written or the one post-correction?

which of the following is correct?

-`<num value="18"><choice><sic>1</sic><corr>2</corr></choice>8</num>`
-`<num value="28"><choice><sic>1</sic><corr>2</corr></choice>8</num>`

**Comment by arlogriffiths** [comment]
another case in Pamintihan 3v6

**Comment by danbalogh** [comment]
Hmm, this is weird. Have some posts been deleted from this thread? I'm 100% positive that I answered this question long ago. I may have forgotten to post my comment after writing it, but I also received an email alert during my recent leave which said Arlo had added the comment "another case in Pamintihan 3v6", and I don't see that here either.

In any case, assuming that I never sent my reply, here it is now with apologies for the delay. The answer is that neither is correct; the num tag should be included within the choice, not outside it, as per EGD §7.1.3. The example there only shows a single-digit numeral corrected to another single-digit numeral. In a multi-digit numeral using place value notation, the entire number will then need to be included in the markup: 

`<choice><sic><num value="18">18</num></sic><corr><num value="28">28</num></corr></choice>`

I can make this explicit in the EGD if you wish.

**Comment by danbalogh** [comment]
Done
