### ISSUE TITLE
multiple <p>s in <handDesc>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#209]
Dear @ajaniak ! 

In line 61 of DHARMA_encodingTemplateInscription_v03.xml, we read:

"If you need to identify individual hands (EGD §7.5/) in addition to one or more paragraphs of general palaeographic description..."

This suggests that even if one doesn't need to describe individual hands, it should be possible to organize the contents of `<handDesc>` in more than a single `<p>`. I have tried this in [tfc-nusantara-epigraphy/xml/DHARMA_INSIDENKPamintihan.xml](tfc-nusantara-epigraphy/xml/DHARMA_INSIDENKPamintihan.xml) and the display doesn't know how to deal with more than a single paragraph. 

Can this be changed on the display side, or should I try something different on the encoding side?

Thanks!

**Comment by ajaniak** [comment]
dear @arlogriffiths, 

it should be good.

<img width="937" alt="Capture d’écran 2023-04-07 à 12 25 34" src="https://user-images.githubusercontent.com/33328906/230594035-d2783834-e10f-4dfa-9f39-c7a362837e93.png">
