### ISSUE TITLE
Adding ranks and roles to names

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#21]
Reading the §§ indicated by Annette in her 2018 publication (_New Horizons in Indology: H.G. Sastri comm. vol._), I note, p. 36: “And particularly those activities which were labelled as _likhita_, 'written', are not always clear.” Which reminds me of myself writing _écrivain_ with quotation marks (2017, in French, p. 464) for the subject of a form of _likh_- in Pallava copper-plate grants, when his exact role was not made explicit. I note in your article, Annette, that you use also the term "author".
I suggest for the values of the values of the subtype of `<roleName>`:
"writer" instead of "scribe" for the subject of a form of _likh_-
"author" instead of "composer"
If it happens that we have a subject of a form of _likh_- and that we know, from other words of the record, that he is also the "author", we can tag it as follows:
`<persName type="brahmin" subtype="author writer">bhaṭṭa</persName>` 
Axelle, can you confirm that I am right?
BTW, there is already a TEI element `<author>`. Could it be used too or instead?

**Comment by ajaniak** [comment]
The use of `<author>`is expected within a bibliographic reference and most of the time in the context of the `<teiHeader>`. I wouldn't recommend choosing such a tag and honestly I am not sure you would be able to encode it since the element itself requires a very limited range of containers: 
```
- core: <analytic>, <bibl>, <monogr>
- header: <editionStmt>, <titleStmt>
- msdescription: <msItem>, <msItemStruct>
```

**Comment by AnneSchmiedchen** [comment]
Frankly speaking, I had originally "composer", not "author" (for German "Verfasser") in my text, but my American colleague (a Byzantinist from the FoundMed project) suggested that I take "author" instead of "composer". However, I still like "composer", and would hence suggest that we keep "composer" for this role.
