### ISSUE TITLE
<note> directly after <lem>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#210]
@ajaniak —

do you understand why there is no space inserted to the left of the • in this apparatus entry?

<img width="351" alt="Capture d’écran 2023-04-07 à 18 22 40" src="https://user-images.githubusercontent.com/835603/230600888-33110a68-292e-44db-b154-3ec1b2db9375.png">

A

**Comment by ajaniak** [comment]
which file is it?

**Comment by arlogriffiths** [comment]
Again Pamintihan
________________________________

**Comment by ajaniak** [comment]
Thanks. It seems there was so space in the code. I have added one 

<img width="709" alt="Capture d’écran 2023-04-07 à 13 41 09" src="https://user-images.githubusercontent.com/33328906/230603109-346aa7b0-f4c1-4b10-bd49-7889bf365742.png">
