### ISSUE TITLE
Display of lines that span multiple faces

### ISSUE THREAD

**Issue by wayanjarrah** [erc-dharma/project-documentation#213]
Hi Axelle,

I'd like to ask about the HTML visualisation of the following encoding situation, where an inscription ([Kayu Ara Hiwang](https://erc-dharma.github.io/tfc-nusantara-epigraphy/workflow-output/html/DHARMA_INSIDENKKayuAraHiwang.html) in this case) has lines that cross multiple faces. A typical couple of lines are encoded like this

`<lb n="3"/><milestone unit="face" n="A"/>ta<unclear>tag</unclear>anya, pala gagānya, Ityevammādi sapinasu
<milestone unit="face" n="b" break="no"/>knikanaṁ vanuA I <milestone unit="face" n="C"/>kayu Ara hivaṁ sinusuk· rake vanuA poḥ, sīmani pa<milestone unit="face" n="d" break="no"/>rhyaṅan Iṁ parivu<lb break="no" 
n="4"/><milestone unit="face" break="no" n="A"/>tan· muAṁ gumavaya Ikanaṁ UAt· I parivutan· <milestone unit="face" n="b"/>sakahalānya pa
<lb n="4"/>hayūn·‚ tan deyan· pagaL̥ sakaL̥ḥ, nāhan· vu<milestone unit="face" break="no" n="d"/><unclear>Aṁ</unclear> <gap reason="lost" quantity="1" unit="character"/> <unclear>ha</unclear>jya rika
`

Currently, these `<milestone unit="face"` tags are displayed with a rather large oval that includes the word "Face" every time, which in this case of this inscription makes each line quite hard to read:

<img width="909" alt="Screenshot 2023-04-20 at 10 29 22 pm" src="https://user-images.githubusercontent.com/40281167/233480776-3776cd5b-db56-49d7-a3d8-2c1260b18716.png">

Could we remove the word "Face" from these milestones, so that they are smaller and do not affect the legibility of the text so much?

I think my proposed solution is only desirable when we have `<milestone>` inside `<lb>`. In normal cases where the `<milestone>` is pagelike, the current situation of having "Face A" etc. seems fine.

**Comment by ajaniak** [comment]
Dear @wayanjarrah, 

I have updated the script by adding a condition to avoid the display of `@unit`with the value face. 

Best, 

<img width="1017" alt="Capture d’écran 2023-04-24 à 10 36 12" src="https://user-images.githubusercontent.com/33328906/233945432-d9dded56-368a-46e6-bb87-22506d14a8c2.png">

**Comment by ajaniak** [comment]
Thanks for you feedback; closing this
