### ISSUE TITLE
modify CSL

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#216]
current export

Bosch, F. D. K. 1922. “De oorkonde van Sendang Sedati.” Oudheidkundig verslag, no. Bijlage B: 22–27.

where "Bijlage B" is the contents of the "issue" field

should become

Bosch, F. D. K. 1922. “De oorkonde van Sendang Sedati.” Oudheidkundig verslag (Bijlage B): 22–27.

**Comment by ajaniak** [comment]
The CSL has been updated
<img width="737" alt="Capture d’écran 2023-04-27 à 11 40 14" src="https://user-images.githubusercontent.com/33328906/234824218-16d0d2e2-64b8-461e-a478-7a5f1b3d5208.png">

**Comment by arlogriffiths** [comment]
is this to everyone's satisfaction?
   @danbalogh @manufrancis @AnneSchmiedchen 
if yes, we can close this "issue" issue.

**Comment by danbalogh** [comment]
I don't know the background to this but have no objection to displaying the contents of "issue" in parentheses, it looks fine. What I don't understand is why publications in this journal don't seem to have volume numbers, only issue numbers. By my logic, the publication year should be duplicated in the "volume" field if there are no volume numbers starting from 1. This seems to be so for some entries in the Journal of the Royal Asiatic Society, but many of those also don't have volume numbers.

**Comment by manufrancis** [comment]
No objection, but most of all, no time for tiny details of display of bibliography.
