### ISSUE TITLE
Weird error messages in validation

### ISSUE THREAD

**Issue by samana218** [erc-dharma/project-documentation#219]
I have been using Oxygen to encode inscriptions on my Macbook. I tried encoding gaps for the first time and got error messages that say I can either have "quantity" or "extent" but not both (screen shot shows the errror messages), when I have not included "extent" at all. I also get these error messages when I try to open other team members' files, even though the files were validated on their computers. My files, when cloned, are also validated on other computers. I tried to open the same file on the Windows computer in my office (assuming it was a problem with my MacBook) and am oddly facing the same problem there as well. 

I also get error messages when I encode verses saying the value of attribute "part" is invalid, even though I have only the attribute "meter" included. 

I would really appreciate any help with this! 

 @michaelnmmeyer @ajaniak 
![Screen Shot 2023-05-11 at 4 56 41 PM](https://github.com/erc-dharma/project-documentation/assets/108796921/ff335e53-57bd-446e-8770-2958032fcec5)

**Comment by danbalogh** [comment]
The files are in https://github.com/erc-dharma/tfb-kalyanacalukya-epigraphy but as Samana says, we have not been able to reproduce these error messages on my or Annette's computer, while conversely, the same sort of errors popped up in my files we tried to validate on Samana's computer. Any help would be much appreciated.

**Comment by ajaniak** [comment]
Have you updated your oxygen lately?

**Comment by ajaniak** [comment]
Then, can you check that the parameters for the schema are still the right one? In the preferences, XML / XML Parser / RELAX NG, the box "Add default attribute values" shouldn't be ticked.

**Comment by ajaniak** [comment]
Great! Glad to read it is solved! 
have a good evening.

Best,
