### ISSUE TITLE
No <lb/> for copper plates

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#22]
No `<lb/>` are displayed for manuscripts, see [Marsmu.xml](https://github.com/erc-dharma/tfc-nusantara-epigraphy/blob/master/provisional/arlogriffiths/Marsmu.xml): bug should be resolved to answer issue #18.

**Comment by arlogriffiths** [comment]
I don't understand. Marsmu.xml is not an edition of a manuscript, but for a copper plate.
