### ISSUE TITLE
schema for critical editions: attributes for <add> and <del> in <subst> not offered

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#221]
@michaelnmmeyer —

When encoding a bit of critical apparatus for a text edition as per ERC, I should have at my disposal the entire gammut of encoding options for diplomatic editions as described in EGD. See EGC 8.6. I believe the following is correctly encoded (as per EGD 4.4.3) yet the critical editions schema rejects it and does not offer the needed values for the @rend attributes on `<del>` and `<add>` in `<subst>`. See screenshots. Can you fix this soon?

<img width="686" alt="Capture d’écran 2023-06-02 à 11 50 10" src="https://github.com/erc-dharma/project-documentation/assets/835603/d0edaea8-dc92-4780-af76-ea4264c47884">

<img width="681" alt="Capture d’écran 2023-06-02 à 11 50 32" src="https://github.com/erc-dharma/project-documentation/assets/835603/c827dacf-8eb7-4e90-b7fb-fc2d7be05d0b">

<img width="1296" alt="Capture d’écran 2023-06-02 à 11 53 57" src="https://github.com/erc-dharma/project-documentation/assets/835603/9c022c6b-4147-4a64-93ee-89c542c00c50">

<img width="1076" alt="Capture d’écran 2023-06-02 à 11 58 08" src="https://github.com/erc-dharma/project-documentation/assets/835603/d3135c79-c169-4816-938f-ff0a31efb008">

**Comment by michaelnmmeyer** [comment]
This should be OK for the two attributes you mentioned (see 96138c4).

**Comment by arlogriffiths** [comment]
my file still doesn't validate. see screenshot.

<img width="1139" alt="Capture d’écran 2023-06-03 à 08 42 52" src="https://github.com/erc-dharma/project-documentation/assets/835603/1a04a397-f085-4ad2-92f5-1570d3f29baa">

**Comment by michaelnmmeyer** [comment]
It works on my side. But then the file you're modifying is
apparently DHARMA_DiplEdSvayambhuKirtya774.xm, which doesn't use the
critical edition schema. Can you send me the full file?

Le sam. 3 juin 2023 à 08:43, arlogriffiths ***@***.***> a
écrit :

**Comment by arlogriffiths** [comment]
no, the file I am talking about is [https://github.com/erc-dharma/tfd-nusantara-philology/blob/master/editions/DHARMA_CritEdSvayambhu.xml](https://github.com/erc-dharma/tfd-nusantara-philology/blob/master/editions/DHARMA_CritEdSvayambhu.xml). it is a critical edition.

**Comment by michaelnmmeyer** [comment]
The current version of DHARMA_CritEdSvayambhu.xml
<https://github.com/erc-dharma/tfd-nusantara-philology/blob/master/editions/DHARMA_CritEdSvayambhu.xml>
validates
fine for me in VS Code. Are you still having this issue?

**Comment by arlogriffiths** [comment]
Yes, the file is still shown to be invalid by VSC, both for the present issue and for #222. See screenshots.

<img width="1601" alt="Capture d’écran 2023-06-09 à 14 31 17" src="https://github.com/erc-dharma/project-documentation/assets/835603/f0843985-75c6-4f9b-8848-02a76811ac5b">
<img width="1597" alt="Capture d’écran 2023-06-09 à 14 34 10" src="https://github.com/erc-dharma/project-documentation/assets/835603/d6861ff6-5555-491d-8f6d-9af7edf3223e">

**Comment by michaelnmmeyer** [comment]
It seems that, for some reason, your editor is picking up an old (locally cached?) version of the schema instead of the latest one. I see this on my side:

![image](https://github.com/erc-dharma/project-documentation/assets/11620332/6b1e00f4-0f79-42fd-b3b1-412c9ceacfb0)
![image](https://github.com/erc-dharma/project-documentation/assets/11620332/b4322bae-0034-4f4e-8e05-e572c4644f21)

I suggest we take a look at this during our next talk about the DCF. However, this won't address the root problem, which is that we're not using a common toolchain for validating texts. The current issue as well as #219 and #222 stem from software incompatibilities and differences of configuration.

**Comment by arlogriffiths** [comment]
thanks for fixing #222. now only this issue remains. although Oxygen and VSC delcare the XML to be valid, VSC does still complain about the present issue.

<img width="1613" alt="Capture d’écran 2023-06-23 à 08 53 29" src="https://github.com/erc-dharma/project-documentation/assets/835603/1d7bccc9-deda-455b-8951-7518abe32220">

**Comment by michaelnmmeyer** [comment]
You can try to replace the initial processing instructions with the following:

```
<?xml-model href="https://raw.githubusercontent.com/erc-dharma/project-documentation/master/schema/DHARMA_CritEdSchema_v02.rng" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://raw.githubusercontent.com/erc-dharma/project-documentation/master/schema/DHARMA_CritEdSchema_v02.rng" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<?xml-model href="https://raw.githubusercontent.com/erc-dharma/project-documentation/master/schema/latest/DHARMA_CritEdSQF.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
```

Besides that, you can try deleting VSCode's caches (but make a backup beforehand!). On Linux, the relevant directories seem to be `~/.config/Code/CachedData/*` and `~/.config/Code/Cache/Cache_Data`.

It might be easier to wipe everything out and to reinstall VSCode, in particular if you haven't a custom configuration.
