### ISSUE TITLE
schema for critical editions: <span type="omissionStart"/> and <span type="omissionEnd"/>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#222]
Dear @michaelnmmeyer !

When I open the file DHARMA_CritEdSvayambhu in Oxygen, it is at this time virtually error-free (only the problem in issue #221 is flagged).

However, when I open the same file in VSC, I also get error messages for use of `<span type="omissionStart"/>` and `<span type="omissionEnd"/>`. See screenshots.

<img width="1290" alt="Capture d’écran 2023-06-03 à 08 53 21" src="https://github.com/erc-dharma/project-documentation/assets/835603/496be15f-8228-4edd-9562-e256e730f2ae">

<img width="1260" alt="Capture d’écran 2023-06-03 à 08 55 14" src="https://github.com/erc-dharma/project-documentation/assets/835603/18cb832b-7d66-4786-ae66-d4afd5e00de1">

Can you help me help VSC understand there are no errors here?

Thanks.

**Comment by michaelnmmeyer** [comment]
I can't use my usual toolchain for now (my computer broke, I'm using
another one), and I don't yet have a license for oXygen, so I'll check this
when I've access to all the necessary tooling. For now I'm working on the
cham dictionary.

Le sam. 3 juin 2023 à 08:56, arlogriffiths ***@***.***> a
écrit :

**Comment by arlogriffiths** [comment]
sorry, this issue of @type attributes of `<span>` now appears not to be editor-dependent. I get the same validation failure in Oxygen now. it is becoming necessary to solve this issue.

<img width="1504" alt="Capture d’écran 2023-06-21 à 11 21 22" src="https://github.com/erc-dharma/project-documentation/assets/835603/090ee8b7-51e6-49ec-a804-6149f8729c6e">
