### ISSUE TITLE
@source with more than one bibliographic reference

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#23]
I haven't take into account the possibility of more than one reference inside `@source`for `<rdg>`. Feature must be added for the content of the tooltip, see [Marsum.xml](https://github.com/erc-dharma/tfc-nusantara-epigraphy/blob/master/provisional/arlogriffiths/Marsmu.xml) for such a use and  #16.

**Comment by arlogriffiths** [comment]
I don't understand. No `@source` ever seems to be declared on `<bibl>` in that file (and I don't know what it would mean).
