### ISSUE TITLE
Symbol taxonomy (`<g>` element)

### ISSUE THREAD

**Issue by michaelnmmeyer** [erc-dharma/project-documentation#232]
@manufrancis @arlogriffiths @danbalogh 

I have prepared a basic data file that maps symbol names (the values of `g/@type`) to their visual representation, their description, etc. See [here](https://github.com/erc-dharma/project-documentation/tree/master/gaiji).

So far, I have copied the contents of the [supplement to the EGD](https://docs.google.com/document/d/1glfyQnFqPrbVOYzegfjKIOVrc-vMgznEQ1iNsFf7DE8), and I added two images as examples. The idea of making this public is that people can look up symbols, add new ones, or provide images when possible.

You can see how images are used in [DHARMA_INSDk00029](https://dharman.in/display/DHARMA_INSDk00029) (the spiral at the very top of the inscription).

If you are OK with the basic protocol, I will hook up the DHARMA app with the data files in `project-documentation`. (For now, I am using copies in my own repository.)

**Comment by danbalogh** [comment]
Hello, this is really nice and ingenious, and the facility to display images is also great. To my mind, symbol display is extremely low priority, however. I think there are on the one hand a lot of things that are far more important to sort out; and on the other, the fancier the web display, the more problematic it will be to copy and paste the transformed output into other software (for use in a printed publication, a PPT presentation, an email, etc.). What I mean is that dingbat characters aren't supported in a lot of fonts and may not be preserved correctly when pasted to a different application.
For the same reason, I think `prefer_text` should be the default option, or even the only possible way to go ahead. If an image has been supplied by the editor, displaying it as a tooltip would be great, but I would not want an image interspersed with the text. Also, I think image display is only useful if it shows the end user exactly what a certain symbol looks like in the original. Thus, no images should be assigned to symbol types; what we might rather need is a way to link specific instances of symbols to a specific zone of a specific image file in our repository. But this is complicated and absolutely not essential or urgent, and should not be attempted at the moment.
If an exception is to be made, e.g. if we do want svg graphics as generic representations of various kinds of spirals, the ones in the Symbol Taxonomy were drawn in SVG and I'll send them to you (Michaël) in a moment.

With these caveats, I think the protocol itself is perfect and can go ahead.

**Comment by michaelnmmeyer** [comment]
Thank you! Duly noted.
