### ISSUE TITLE
encoding <note> in bibliography

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#238]
@danbalogh —

I am pretty sure we have discussed this before, but don't remember what conclusion was reached.

The following use of `<note>` is rejected by the schema:

`<bibl n="Da">
                   <ptr target="bib:Damais1955_01"/>
                   <citedRange unit="page">49</citedRange><note>1r1–1v1 only</note></bibl>`

Moving the `<note>` inside `<citedRange>` does not help.

Is there any way we can encode such information in compliance with the schema?

**Comment by danbalogh** [comment]
It should certainly not be inside `<citedRange>`.
EGD §9.4.2 on bibliography (also noted in §10.4.1 on notes) explicitly permits using `<note>` as the last child of a `<bibl>` element in the structured bibliography (but not elsewhere: outside the structured bibliography, notes must go after the `<bibl>` element).
According to my comment in the gdoc, this was introduced in or before February 2021, and I think the schema did not object back then.

So I'm tagging @michaelnmmeyer here: if feasible, please change the schema so it allows this use of note. If this is counterrecommended for some reason, then we'll need you to advise us on how notes of the kind Arlo needs in his example above should be encoded in the bibliography.
