### ISSUE TITLE
dharmanin/catalog

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#239]
I am getting this error message for all pages of your provisional site, @michaelnmmeyer :

<img width="1668" alt="Capture d’écran 2023-12-18 à 05 22 29" src="https://github.com/erc-dharma/project-documentation/assets/835603/47dea45e-c117-4a51-9176-2b4656a375ba">

**Comment by michaelnmmeyer** [comment]
Fixed in https://github.com/michaelnmmeyer/dharma/commit/e9e8a8431dee1f1b71770e0c24427a3387077d7d
