### ISSUE TITLE
display of translations of inscriptions and error message "Missing in bibliography"

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#248]
Dear @michaelnmmeyer —

You are no doubt aware of this, but just as a reminder: the display of translations of inscriptions apparently still needs quite a lot of your attention. For example, contrast the rather plain formatting of the translation at https://dharman.in/display/DHARMA_INSIDENKAlasantan with the carefully designed display of the same at https://erc-dharma.github.io/tfc-nusantara-epigraphy/workflow-output/html/DHARMA_INSIDENKAlasantan.html. I am referring especially to the way lists are displayed.

By the way, I think this kind of error message is unwanted.

<img width="464" alt="Capture d’écran 2023-12-20 à 17 56 34" src="https://github.com/erc-dharma/project-documentation/assets/835603/7cc21b0a-f78d-4319-b547-e1741a17cef7">

 I guess it means that the bibliographic entry is not defined in the `<div type="bibliography">` of the given inscription, but it is not the case that all references cited in commentary, notes, etc., must be encoded in the inscription's bibliography. For instance, general reference works such as the dictionary Zoetmulder 1982 are not include in the inscription's bibliography by most encoders, I think — in any case not by me.

**Comment by michaelnmmeyer** [comment]
OK for lists formatting.

For bibliographic references, I see two options:

1. I automatically add the missing bibliographic entry to `<div type="bibliography">` if it is not already there, and make the reference point to it. However, I cannot tell if the entry should go under "primary" or "secondary", and we have not specified for now how bibliographic entries should be sorted (if they should be sorted at all).
2. I generate a global bibliography for the project (or maybe per study area, per author, etc.), and make the bibliographic reference point to that.

Which do you prefer?

**Comment by michaelnmmeyer** [comment]
The bibliography of EIAD should definitely not be that slow to load. It will be OK in DHARMA.

**Comment by michaelnmmeyer** [comment]
Lists display fixed in https://github.com/michaelnmmeyer/dharma/commit/9dd746898f05997123f837b355542a18ba615aa6

**Comment by arlogriffiths** [comment]
Thanks. So can we close this?

**Comment by michaelnmmeyer** [comment]
OK.
