### ISSUE TITLE
Page breaks no longer displayed when not followed by text

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#249]
Copperplate sets often contain uninscribed pages; generally, the outer pages of a multipage set (i.e. the recto of the first plate and the verso of the last) are blank. In DHARMA we encode `<pb/>` elements corresponding to the blank pages as well as the inscribed pages. (The reasons, if I recall correctly, were on the one hand to make it explicit that these pages exist; and on the other hand to allow a possible future implementation of linking images to every page including the blank ones.)
Earlier on, these page breaks were displayed in the HTML transformation, but for some time now, they do not appear. Thus, e.g. for the following code
`
<pb n="1r"/><p><pb n="1v"/><lb n="1"/>svasti ...</p>
`
The output was formerly
<sup>⎘ plate 1r </sup>
<sup>⎘ plate 1v 1</sup>svasti

while now it is just
<sup>⎘ plate 1v 1</sup>svasti

I think the former is preferable. If these page breaks were suppressed for a reason, then I can accept that but would like to know the reason. If this is a bug, then it should be corrected. Not urgent.

**Comment by arlogriffiths** [comment]
I definitely agree that the former is preferable.

**Comment by manufrancis** [comment]
I concur with Arlo.

**Comment by michaelnmmeyer** [comment]
I addressed that in the new display. Compare e.g. the beginning of https://dharman.in/display/DHARMA_INSPallava00004 and https://erc-dharma.github.io/tfa-pallava-epigraphy/texts/htmloutput/DHARMA_INSPallava00004.html.

**Comment by danbalogh** [comment]
Thanks. But does this only affect the transformation you use for dharman.in? What about that used for github.io? And what about the transformations I can run for myself from Oxygen? I'm using start-edition-with-bibl.xsl to transform my XML to HTML (from which I then make copies into my offline corpus in Word), and that still gives me the old behaviour. Is that because it just takes time for your update to trickle down, or are the old xsl scenarios deprecated? (If the latter, can you advise me what scenario I should use for offline transformations for my own purposed?)

**Comment by michaelnmmeyer** [comment]
@danbalogh Sorry for the confusing statement, I should have made things clearer.

The github.io website uses stylesheets in `project-documentation/stylesheets` to transform inscriptions. The local transformations you are doing in Oxygen also use them. However, the dharman.in website does not. It uses a completely different transformation mechanism that is devised to make full-text search convenient.

The old transformation scenarios will be superseded eventually. I have not yet written a scenario for the new transformation in Oxygen, but I will do that soon.

**Comment by danbalogh** [comment]
Thanks for the clarification.
