### ISSUE TITLE
Epigraphia Carnatica

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#25]
I am currently encoding a Pallava inscription from Karnataka (see https://github.com/erc-dharma/tfa-pallava-epigraphy/blob/master/texts/xml/tfaPallava252.xml), which was edited in Epigraphia Carnatica [EC] vol. 10.

I have thus:
(1) created a repository "E-EpigCarnatica" in Zotero.
(2) created a new value for @unit in `<citedRange>`, that is, `<citedRange unit="part">`, as the EC volumes contains multiple pagination in Arabic numerals.

Dear Dan, if you agree with this new value or have another proposal, could you please update the EG?
Dear Axelle, I am not sure the ZG needs any update.
Dear Annette and Florinda, could you upload in sharedocs (in the PDF Library) the high resolution scans obtained from our Tubingen colleagues.

**Comment by danbalogh** [comment]
"part" sounds good to me for this purpose. I've added it to the EG. I'm not sure the definition is very straightforward, so I mention EC as a specific example there. Improvements to the definition of "part" are welcome (please comment in the EG).

**Comment by AnneSchmiedchen** [comment]
Dear Manu, I could upload the Tübingen files in sharedocs, but not from my home. I might go to the institute (unofficially) again next week, and then I could try to do this. I do not know whether Florinda would be able to do it from her home.

**Comment by manufrancis** [comment]
Dear Annette and Dan, thanks!
