### ISSUE TITLE
Zotero Style, journal abbreviation

### ISSUE THREAD

**Issue by wayanjarrah** [erc-dharma/project-documentation#257]
Dear @michaelnmmeyer,

When creating bibliographies in Zotero, I am accustomed to using the standalone desktop application. I have been using the CSL files updated by Axelle 9 months ago, available at [project-documentation/bibliography](https://github.com/erc-dharma/project-documentation/tree/master/bibliography). However, I note that there are two versions of the CSL file ("DHARMA_modified-Chicago-Author-Date_v01.csl" and "DHARMA_modified-Chicago-author-date_abbreviation_v01.csl"). As far as I can tell, their only difference is that one represents journal titles in full while the other applies the journal abbreviation if it exists. 

Here is the difference in output:
Noorduyn, Jacobus. 1978. “Majapahit in the Fifteenth Century.” _Bijdragen Tot de Taal-, Land- En Volkenkunde_ 134 (2–3): 207–74. [DOI: [10.1163/22134379-90002587](https://doi.org/10.1163/22134379-90002587)].
Noorduyn, Jacobus. 1978. “Majapahit in the Fifteenth Century.” _BKI_ 134 (2–3): 207–74. [DOI: [10.1163/22134379-90002587](https://doi.org/10.1163/22134379-90002587)].

Both of these are valuable options and I want to keep both available to me, which means I need to import both CSL files as separate styles in my Zotero. However, when I try to import the Abbreviation version, it overwrites the original version. Zotero cannot hold both styles at the same time. Am I right in thinking that the reason for this is that they both have identical content in this line:
`<id>https://github.com/erc-dharma/project-documentation/blob/master/bibliography/DHARMA_modified-chicago-Author-Date_v01.csl</id>`

where as in reality, the one called abbreviation should have the following?
`<id>https://github.com/erc-dharma/project-documentation/blob/master/bibliography/DHARMA_modified-chicago-author-date_Abbreviation_v01.csl</id>`

If so, then is it okay for me to push that small change to the ID field of the Abbreviation CSL to make sure that both templates have different IDs and so can be imported as separate styles?

Thanks,
Jarrah

P.S. @arlogriffiths for the separate issue of the choice between representing issue as (#) as opposed to no. #, I have found that downloading the CSL again and re-importing into Zotero has given me the desired format of (#). So this must have been one of the last updates the Axelle put through last year.

**Comment by michaelnmmeyer** [comment]
Dear @wayanjarrah,

Sure, you can go on. I think you also need to modify `<link href="[...]" rel="self">` (use the same URL you indicate in `<id>`).

**Comment by arlogriffiths** [comment]
@wayanjarrah : can this issue be closed now?

**Comment by michaelnmmeyer** [comment]
Yes.
