### ISSUE TITLE
Permit <certainty> in <gap>

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#258]
Today I have encoded a case of "lines possibly lost", i.e. where it is not clear whether there were additional lines inscribed at the end of an inscription. EGD §5.4.6 following EpiDoc guidelines prescribes `<certainty match=".." locus="name"/>` within the `<gap>` element for such a case, but the schema does not currently permit this. This should be permitted. This is the only case where a `<gap>` may be non-empty, and this element (with these attributes and values) is the only thing allowed inside it.

Alternatively, we could dispose of this way of encoding. I do not know if anybody has used it anywhere else, and I do remember that I was not very eager to adopt this complication from the epidoc guidelines. I can live with just encoding the text and mentioning possibly lost lines in the commentary or layout description for human readers only, provided that the PIs can also live with that.

**Comment by michaelnmmeyer** [comment]
OK, this is corrected in https://github.com/erc-dharma/project-documentation/commit/7028d016150a9c93cf860d8ac33d4243d03bec03.

**Comment by manufrancis** [comment]
@danbalogh 
I think I used `<certainty match=".." locus="name"/>` within the `<gap>` element, followin EGD.
I can also "live with just encoding the text and mentioning possibly lost lines in the commentary or layout description for human readers only"
