### ISSUE TITLE
bug with search?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#259]
I am only getting this result at the moment:

<img width="1410" alt="Capture d’écran 2024-01-12 à 14 51 35" src="https://github.com/erc-dharma/project-documentation/assets/835603/ec702fa9-4273-47fd-8af7-1fc60cf738b3">

**Comment by michaelnmmeyer** [comment]
Fixed in https://github.com/michaelnmmeyer/dharma/commit/d5415e7f5a4a4f35207f3398e87fc073ec15b6e1.
