### ISSUE TITLE
New DHARMA ID for encoders

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#261]
@michaelnmmeyer michaelnmmeyer 

Dear Michaël, I have updated recently the DHARMA ID list:
https://github.com/erc-dharma/project-documentation/commit/6432a24fbf3cbf8064905e55bcb665c2d70a475c#diff-a6c4b1d2995ff4f4a6d100a10ac0d3134538c1804a90c7c2e2c48fe71bce91e5

I have create two new IDs:
- "ants" for Antonella Santoro (ansa was not available, as already used for Anjaneya Sarma).

- "matr" for Margherita Trento

As far as I can see, these are not displayed on dharman.in.

Could you fix these when back at work, next week?

Thanks.

**Comment by michaelnmmeyer** [comment]
Done!
