### ISSUE TITLE
installation problem and possible bug with Zotero CSL DHARMA-modified CMS 17th ed.

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#262]
@michaelnmmeyer —

Today I noticed a bug in the CSL I have so far been using for standalone use (the one made by Axelle based on CMS 17th ed.).

The bug effects hyphenated author names, as the name of the editor **Parasher-Sen** in the entry Prasad2004_01, which is exported as follows:

Prasad, B. R. 2004. “Cultural Map of Ᾱndhra Deśa.” In Kevala-Bodhi: Buddhist and Jaina History of the Deccan (The BSL Commemorative Volume), edited by Aloka **Parasher**, B. Subrahmanyam, and Emani Siva Nagi Reddy, 1:76–97. Delhi: Bharatiya Kala Prakashan.

I then decided to open a github issue and in the process noticed that my CSL file is called "deprecated" at [https://github.com/erc-dharma/project-documentation/tree/master?tab=readme-ov-file#bibliography](https://github.com/erc-dharma/project-documentation/tree/master?tab=readme-ov-file#bibliography).

Next I tried to uninstall that CSL file while installing the one I'm supposed to use, and ran into further trouble. See the following screenshots. 

<img width="571" alt="Capture d’écran 2024-02-18 à 10 28 17" src="https://github.com/erc-dharma/project-documentation/assets/835603/f61bc665-d34b-4fa9-926a-41d306753223">

<img width="492" alt="Capture d’écran 2024-02-18 à 10 27 23" src="https://github.com/erc-dharma/project-documentation/assets/835603/3b469807-c009-4bd5-9f20-e8fc754f563d">

1. Can you help solve these problems?
2. Finally, it seems the mopst specifically relevant readme file needs to be updated: https://github.com/erc-dharma/project-documentation/blob/master/bibliography/DHARMA_addingCSLZotero_v01.md.

**Comment by arlogriffiths** [comment]
even though the new CSL does not seem to be installed, now I do notice a new behavior concerning journakl titles, which are indicated in abbreviation rather than in full. example:

Sewell, Robert. 1895. “Some Buddhist Bronzes, and Relics of Buddha.” JRAS, 617–37. [http://www.jstor.org/stable/25197278].

for standalone usage, we need to have a CSL which does not show this behavior, or we need to have the choice.

**Comment by arlogriffiths** [comment]
And the revised CSL that apparently is installed altough I thought installation had failed (and I don't see the file named DHARMA_modified-chicago-author-date_Abbreviation_v01.csl in my folder zotero/styles) also shows a new behavior regarding book sections, no longer with "In" before the title:

Shah, Umakant Premanand. 1975. “Jain Bronzes: A Brief Survey.” Aspects of Jaina art and architecture, edited by Umakant Premanand Shah and Madhusudan A. Dhaky, 269–98. Ahmedabad: Navajivan Press.

I do not disagree with these new behaviors for the DHARMAbase but they are practically a nuisance as I am midway formatting bibliographies for a large edited volume and have already created hundreds of bibliography items with the old CSL. For for each new item I format I now have to make (and think of making) several manual changes.

**Comment by michaelnmmeyer** [comment]
In the entry Prasad2004_01 (https://www.zotero.org/groups/1633743/erc-dharma/search/Prasad/titleCreatorYear/items/U6BA5EY8/item-list), the editor name is set to "Parasher", not "Parasher-Sen", so I do not see an issue here. Do you have other examples?

As concerns the CSL stylesheet you mentioned (DHARMA_modified-chicago-author-date_Abbreviation_v01.csl), there is a syntax error which went unnoticed so far. The stylesheet does not seem to be installed on your computer because Zotero derives the filename from an XML id within the file, and because this id has not been modified after the file was renamed in the repo. I will fix both issues in a v2.

For the volume you are working on, I suggest you keep using the old CSL stylesheet you used so far.
