### ISSUE TITLE
display of large space

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#264]
Would it be possible to slip the word "semantic"  before the first occurrence of "space" and then remove everything from the semicolon onward?

<img width="722" alt="Capture d’écran 2024-03-24 à 17 46 57" src="https://github.com/erc-dharma/project-documentation/assets/835603/5602d96d-3703-4c16-8d31-2197076bd8fe">

Are there many implications for other display issues?

**Comment by michaelnmmeyer** [comment]
There are three basic variations of the same tooltip, depending on the value of the `space/@type` attribute:

When `@type` is empty or = "semantic":

> Large space (about ${quantity} ${unit}s wide); semantic space

When `@type` = "vacat"

> Large space (about ${quantity} ${unit}s wide); vacat space; the area was left blank when the rest of the inscription was engraved, possibly with the intent to be filled later on

When `@type` = "unclassified"

> Large space (about ${quantity} ${unit}s wide); unclassified significant space that does not fit other categories

I am not sure how to reformulate cases 2 and 3.

**Comment by arlogriffiths** [comment]
suggestion:

1. Large semantic space (about ${quantity} ${unit}s wide)
2. Large vacat space (about ${quantity} ${unit}s wide)
3. Large unclassified space (about ${quantity} ${unit}s wide)

**Comment by michaelnmmeyer** [comment]
OK, done
