### ISSUE TITLE
display of <fw>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#269]
@michaelnmmeyer —

Am I right that we currently don't have any display yet of `<fw>` on dharmalekha? If so, can this lacuna be filled?

See e.g. https://dharmalekha.info/texts/DHARMA_INSIDENKAirKali where `<fw>` is encoded but not displayed at the start of 6v.

There is an old issue that is related (#204), though discussion focussed there on the display set up  by Axelle and on a concrete (rare) scenario in the EGD-based encoding of a diplomatic edition of a manuscript.

**Comment by michaelnmmeyer** [comment]
What do you want to be displayed? Axelle did this:

![image](https://github.com/erc-dharma/project-documentation/assets/11620332/ad40ccc9-796a-4dc5-a939-0a3ac675a2fa)

Currently I display  `(⎘ 3r)`, should I use `(⎘ 3r #3)`?

**Comment by arlogriffiths** [comment]
May I suggest you take into account some of the issues raised and solutions proposed in #204? Re-reading the discussion there, I am not sure I understand Axelle's objection to making reference to the value of @place in the display.

**Comment by michaelnmmeyer** [comment]
Done in https://github.com/michaelnmmeyer/dharma/commit/095223473297916decc12e44087b8028b74781ee.

**Comment by arlogriffiths** [comment]
Thanks. So now the page number is displayed in Physical mode:

<img width="1261" alt="Capture d’écran 2024-03-30 à 09 38 19" src="https://github.com/erc-dharma/project-documentation/assets/835603/a420d4d6-30b8-441c-aa04-8125eab1105d">

I am happy with this. But since the contents of `<fw>` is part of the (para)contents of the given text and ought to be harvestable for instance when all instances of a given number are searched for, I think the last number 6 should appear in black and not in grey and we should probably have some manner of including the `<fw>` also in logical display (or in any case in the textual contents that would be exported to txt and that are accessible to the search engine). 

Suggestion: siraruda(⎘ 6v)(fw left: 6)(6v1)ha

I can't indicate changes of color. I mean everything in this example to be grey except "siraruda", "6" and "ha".

As implied by my reference to #204, the system must be set up to be able to deal with any rare cases of more than one `<fw>` for the given `<pb>`.

**Comment by michaelnmmeyer** [comment]
I added `<fw>` to the full display. You can see examples at: https://dharmalekha.info/texts/DHARMA_INSTestPhysical.
