### ISSUE TITLE
Metadata spreadsheet's review

### ISSUE THREAD

**Issue by alevivier** [erc-dharma/project-documentation#27]
**About the digital resource's metadata** (AS and AG)
(1) Origin of the metadata: Are we the „creators“ of the metadata? In fact, the metadata can have different sources. We may have created some of the metadata, other parts may be based on information derived from published editions, etc. I do not quite understand how to handle this.

(2) How to manage the modification of the metadata? By whom they had been modified, when and type of modification. It should be described at a raw level, not for all the file.

**About text's metadata:** (MF)
(1) Does your field "designation" correspond to <title>?
If so, maybe use "title" instead of "designation" OR state this correspondence?

(2) As for dates, most of my inscriptions are dated as follows: "Year n of [king's name]".
I guess I have to put this in the field "Others era" as follows: "Year n of [standardised king's name]".
Often the year is accompanied by other informations (nth day of the current year; month, fortnight, season). I guess I have to put this after "Year n of [standardised king's name]". 

(3) "Exact date CE"
Often it is not known precisely. For an approximate date, use "ca" before the date?
Is it also the place to record dates (different than the one above) by other editors/researchers?
If not, where would you put such an information.

(4) Does your field "comments" correspond to `<div type="commentary">`? 
If so, maybe use "commentary" instead of "comments" OR state this correspondence?

(5) As for language and script, what about bilingual (strict or un-strict) inscriptions?
Can we duplicate language and script and indicate lines?
E.g.
For language: 
Sanskrit (lines 1, 12-14)
Tamil (lines 2-11)
For script:
Grantha (lines 1, 12-14) 
Tamil (lines 2-11), [and, when this is the case] with occasional Grantha characters.

**About artefact's metadata:** (MF and AS)
(1) "Origin place (Site)", "Find place (Site)", "Preservation place (Institution or site)".
I guess we add after the site name, district/province and state.
(2) Dimensions: I assume that we have to fill in the information about the height and width of a copper plate under „format“ (not under „copper-plate format“). What are we expected to do if there is more than one plate, and the dimensions of the individual plates differ from each other? Just duplicate?
(3) Categories „Indicating the presence of not …“ >>  „Indicating the presence or not …“
I think that the sequence should be: hole(s) – ring(s) – seal.
(4) Category „Indicating the presence o[r] not of a hole / ring“: Quite frequently we have more than one hole / ring, often two holes / rings. So just yes / no might not be sufficient.

**Comment by alevivier** [comment]
(1) Does your field "designation" correspond to <title>?
-> yes, "designation" correspond to "title". We can use it instead of "designation"

**Comment by alevivier** [comment]
(4) Does your field "comments" correspond to <div type="commentary">?

-> yes, and actually it would be better to use "commentary" as there will be different types of comment allowed for groups of metadata.

**Comment by alevivier** [comment]
(4) Does your field "comments" correspond to `<div type="commentary">`?

-> yes, and actually it would be better to use "commentary" as there will be different types of comment allowed for groups of metadata.

**Comment by arlogriffiths** [comment]
I prefer designation, because ‘title’ to me sounds like something internal to the document in question. In the case of inscriptions, it is almost always the editor who chooses how to name or designate a text, hence I prefer ‘designation’. Should everyone agree on this point, of course it can be explained that we mean the thing that will appear in <title> in TEI.

Le 8 avr. 2020 à 17:47, alevivier <notifications@github.com<mailto:notifications@github.com>> a écrit :



(1) Does your field "designation" correspond to <title>?
-> yes, "designation" correspond to "title". We can use it instead of "designation"

**Comment by alevivier** [comment]
(5) As for language and script, what about bilingual (strict or un-strict) inscriptions?

-> for bilingual inscriptions, you can duplicate the column. The languages and scripts are controlled vocabularies, so the list will be strict. It would be a solution to add a field "comments on script and/or language" that allows you to describe the division of the text. This solution could be matched to `<scriptDesc>`

**Comment by arlogriffiths** [comment]
sorry, I think Adeline’s answer should have been ‘no’. in no case does her spreadsheet concern anything that would end up in the `<div type="commentary">` of a TEI edition. I don’t know excatly what TEI equivalent she has in mind, but it would be something in the teiHeader. as appears from her response, I think Adeline means comments on certain text-related metadata. not comment on the text itself.

**Comment by alevivier** [comment]
About the comments in the spreadsheet:
Sorry, Arlo is right. I thought that maybe you would want to put some elements of commentary, but not the complete commentary.
For now, we have 4 types of specific comments: 
- comments about the history of the artefact (discovery, move, etc) which can correspond to `<history>`
- comments about the location of the artefact (e.g. top of the north wall of the temple Y) which can correspond to `<history>`, `<origin>`, `<origPlace>`
- comments about language/script which can correspond to `<scriptDesc>` or `<handDesk>` or `<langUsage>`
- comments about the iconography/decoration `<decoDesc>`

The information above have to be strictly in these fields. For the field « comments on text » it will depend on what you would like to describe. But if you think that the other fields are sufficient to describe in prose all the specificities of the artefact and the text, we can remove it.

**Comment by alevivier** [comment]
About hole(s), ring(s), seal: 
-> ok I will change the sequence and add the possibility to indicate the number.

**Comment by ajaniak** [comment]
Discussion moved to the Spreadsheets. Closing this since it is not active anymore in github.
