### ISSUE TITLE
XML display

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#271]
@michaelnmmeyer — is it intentional or not that the XML display shows formatted Apparatus after `</TEI>`? It seems unwanted to me.

<img width="1648" alt="Capture d’écran 2024-03-30 à 08 43 13" src="https://github.com/erc-dharma/project-documentation/assets/835603/acdbeb43-4831-4d9e-a2a7-94b5078fb7bc">

**Comment by arlogriffiths** [comment]
sorry, now I understand that this is related to the fact that XML view is only offered behind Edition (which in turn explains why previously you were not including the teiHeader).

since we already have (on the left) the External Link to the entire xml file, we could either return to the previous situation where the XML tab under Edition offers a view only of the contents of `<div type="edition">` or remove the XML tab altogether. in the latter case, it might be nice if the xml data were shown via the External Link in the same pretty manner that we now have behind the XML tab, rather than the completely plain manner that we get via the External Link at this time.

**Comment by arlogriffiths** [comment]
<img width="1186" alt="Capture d’écran 2024-03-30 à 09 10 54" src="https://github.com/erc-dharma/project-documentation/assets/835603/153828c4-68aa-4e07-9a68-0f81617c2822">

**Comment by michaelnmmeyer** [comment]
The XML source indeed should not appear under the "Edition" section. I plan to add a "View Source" button in the sidebar for showing the XML in a pretty format.

The "XML File" link I added under "External Links" is meant for downloading the file. I will also add a "Download Plain Text" link, and (hopefully) "Download PDF".

**Comment by arlogriffiths** [comment]
@michaelnmmeyer : shall we close this now?

**Comment by michaelnmmeyer** [comment]
Yes, this is implemented. I will probably change the appearance of the "Source view" button later on.
