### ISSUE TITLE
value of @source in <lem> not displayed

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#275]
Is something wrong with my encoding or is the non-display of the siglum G based on @source and `<bibl>` an imperfection of the database code?

```
<app loc="3">
	<lem source="bib:Griffiths2019_01">Urām̃</lem><rdg source="bib:Cabaton1904_01">uraṅ</rdg>
</app>
<app loc="3">
	<lem source="bib:Griffiths2019_01">rāṣ<orig>t</orig>ra</lem>
	<rdg source="bib:Cabaton1904_01">rāṣṭra</rdg>
</app>
...
  <bibl n="G"><ptr target="bib:Griffiths2019_01"/><citedRange unit="page">200-201</citedRange><citedRange unit="figure">4</citedRange></bibl>
```

<img width="289" alt="Capture d’écran 2024-04-07 à 12 58 47" src="https://github.com/erc-dharma/project-documentation/assets/835603/e7107ead-324a-4153-9aa9-20641664a08f">

**Comment by michaelnmmeyer** [comment]
I did not check `lem/@source`, now fixed.
