### ISSUE TITLE
absence of <listApp> not flagged by schema

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#276]
@michaelnmmeyer —

I have just noticed that there are files where the `<app>` entries are assembled in `<div type="apparatus">` without being wrapped in `<listApp>`. This contravenes EGD rules. I think the schema should be set to flag this as an error in the same way that other non-fatal errors are. See the screenshot from tfc-campa-epigraphy/DHARMA_INSCIC00148.xml.

<img width="637" alt="Capture d’écran 2024-04-07 à 16 29 34" src="https://github.com/erc-dharma/project-documentation/assets/835603/67bd8c94-e3a0-43e0-b3ec-ffe278c040ce">

**Comment by michaelnmmeyer** [comment]
Addressed in 9bde319.
