### ISSUE TITLE
dharmelekha offline

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#277]
@michaelnmmeyer — how long will this last?

<img width="1183" alt="Capture d’écran 2024-04-08 à 08 17 14" src="https://github.com/erc-dharma/project-documentation/assets/835603/4a2d0826-3406-4ee1-be07-bf784b7b8b8f">

**Comment by michaelnmmeyer** [comment]
I probably stopped it by mistake yesterday, it is back online.
