### ISSUE TITLE
EGC 7.1.3.2 and 6.3.2: multiple values for @sameAs, @copyOf or @corresp 

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#279]
@michaelnmmeyer —

This refers to the file DHARMA_CritEdSarasamuccayaVararuci on tfd-nusantara-philology.

I don't understand why some cases where multiple txt: values are recorded on an attribute of `<note>` in `<listApp><app>...</app></listApp>` are flagged as encoding errors while others are not. See screenshots. Can you intervene so that this manner of encoding is never flagged as error? (As explained in EGC 7.1.3.2, this usage of txt: is useful only in theory but has no practical impact on transformation, so good reason to be very lenient about it.)

<img width="1367" alt="Capture d’écran 2024-04-12 à 16 51 48" src="https://github.com/erc-dharma/project-documentation/assets/835603/f9d680a8-d06d-4a54-9cbf-850baddf2355">

<img width="1329" alt="Capture d’écran 2024-04-09 à 11 30 18" src="https://github.com/erc-dharma/project-documentation/assets/835603/8949f907-327d-4436-8b22-05e7ce81dc02">

**Comment by arlogriffiths** [comment]
also in this case, presence of more than one txt: value cause an error message. iof I remove one of them, the error disappears. there should be no error message at all, as use of multiple values must be allowed. by the way, I don't understand why the error message speaks of "witness(es)" which suggest a connection with @wit, which is irrelavant here.

<img width="1594" alt="Capture d’écran 2024-04-10 à 19 34 42" src="https://github.com/erc-dharma/project-documentation/assets/835603/7a0441a9-bac4-4f3b-9892-0f2cad7c4531">

@michaelnmmeyer : I think it should be easy to make the necessary tweaks in the schema. I expect the file will validate and correctly displayed once these small tweaks are made.

**Comment by michaelnmmeyer** [comment]
The problem is that, in the TEI model, [`@sameAs`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.linking.html#tei_att.sameAs) and [`@copyOf`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.linking.html#tei_att.copyOf) are supposed to contain a single reference. The [`@corresp`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.linking.html#tei_att.corresp) attribute, on the other hand, can enumerate several references.

I can change `@sameAs` and `@copyOf` in such a way that multiple references are allowed, but our documents will not be TEI-compatible anymore.

**Comment by arlogriffiths** [comment]
Thanks. Then I think the appropriate solution is to make one `<note>` per parallel with @sameAs or @copyOf.

Example:

`<note sameAs="txt:MBh_12.080.018 txt:MBh_13.037.011"/> `

becomes

```
<note sameAs="txt:MBh_12.080.018"/> 
<note sameAs="txt:MBh_13.037.011"/>
```

@michaelnmmeyer : please confirm, so we can execute. We will also need to specify these constraints in the next version of EGC.

**Comment by michaelnmmeyer** [comment]
This would work, yes.

**Comment by arlogriffiths** [comment]
Fixed with [3ccc1f1410a175872384fda37ec8fd4047e20ad1](3ccc1f1410a175872384fda37ec8fd4047e20ad1). 

@nicholaslua : you may click on that link to see all the changes I've made. We will gradually need to come up with a manner of encoding that 

1. captures the information on parallels in an accurate human-readable form, focusing on the Sanskrit text that our coimpiler is actually likely to have selected from
2. allows the machine to extract a corcordance of passages from various Sanskrit texts that have parallels in Sārasamuccaya

@michaelnmmeyer : if you think we will definitely want to move to another manner of encoding to achieve aim 2 while remaining TEI compliant, and we'd better move now rather than later, please react now. Otherwise please close this issue.

**Comment by arlogriffiths** [comment]
Sorry, the link wasn't working. How about this one: https://github.com/erc-dharma/tfd-nusantara-philology/commit/3ccc1f?

Choose the right file and press Load Diff.

**Comment by michaelnmmeyer** [comment]
The encoding is fine, but the format of references (`txt:xxx`) will have to be specified at some point. People should also think to put the files they are referring to under version control.
