### ISSUE TITLE
copyright <respStmt>

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#28]
For the record and discussion, summary of previous exchanges.

Presently in the XML template:
`<resp>EpiDoc Encoding</resp>`
`<resp>intellectual authorship of edition</resp>`
`<!-- the copyright is that of the encoder(s) -->`

Arlo's comment:

> I think it doesn't make sense **not** to let the person who claims intellectual authorship of the edition in `<respStmt>` to have the first claim on copyright.
> So why not say something like this?
> "the copyright is that of the scholar who is the intellectual author of the edition (whether or not he is project member), as indicated under `<respStmt>`, followed by the person responsible for EpiDoc encoding"

Manu's comment:

> Note that there seems to be no copyright for Indian government publications beyond 60 years. See https://en.wikipedia.org/wiki/Copyright_law_of_India#Types_of_works_protected:
> "until sixty years[12] from the beginning of the calendar years next following the year in which the work is first published [13]"
Epigraphia Indica, South Indian Inscriptions, etc. are Government publications.

Possible cases:
(1) entirely new or (more or less) substantially revised edition
(2) reproduction of an earlier edition no more under copyright 
(3) reproduction on an earlier edition under copyright

The contentious case is (3).

Notes: 
* There is/seems to be a certain tolerance concerning the copyright on the edition of primary sources. I remember discussions on this topic appear from time to time on the INDOLOGY list (D. Wujastyk).
* There must be a rule about the percentage of a work that can be cited verbatim in a further publication (like the library rule that you can xerox only a certain percentage of a book).
* We might for case (3) directly contact the copyright holder and invite him to make or accept that we make an online DHARMA edition.
* The EPM will contact CNRS DR (délégation régionale) on this matter.

Further issues: 
* What about the (c) of reprints (e.g. 1986 ASI reprints of 19th and early 20th c. ARIEs)

**Comment by ajaniak** [comment]
Dear all, 

During the workshop, you had ask to a list about a practice in digital edition and for EPIDOC. 
I had looked into several project about what they do and don't with their `<resp>`. I only kept only a short list of projects in my sum up, but there isn't any consensus. 
It seems a lot of projects avoid using a direct copyright in the XML and only put it on the whole project. But even then, you meet differences between institutions, projects or persons mentioned as the "bearer". 

Best, 

Project| Project type | Persons mentioned in the `<teiHeader>` | Copyright
-- | -- | -- | -- 
Campa|EPIDOC| Only editor | Copyright with editors
EAID|EPIDOC | Principal, editors as general and contributors, assistants and DH | Copyright with editors
IPSOS|EPIDOC | Have chosen translator in `<TitleStmt>` | NONE
I.Sicily |EPIDOC| in `<TitleStmt>`: editor and principal & `<respStmt>`: Jonathan Prag and ITs | NONE
Papyri.info |EPIDOC| NONE(but you need an account to use their VRE) | Copyright on the project name
DFHG | EPIDOC|editors and `<respStmt>` for editorial involvement | NONE
IRT |EPIDOC| editor | NONE
Aphrodisias |EPIDOC| Editors presented like a bibliographical reference | NONE
SARIT |TEI| Every person involved with the files, even the subcontractors | Copyright on the project name
MENOTA |TEI| Editor or `<respStmt>` for everybody involved | NONE
BetaMasaheft |TEI| Everybody as editor with its key | NONE

**Comment by manufrancis** [comment]
Thanks, Axelle!

Further memo notes on this issue:

* As for copyright, does it make sense in the era of OA, to which we, as ERC project, are contractually committed?
See D. Wujastyk email : Today, the importance of copyright in our field is mainly that it's the copyright-holder alone who has the right to release a piece of work under a Creative Commons license.
* On ERC OA, see:
https://erc.europa.eu/managing-project/open-access
Articles 29.2, 29.3. Check GA.
* Find India Copyright Act 1957
https://en.wikipedia.org/wiki/Copyright_law_of_India#Types_of_works_protected

**Comment by danbalogh** [comment]
As I'm trying to resolve loose threads in the Encoding Guide (Diplomatic), can one of you have a look at the pertaining section (§11.1/The responsibility statement) and help me decide what the Guide should say on this topic? As far as I am concerned, it's perfectly OK if the Guide just says something like "fill out this section as instructed in the XML comments found in the template". But if there's anything specific that you've already agreed on and want to see in the EGD, please let me know.

**Comment by manufrancis** [comment]
Dear Dan, I am afraid there is not yet a consensus on this issue, as we await feedback, if any will come (e.g. from the CNRS juridical services).
I concur with your opinion that it's perfectly OK if the Guide just says, for the moment, something like "fill out this section as instructed in the XML comments found in the template" and leaving as example the following:

```
<respStmt>
<resp>EpiDoc Encoding</resp>
<persName ref="part:jodo">
<forename>John</forename>
<surname>Doe</surname>
</persName>
</respStmt>
```
				
This §11.1 will be updated in a further version of the EGD, when we will be clear on the issue.

**Comment by arlogriffiths** [comment]
I agree with Manu’s advice.

A


Le 7 mai 2020 à 13:14, manufrancis <notifications@github.com<mailto:notifications@github.com>> a écrit :



Dear Dan, I am afraid there is not yet a consensus on this issue, as we await feedback, if any will come (e.g. from the CNRS juridical services).
I concur with your opinion that it's perfectly OK if the Guide just says, for the moment, something like "fill out this section as instructed in the XML comments found in the template" and leaving as example the following:

<respStmt>
<resp>EpiDoc Encoding</resp>
<persName ref="part:jodo">
<forename>John</forename>
<surname>Doe</surname>
</persName>
</respStmt>


This §11.1 will be updated in a further version of the EGD, when we will be clear on the issue.

**Comment by danbalogh** [comment]
Thanks to both of you. I'll handle the EGD.

**Comment by manufrancis** [comment]
Great! Thanks!
