### ISSUE TITLE
paleographic remarks

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#280]
Dear @chhomkunthea  and @salomepichon,

Thank for your responses on this point.

- Kunthea said: "For the palaeographic remark, I’m wondering if we can say that “The akṣaras are characteristic of the tenth century CE.”"
- Salomé said: "In my XML file, I note the paleographic remarks inside a `<p>` within the `<handDesc>`. Is it the information you're looking for?  Personally I would write something along the line of "The scribe has made a use of a cursive script"."

Kunthea's response corresponds to what I had asked you to do some time ago, though I would now prefer to write "lettering" instead of "akṣaras". I don't remember at the momen t why I asked you to put such remarks in your XML files and in the present display, they are no longer shown, though this might change as @michaelnmmeyer's work on the database and display of metadata advances.

In any case, please gradually revise all your files using a sentence with the pattern `<p>The lettering is characteristic of the tenth century CE.</p>` Don't hesitate to ask if you encounter problems.

I am sending a copy to @chloechollet and @danbalogh for their information and for any input they may wish to give.

**Comment by salomepichon** [comment]
Dully noted, thanks! 
Is it still advised to elaborate a bit more if we have things to say? For instance, in the file of the inscription K. 444 (https://dharmalekha.info/texts/DHARMA_INSCIK00444), that I studied in my Master's thesis, I made the following remarks:

<p>The lettering is characteristic of the tenth century CE.</p> (--> Freshly added)
<p>The scribe has made a use of a cursive script, caracterised by its irregularities. Single-downstroked ra alternate with double-downstroked ra. Likewise, both complete and abbreviated ña were engraved.</p>
<p>The text of the inscription contains a lot of glyphs signs separating segments of the text, mostly middle dot.</p>
<p> The inscrition was chiselled on face B, making its reading more difficult.</p>

Should I stick to a more simple observation, or can I keep the rest?

Best,

**Comment by chhomkunthea** [comment]
Dear Arlo and Salomé,

If I remember well, in one of our virtual meetings (Salomé, Chloé and me), we mentioned that the little sentence (“The lettering is characteristic of … century CE”) should be in the <handDesc> and that further palaeographic observations should be added in the commentary. 

I have applied this “rule” to several files. Can I keep the additional observations in the commentary or move them back to the <handDesc>, with the little sentence?

Best,
Kunthea

**Comment by arlogriffiths** [comment]
There is no hard rule forbidding such remarks in the commentary, Kunthea, but I think in principle remarks that touch on Paleography should be assembled in `<handDes>`. See EGD 11.2.1 ("The hand description"). It is rather unlikely that I ever recommended you to make palaeographic observations in  any other part of an XML file, so it may have been a misunderstanding on your part.

**Comment by chhomkunthea** [comment]
Well noted with thanks! I will put the palaeographic remarks in the <handDesc>.

Best,
Kunthea
