### ISSUE TITLE
Mixed milestones and transliteration issues in DHARMA_INSCIK00523

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#281]
Dear @chloechollet , 
Michaël and I have been talking about limiting the degree of complexity in our use of milestones (#270 , but you don't need to read that). In the course of this, [DHARMA_INSCIK00523](https://dharmalekha.info/texts/DHARMA_INSCIK00523) has come up as one of the few encoded texts where there is more than one kind of pagelike milestone (i.e. `<milestone type="pagelike"/>` with different kinds of `@unit`) within a document, namely:

- face A with the label "Face A"
- item B with the label "Face B"
- item C with the label "Face C"
- item D with the label "Face D"

I assume this is a stela of four faces, and the first milestone is correct, while the other three should have "face" instead of "item" as their units. If that is right, then please correct the milestones. If the situation is more complicated than that, then please tell me more about the layout and I'll help work out a good encoding scheme for it.

Incidentally, while looking at inscriptions involving mixed milestones with Kunthea and Arlo today, Arlo has noted that there seem to be problems with the encoding of this file. In many (perhaps all) places where a dot for virāma is expected, we see instead a space. We've only looked at the file on dharman.in, so there's a chance that your XML is correct and something has got lost in the transformation, but please check the file. @chhomkunthea can help you sort out the correct encoding; or if the problem is not present in your XML files, then @michaelnmmeyer will need to be involved to make sure that it also appears on dharman.in.

**Comment by chloechollet** [comment]
Dear @danbalogh 
Thank you for pointing out this problem, I've corrected the label and also the virāma, which I had saved for later because of the very poor condition of the rubbings.

**Comment by danbalogh** [comment]
Great, thanks.
