### ISSUE TITLE
@rendition for an inscription in Kannada script and language?

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#285]
@danbalogh 

Would this do?

`<div type="edition" xml:lang="kan-Latn" rendition="class:83217 maturity:83215">`

Where "class: 82317" = Brāhmī and derivatives
and "maturity:83215" = vernacular Brāhmī-derived script

NB: this applies to https://dharmalekha.info/texts/DHARMA_INSKarnataka00001

**Comment by danbalogh** [comment]
I suppose so.

**Comment by manufrancis** [comment]
Fine. Thanks!
