### ISSUE TITLE
small presentational improvements

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#288]
I don't know how closely our final website is going to resemble what dharmalekha.info looks like now, but I hope the plan is to evolve incrementally from what it looks like today. If that is correct, may I suggest the following small changes?

1. When Apparatus for an epigraphic edition is substantial, it stands in the way of jumping back and forth between edited text and translation. What about offering the option to collapse display of Apparatus?

2. I'd like hyphens to be auto-replaced by en-dashes in display of the values of @n on `<p>` in `div type="translation">`.

3. At the top left of our screens, it might be nice if instead of the DHARMA button we could have a button using our special logo (the one that is also our avatar at https://github.com/erc-dharma).

**Comment by manufrancis** [comment]
I am fine with 1, 2, and 3.

@michaelnmmeyer 
You will find the logos here
https://sharedocs.huma-num.fr/wl/?id=3xfoJH7gvpJnkJ5NQJCBwpL52elYtstJ

**Comment by michaelnmmeyer** [comment]
OK, noted. For the logo, though, we will probably need a smaller one.

**Comment by arlogriffiths** [comment]
maybe for this specific context use the same reduced version as in our github avatar

![image](https://github.com/erc-dharma/project-documentation/assets/835603/cb583439-8f6b-4da8-8ab0-a3b1425932ee)

or the whole bull if possible but without the word dharma.

**Comment by arlogriffiths** [comment]
looks great! thanks!

<img width="522" alt="Capture d’écran 2024-04-26 à 18 14 24" src="https://github.com/erc-dharma/project-documentation/assets/835603/1130ff1d-7d14-425f-9367-e402086a7a06">

**Comment by arlogriffiths** [comment]
I think only task 2 (hyphens to en-dash in `<p n="xxx-yyy">` in translation) remains

**Comment by arlogriffiths** [comment]
thanks for carrying out all these modifications!
