### ISSUE TITLE
https://github.com/erc-dharma/electronic-texts/tree/master/DHARMA

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#289]
Dear @michaelnmmeyer !

Does this txt file collection only get updated upon manual instruction? Might it be possible to make it a weekly a monthly automated process? In any case, could you generate an update now?

**Comment by michaelnmmeyer** [comment]
I just pushed a new export. For now, the process is not automated, because plain text conversion is not reliable. I will set up live exports when possible.

**Comment by arlogriffiths** [comment]
ok, thanks
