### ISSUE TITLE
URL in biblio. display

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#294]
@michaelnmmeyer — I am sure we have discussed this before, sorry for forgetting what the suituation is.

can URLs not be represented in the same way as DOIs, i.e. as [URL] with hyperlink?
is this why in general we're not displaying URLs recorded in zotero items at all?
and for itemType:website, like this one, we are forced to make an exception due to the nature of the case?

<img width="1039" alt="Capture d’écran 2024-04-26 à 18 13 39" src="https://github.com/erc-dharma/project-documentation/assets/835603/ac37885c-cccb-485d-8a89-6a17e1c76d27">

if actually it is possible to display URLs as [URL] with hyperlink, then I'd like all URLs to be displayed including the ones for itemType:website.

**Comment by michaelnmmeyer** [comment]
There are no restrictions on the bibliography format, we can do what we want, so OK for this.

Displaying websites URLs might still be useful for people who want to print things on paper, or if we want to produce PDF files.

**Comment by arlogriffiths** [comment]
thanks!

I am not inclined to give much (or any) importancre to the needs of people who want to print on paper; in a pdf, I presume the hyperlink could be preserved. closing this for now.
