### ISSUE TITLE
About domains

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#30]
Dear all, 

Some details about domains to follow my previous mails. 

# Regarding URL naming
I have checked the possibilities for the following domains 
www.dharma.net => already owned
https://dharma.eu/ already own by a reseller, cost €5 999 (VAT included)
https://www.dharma.org/ => already owned
https://dharma.info/ => already owned
http://dharma.academy/ => already owned but not used.

I will need to know if you have other ideas and 

# Some notions of prices
I have only checked with OVH and Gandi. Both I have already used and know they can be trusted. 
|extension|creation cost|transfer cost|renewal|owner Change|restore|Company|
|--|--|--|--|--|--|--|
|.academy|€35.84|	€30.37|	€35.84|	€0.00|€98.66|Gandi|
|.academy|€11.99 (sale, normal cost €25.99)|€25.99|€25.99|free|€75.99|OVH
|.eu|€12.00|€12.00|€12.00|	€0.00|€12.00|Gandi|
|.eu|€6.99|€3.99|€7.99|€6.99|€ 49.99|OVH|
|.info|€5.20 (sale, normal cost €20.00)|€16.95|€20.00|€0.00|€86.12|Gandi|
|.info|€1.99 (sale, normal cost €13.89)|€8.99|€12.99|free|€50.99|OVH
|.net|€17.00|	€14.00|	€17.00|	€0.00|€103.56|Gandi|
|.net|€7.99 |€7.99|€12.99|free|€50.99|OVH|
|.org|€8.06 (sale, normal cost €15.20)|€12.20|€15.66|€0.00|€102.23|Gandi|
|.org|€8.89|€8.89|€12.99|free|€50.99|OVH|

Prices don't take into account the VAT of 20%.

# About Gandi
- 2 mailboxes with 3GB storage
- 1 Standard SSL certificate 1 Year
- DNSSEC
- No web hosting, but offer a 50% off if we host something with their service.
- No information about under-domain, even in the documentation, still investigating

## POSSIBLE SUPPLEMENTARY COSTS
- Counting €12.00 for SSL certificate each year. (basic option)
- Counting a basic web hosting for static page: €72.00 reduced to €36.00 the first year.

# About OVH
- 10 Mo for web hosting
- 1 mailbox with 5GB storage
- SSL handled
- DNSSEC
Note: No possibility to create under-domain, need to take a "Offre perso" at €35.88 per year.

**Comment by arlogriffiths** [comment]
- decided to use **dharmalekha** for domain names during project brainstorm in May 2020
- Vincent Paillusson has blocked it with .info, .eu, .org on 15/06/2020
