### ISSUE TITLE
color codes for <num> and <abbr>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#302]
@michaelnmmeyer — in Axelle's display, segments marked as `<abbr>` or `<num>` were shown with a special color code. is this also foreseen on dharmalekha? I would like it to be implemented if possible.

**Comment by michaelnmmeyer** [comment]
`num` has no color, but `abbr` is already colored in brown.

I think we agreed a while ago not to use too many colors. Currently, we have:

```
.abbr {
        color: brown;
}
.sic {
        color: red;
}
.corr {
        color: green;
}
.orig {
        color: magenta;
}
.reg {
        color: blue;
}
.check {
        background-color: yellow;
}
```

And of course hyperlinks in blue.

**Comment by arlogriffiths** [comment]
Somehow the brown was not showing when I opened this issue but later I did start to see it. No problem for me not to put colors on `<num>` and the principle of not using too many colors seems good to me.

@danbalogh and @manufrancis may express themselves and the last in line can close this issue unless any disagreement arises.

**Comment by danbalogh** [comment]
I'm happy with no special colour for num and brown for abbr.
