### ISSUE TITLE
display of various types of <supplied>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#303]
At the moment, we have:

1. `<supplied reason="omitted">`
<img width="163" alt="Capture d’écran 2024-05-16 à 09 31 03" src="https://github.com/erc-dharma/project-documentation/assets/835603/288f901b-18f9-4b05-b1b3-6ebc0b786c79">

2. `<supplied reason="lost">`
<img width="141" alt="Capture d’écran 2024-05-16 à 09 31 52" src="https://github.com/erc-dharma/project-documentation/assets/835603/70963711-41c6-415b-8b5e-6f5e30b1dbaf">

3. `<supplied reason="subaudible">`
<img width="287" alt="Capture d’écran 2024-05-16 à 09 30 28" src="https://github.com/erc-dharma/project-documentation/assets/835603/46194e71-fcce-4718-be5b-a27a1bdf99c9">

@danbalogh and @michaelnmmeyer : is our use of the same brackets for cases 2 (lost) and 3 (subaudible) as intended?

I think the latter should be included under "6. Editorial intervention" at https://dharmalekha.info/editorial-conventions where it is currently still lacking.

**Comment by michaelnmmeyer** [comment]
This is as intended, as far as I am concerned. The same brackets are also used for `supplied[@reason='undefined']`.

**Comment by danbalogh** [comment]
I've added an item showing this markup to the editorial conventions. It may take a while for it to trickle down to the website.
I agree with Arlo that `<supplied reason="subaudible">` should be shown in angle brackets, like omissions, and not in square brackets, like restorations. Square brackets are generally associated with lacunae, and angle brackets generally with insertion. The display for `<supplied reason="undefined">` should remain square brackets, nothing to do about that.
If we want a display distinction between supplied reason omitted versus supplied reason subaudible, we could make the latter's font colour grey, but I do not think this is needed.

**Comment by michaelnmmeyer** [comment]
I believe we used square brackets so far because `supplied[@reason='subaudible]` also appears

**Comment by danbalogh** [comment]
Good point, thanks for raising it. Yes, indeed, in modern language contexts (translation div) the display of `supplied[@reason='subaudible]` should remain square brackets. But if that is complicated to accomplish, I can also live with square brackets everywhere. Let @arlogriffiths and @manufrancis decide.
