### ISSUE TITLE
<surplus> in logical display

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#305]
I have this chunk of code:

`tinaḍaḥ rakryān· mahāmantrī I hino śrī samaravijaya <surplus>dha<lb break="no" n="B3"/>ma</surplus> suparṇa<unclear>vā</unclear>haṇa tguh uttuṅgadeva,`

I wasn't sure whether I could wrap `<surplus>` around a chunk interrupted by `<lb>` but it doesn't cause any invalidation problem so at first sight I thought it was fine.

But when I see the display, I am not sure I approve of the segment encoded as superfluous being entirely invisible in logical display; and it can certainly not be our intention for this particular `<lb>` to become invisible in the same process.

<img width="556" alt="Capture d’écran 2024-05-18 à 09 19 04" src="https://github.com/erc-dharma/project-documentation/assets/835603/e6484a7e-9410-4556-9af6-cfe6de5ecfe6">
<img width="1208" alt="Capture d’écran 2024-05-18 à 09 18 39" src="https://github.com/erc-dharma/project-documentation/assets/835603/9e716f48-8f43-4758-a845-32e7bf2c580d">

I'd prefer {dhama} and the line beginning to be shown in both logical and physical display.

**Comment by manufrancis** [comment]
I concur with Arlo

**Comment by danbalogh** [comment]
According to our present encoding rules, `<surplus>` must be split across the line break. The correct encoding is `<surplus>dha</surplus><lb break="no" n="B3"/><surplus>ma</surplus>` and anything else should be flagged as an error by the schema. See #304 for the details.

**Comment by arlogriffiths** [comment]
Thanks for the clarification. Encoding updated.

I'll let @michaelnmmeyer close this again once he feels it's time.

**Comment by michaelnmmeyer** [comment]
Closing this as this is covered by https://github.com/erc-dharma/project-documentation/issues/304.
