### ISSUE TITLE
display of <supplied reason="subaudible">...</supplied> in translations

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#308]
this is at present displayed with ⟨...⟩, as in editions, but we want [...] in translations

**Comment by michaelnmmeyer** [comment]
You need to give me an example. Looking at https://dharmalekha.info/texts/INSBengalCharters00084, for instance, I do not see this issue.

**Comment by arlogriffiths** [comment]
See https://dharmalekha.info/texts/INSIDENKWukiran. The wrong brackets appear in `<p>`, while the correct ones appear in `<p rend="stanza">`.
