### ISSUE TITLE
Initial blessing in column-like layout

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#316]
@danbalogh 

Please have a look at this one also:

![IMG_4608 - Copie](https://github.com/erc-dharma/project-documentation/assets/905870/14921c30-e83d-4efb-a612-b3a934efde9a)

On the top of this stele we find

- on the left, in 2 lines, the blessing "hariḥ Om"
- on the right, in 1 line, the blessing "svasti śrī"

The "main" text then starts.

What would you advise?
To encode both initial blessings in `<fw>`?
And as per EGD 3.3.5, I understand I should not indicate `<lb>` in the top left blessing.

**Comment by danbalogh** [comment]
For this one, you should definitely use the guidelines for incipits, EGD §3.3.3. Forme work should primarily (and preferably only) apply to documents with actual pages or pagelike partitions. This was taken for granted in drafting the section, hence the note that the fw element must always follow the pb.

**Comment by manufrancis** [comment]
Noted. Thanks!
