### ISSUE TITLE
Display for <pb> and <fw> for copper plates

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#32]
Dear all, 

With Manu, we are facing some issues regarding the display of `<pb/>` and `<fw>`, our test case being tfaPallava006. Would that be ok for all of you if we favor in the following structure at least for proof-reading? 
```
Plates

⎘ plate 1r
⎘ plate 1v
1

(1)jitaṃ bhagavatā

śrī-vijaya-palakkaḍa-sthānāt parama-brahmaṇyasya sva- 
(2)bāhu-balārjitorjita-kṣātra-tapo-nidheḥ vihita-sarvva-maryyādasya 
(3)sthiti- vac. sthitasyāmitātmano mahārajasya śrī-skandavarmmaṇaḥ 
(4)prapautrasyā<r>ccita-śakti-siddhi-sampannasya pratāpopanata-rāja-

⎘ plate 2r
(5)maṇḍalasya mahārājasya vasudhā-talaika-vīrasya śrī-vīravarmmaṇaḥ pau- 
(6)trasya vac. deva-dvija-guru-vṛddhopacāyino vivṛddha-vinayasyāneka-go-hi- 
(7)raṇya- vac. bhūmy-ādi-pradānaiḥ pravṛddha-dharmma-sañcayasya prajā-pālana- 
(8)dakṣasya loka-pālānāṃ pañcamasya loka-pālasya satyātmano mahā-

⎘ plate 2v
2
(9)tmano mahārājasya śrī-skandavarmmaṇaḥ putrasya bhagavad-bhakti-sadbhāva- 
(10)saṃbhāvita-sarvva-kalyā¿n?<ṇ>asya prajā-saṃrañjana-paripālanodyoga-sata- 
(11)ta-sa vac. tra-vrata-¿dita-kṣitasya?<dīkṣitasya> Aneka-samar-sāhasāvamardda-la- 
(12)bdha-vijaya-yaśa<ḥ>-prakāśasya kali-yuga-doṣāvasanna-dharmmoddharaṇa-nitya-sa-

⎘ plate 3r
```
Previously, it has been asked to rend the `<pb/>` inline which creates the following display. We don't find it really clear. 
```
(7)raṇya- vac. bhūmy-ādi-pradānaiḥ pravṛddha-dharmma-sañcayasya prajā-pālana-
(8)dakṣasya loka-pālānāṃ pañcamasya loka-pālasya satyātmano mahā- ⎘ plate 2v
2
(9)tmano mahārājasya śrī-skandavarmmaṇaḥ putrasya bhagavad-bhakti-sadbhāva-
(10)saṃbhāvita-sarvva-kalyā¿n?<ṇ>asya prajā-saṃrañjana-paripālanodyoga-sata-
```
Could you let us know your opinion?

Thanks,

**Comment by danbalogh** [comment]
The display at the top looks good enough to me for checking our work while encoding. I do not know who proposed rendering `<pb/>` inline in a diplomatic/physical display, and I don't see any reason why one would want that. But, here are two points that may be relevant. 

1. Do we even need to display the contents of `<fw>` in these "proofreading" transformations? If yes, it would be essential I think to set them apart somehow, e.g. put a border around them or render them with a coloured background.
2. Wasn't the idea that in our "proofreading" transformations prose gets displayed by epigraphic line (diplomatic/physical), but verse gets displayed in a stanza structure (curated/logical)? If not, then it's OK to display everything line by line. But if verse is displayed as stanzas, then `<pb/>` (along with `<lb/>` and `<milestone/>`) will have to be displayed inline, no question about it. For that, my recommendation is still what it has always been: wrap in `<>` (or proper angle brackets) and display as superscript. And the contents of `<fw>` could be not displayed at all, or displayed in a box or something after this label.

**Comment by manufrancis** [comment]
To answer your (Daniel) initial remark:

> I do not know who proposed rendering `<pb/>` inline in a diplomatic/physical display, and I don't see any reason why one would want that.

It was a misunderstanding from our side. Sorry.

> Do we even need to display the contents of `<fw>` in these "proofreading" transformations? If yes, it would be essential I think to set them apart somehow, e.g. put a border around them or render them with a coloured background.

I am in favour of displaying it, for proofreading purpose precisely.
As for a specific display, why not?
But I find it is clear enough as it is.
![image](https://user-images.githubusercontent.com/905870/79685868-27774d00-823c-11ea-8b08-ae348f48bd5b.png)
And if unclear to the proofreader/reviewer, she/he will check the XML.
NB: a discussion for later will be on display or not display `<fw>` on the DHARMA-base.

> Wasn't the idea that in our "proofreading" transformations prose gets displayed by epigraphic line (diplomatic/physical), but verse gets displayed in a stanza structure (curated/logical)? If not, then it's OK to display everything line by line. But if verse is displayed as stanzas, then `<pb/>` (along with `<lb/>` and `<milestone/>`) will have to be displayed inline, no question about it. For that, my recommendation is still what it has always been: wrap in `<>` (or proper angle brackets) and display as superscript. And the contents of `<fw>` could be not displayed at all, or displayed in a box or something after this label.

Here is the current display:
![image](https://user-images.githubusercontent.com/905870/79685954-dcaa0500-823c-11ea-9e31-f2091c5fc637.png)
I guess we could have on the DHARMA-base different displays for those elements: one for the diplomatic/physical, the other for the curated/logical.
Your comment 

> But if verse is displayed as stanzas, then `<pb/>` (along with `<lb/>` and `<milestone/>`) will have to be displayed inline, no question about it.

is relevant, as far as I understand, in the latter case only (curated/logical).

**Comment by danbalogh** [comment]
Manu, your samples given above seem to show that stanzas will indeed be shown in curated/logical form, and so if a `<pb/>` or `<lb/>` occurs within a stanza, then it will have to be shown inline. In your above example, suppose `<pb n="5r"/>` and `<lb n="30"/>` come after _bhūmi_, and suppose `<lb n="31"/>` comes after tasyaiva.

**Comment by manufrancis** [comment]
Dear Dan, I see what you mean.
Dear Axelle, could you implement an inline display like the following (for the moment for the purpose of our proof-reading display; to be discussed again when we will tackle the display on the website).

![Capture d'écran 2020-04-28 12 53 45](https://user-images.githubusercontent.com/905870/80479638-9b59d980-894f-11ea-990e-7dfc850ca67d.jpg)

**Comment by ajaniak** [comment]
Done
