### ISSUE TITLE
Transformation relating to "editorial" display

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#33]
Dear all, 

Could you list here all the elements regarding editorial norms and practices that you expect to be dealt through automation? Please, make sure to precise the context of use and language when necessary.

e.g. Change _***Space***_ into _***Non-breaking space***_  in French translation, before `;`, `?`,` !`, `»`, `›`, `:` and after `«`, `‹`

Best,

**Comment by manufrancis** [comment]
**For French**

To be implemented anywhere.

See "Règles typographiques, Imprimerie Nationale".
* Summary table for punctuation, page 149: https://sharedocs.huma-num.fr/wl/?id=ckYylpU8pVoWtdfy0t9eID9M425OmEEN
* The full book: https://sharedocs.huma-num.fr/wl/?id=aiwGT5isC7vPMiW1PBErApJhr3l2W6D2

As for French "chevrons" (`<` and `>`), I do not foresee, for the moment, any specific treatment.

**For English**

To be implemented anywhere.

No space before + space after any punctuation, e.g. `!` `?` `;` `:`

Transform 
`'…'` and `"…"`  (neutral, vertical, straight, typewriter, dumb, or ASCII quotation marks)
into
`‘…’` and `“…”` (typographic, curly, curved, book, or smart quotation marks)
Space before + no space after for opening quotation mark.
No space before + space after for closing quotation mark.




> >

**Comment by arlogriffiths** [comment]
non breaking spaces after common abbreviations: 

- cf. and Cf.
- e.g. and E.g.
- p. (although there shouldn't be any of encoders follow the EG)
- n. (although there shouldn't be any of encoders follow the EG)

**Comment by ajaniak** [comment]
I made sure p. and n. would be use with a non breaking space but it also generates an error message saying it is not allowed.

**Comment by manufrancis** [comment]
Fine! Thanks!

**Comment by manufrancis** [comment]
Implemented by Axelle.
Feedback requested on implementation.
Linked to issue #91 
Integrated into pipeline for editorialisation setup by Axelle following DHARMA brainstorming (2020/12/17).
