### ISSUE TITLE
tiny inconsistemcy with hyphen / en-dash

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#331]
@michaelnmmeyer 

hyphens in page runs get converted to en-dash but not hyphens in year ranges. can the conversion be implemented also for the latter?

<img width="1176" alt="Capture d’écran 2024-09-22 à 20 49 14" src="https://github.com/user-attachments/assets/4f457ee0-546f-4fc5-b1ee-feb6d737fb16">

**Comment by michaelnmmeyer** [comment]
Done in https://github.com/michaelnmmeyer/dharma/commit/febafe2017b058da18f3d735dd1ee60044ab941d.
