### ISSUE TITLE
small adjustment to xslt for <div type="translation">

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#35]
@ajaniak : the code `<div type="translation" xml:lang="eng">` presently leads to "Translation in English" in html. See screenshot. Please correct this to "Translation **into** English".

<img width="321" alt="Capture d’écran 2020-05-07 à 14 27 06" src="https://user-images.githubusercontent.com/835603/81294436-30a34f00-906f-11ea-840b-162e57736f37.png">

**Comment by ajaniak** [comment]
It is done, you can pull.
