### ISSUE TITLE
display of <lb> included in <lem> in <div type="apparatus">

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#36]
@ajaniak : for `<app loc="10"><lem>sa-karaṇo<lb break="no" n="11"/>petānā<unclear>ṁ</unclear></lem>` in xml, the xslt current produces an output that isn't yet as we want it. see screenshot attached. and compare (current) oage 108 of the EGD (§9.1, subsection "Specifying a precise spot by a lemma"), from which I quote the most relevant points:

- the lemma should appear exactly as it appears in your digital edition
- empty elements representing transition points (`<lb/>`, `<pb/>` and `<milestone/>` of any kind) shall, however, be included in the lemma
- we foresee that all of these elements will be displayed as a simple / character when they appear as a lemma (thus, since a pagelike partition will always be followed by a line beginning, these together will display as //)
- when a lemma extends across such a boundary, the `@loc` of the apparatus entry must be the number of the line where the lemma begins (i.e. do not use a range of lines here)

Please implement the following:
1. the behavior with regard to / (and no hyphen at the line transition even in case of `@break="no"`)
2. the line reference just before the text of `<lem>` in a situation like this one should be displayed as **(10–11)** (in superscript with en-dash)

<img width="206" alt="Capture d’écran 2020-05-07 à 16 38 27" src="https://user-images.githubusercontent.com/835603/81307967-8a147980-9081-11ea-932b-27158efda41a.png">

**Comment by ajaniak** [comment]
It should be done. There is a bug which add a space for the / related to the transformation of the @break. I have it for other hyphen as well. But it is related to this issue, so I am closing this thread.
