### ISSUE TITLE
Zotero Guide: used of & in short titles

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#4]
I have just tried to use the short title "Huart&Hooiberg1875_01" in the file tfc-nusantara-epigraphy/.../arlogriffiths/Marsmu.xml, and the & causes the file not to validate. See screenshot.

<img width="989" alt="Capture d’écran 2020-01-18 à 18 40 05" src="https://user-images.githubusercontent.com/835603/72663193-1d1d9b00-3a22-11ea-81ec-4373451a4e22.png">

Should be change the rule formulated in ZG 4.10.1? or is there some setting that I should

**Comment by ajaniak** [comment]
It is because you can't use the & on its own. The & calls for characters you have declare as entitty in a doctype. To use it, you have to use its html code &amp;

**Comment by arlogriffiths** [comment]
désolé, je ne comprends pas ta réponse, et me demande si elle est complète

maintenant que je relis la page 20 du ZG, je ne comprends pas non plus ce qui est dit ici: "In the case of a sequence of two names, the Name block is to consist of both separated by an ampersand in its HTML code. Example: Coedes&Damais for “Coedès
and Damais”.

What is an "ampersand **in its HTML code**"? what concretely should I type in an XML file when I have a short title of the type "Huart&Hooiberg1875_01" to fill in within a `<bibl>`?

I guess we need to give clearer instructions in the ZG and maybe also in the EG.

**Comment by ajaniak** [comment]
You can't use `&`, you need to use its code which is `&amp;`. It will be automatically proposed bu Oxygen. 

The lack of clarity is my mistake. You change the text to answer this issue with Manu before changing our mind and deciding, it would be easier to put it only in the EG. I guess I have forgotten a delete a part of the changes. 

The ampersand in its hmtl code is `&amp;`.

In you `<bibl>, you type "Huart&amp;Hooiberg1875_01".

**Comment by arlogriffiths** [comment]
Axelle: after editing your last response, and making visible some of the code that had been hidden because you forgot to use `..., I now understand. 

Daniel: we need to given an example like `"Huart&amp;Hooiberg1875_01"`  in the EG. Close this issue when you've done it.

**Comment by ajaniak** [comment]
oups...sorry!

**Comment by arlogriffiths** [comment]
no problem. how can I make my own aposytrophes visible when talking about them?

**Comment by danbalogh** [comment]
I've added this to Bibliographic citations under 10.4, as well as an explanation of why in 1.3/XML Terms.
But, before I resolve this: is it too late to reconsider and, instead of complicating the encoding with &amp;, using some other character (e.g. + or _) in Zotero Short Titles for multi-author publications?
I believe Huart+Hooiberg1875 should be technically OK and fairly intuitive, and Francis+al might also work.

**Comment by ajaniak** [comment]
We can change in favor of `+`. I don't see any problem with this. 
\`

**Comment by arlogriffiths** [comment]
sounds good. please make the needed changes in ZG and EG. (for EG, I guess this means we can go back to not discussing this kind of case at all.)

Axelle: can you auto-replace all cases of & in shorttitles already declared in Zotero?

In any case, please send around a message to all team members that we have made this significant change to the pilicy re. shorttitles.

Le 20 janv. 2020 à 17:27, ajaniak <notifications@github.com<mailto:notifications@github.com>> a écrit :


We can change in favor of +. I don't see any problem with this.
`

**Comment by danbalogh** [comment]
I've removed the caution from the citation section of the EG and changed the example code to <ptr target="bib:Huart+Hooiberg1875_01"/>. However, I've retained the notes on character entity references in the terminology section, because it's good if our people will be aware of this.
I guess it's best if I pass over resolving this thread to Axelle, who can do so once the ZG has been revised to + and existing Zotero entries with & have been changed to +.

**Comment by ajaniak** [comment]
I have made the change in the guide. 

I can do the change on Zotero but I will need to use the JavaScript console. I will let you know as soon as I find some time to apply it. As well as Daniel demands on adding the ! to start the unchecked short titles. If you have other requirement, let me know.

**Comment by arlogriffiths** [comment]
sounds good. no other requirements from my side at this stage. close this when you're done.

**Comment by ajaniak** [comment]
Done
