### ISSUE TITLE
display of <lg> in connection with value of @met and values of @n in <l> when xml:lang is "san" or "kaw"

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#40]
@ajaniak:

**NB: this message does not concern any editions where xml:lang is "tam". Manu has to formulate rules for that language.**

```
<lg n="1" met="anuṣṭubh">
	<l n="a">vahubhir vasudhā dattā</l> 
	<l n="b">rāj<choice><sic>ā</sic><corr>a</corr></choice>bhis sagarādibhi<supplied reason="omitted">ḥ</supplied></l>
	<l n="c">yasya yasya yadā bhūm<unclear>i</unclear>s</l> 
	<l n="d">tasya tasya tadā phalaṁ</l>
</lg>
```

currently leads to this display:

<img width="336" alt="Capture d’écran 2020-05-16 à 06 04 03" src="https://user-images.githubusercontent.com/835603/82110000-4f72a700-973b-11ea-8eb6-376463039e41.png">

I would prefer it to be like this:

<img width="474" alt="Capture d’écran 2020-05-16 à 06 44 41" src="https://user-images.githubusercontent.com/835603/82110718-c52d4180-9740-11ea-90e2-91139bf414c3.png">

I have taken this example of desired layout from [EIAD 188](http://hisoma.huma-num.fr/exist/apps/EIAD/works/EIAD0188.xml?&odd=teipublisher.odd). We don't need such a large gap between the stanza number and the rest, but we do need the following:

1. the name of the meter is to be aligned with the lines of verse
2. when `met="anuṣṭubh"`, `<l>` ab and cd are to be placed side by side, and no extra indent on the group cd vis-à-vis the group ab. 

Let us call this second mode "grouped display" and let us call the present display "linewise display".

For proper display of `<lg>`, please take into account the following parameters

- value of `@met` (refer to the tables under "Sanskrit syllabic metres" and "Sanskrit/Prakrit moraic metres" in EGD Appendix B)
- values of `@n` in `<l>`

With those parameters, I think the following rules can be formulated:

1. If `@n` shows values "ab" and "cd", then always choose linewise display.
2. If `@n` shows values "a", "b", "c" and "d", then apply groupwise display if `@met="sumānikā"` or `@met="anuṣṭubh"`. **NB: if `<l>` shows `@enjamb="yes"` then place the next `<l>` after the first without intervening space; in all other cases, place a space between the two `<l>`s.**
3. If `@n` shows values "a", "b", "c" and "d", the apply linewise display for all other values of `@met`.

I would suggest always using the same amount of indent on every displayed line. 

It is quite possible that I have forgotten some complications, and I trust @danbalogh will intervene quickly if such is the case.

**Comment by danbalogh** [comment]
I'm OK with displaying anuṣṭubh and this weird sumānikā in the grouped manner. I see no complications at the moment, except possibly that in some rare cases there may be an `@enjamb` on line b. I think that is quite unlikely, but should it happen, line c must still be started in a new line and perhaps a hyphen should then be displayed at the end of line b. (I think this is what I suggested earlier for the default displaying of stanzas).
As for indenting, I personally much prefer to indent even lines (that is, to indent them more deeply than odd lines), but if Arlo definitely prefers all lines of a stanza to begin at the same level of indentation, then I can live with that.

**Comment by AnneSchmiedchen** [comment]
If it comes to personal preferences, I - like Arlo - prefer all lines to begin at the same level of indentation.

**Comment by arlogriffiths** [comment]
Manu: can you cast your vote, so that Axelle can get to work on this?

**Comment by manufrancis** [comment]
I am in favour of linewise display **in all cases**, that is
1 line for `<l n="a">`, 1 line for `<l n="b">`, etc.
1 line for `<l n="ab">`, 1 line for `<l n="cd">`, etc.

Thus, option1:
![Capture d'écran 2020-05-19 14 10 15](https://user-images.githubusercontent.com/905870/82324937-bd88c980-99da-11ea-827d-d70cbc81b026.png)

Or, option 2 (my favourite)
![Capture d'écran 2020-05-19 14 13 12](https://user-images.githubusercontent.com/905870/82325124-fc1e8400-99da-11ea-90d8-3969a87d035a.png)

Or even option 3 (I am not against furhter identation for `<l n="b">` and `<l n="d">`)

![Capture d'écran 2020-05-19 14 15 31](https://user-images.githubusercontent.com/905870/82325288-456ed380-99db-11ea-85c0-128f01753cab.png)

As for Anuṣṭubh, I do not mind if it is italicised or not.

**Comment by arlogriffiths** [comment]
all of Manu's proposals would be fine with me. for me it is most important that we soon get a better layout than what we have now (so I can start using our html's in reading editions in the classroom). so let us take Manu's favorite option (no. 2).

@ajaniak: please go ahead and implement it.

**Comment by ajaniak** [comment]
@manufrancis, can you confirm you expect  a line/space between the line with the number and the `@met` and the first `<l>`?

**Comment by manufrancis** [comment]
Yes, I confirm.
Like this:
![Capture d'écran 2020-05-19 14 13 12](https://user-images.githubusercontent.com/905870/82445971-13767380-9aa6-11ea-952a-3ddb39746e12.png)

Not like this:
![Capture d'écran 2020-05-20 14 26 20](https://user-images.githubusercontent.com/905870/82445983-18d3be00-9aa6-11ea-8c31-a7da5b450ec5.png)

**Comment by ajaniak** [comment]
Thanks @manufrancis . To do so, I had to distinguish the first `<l>` and handle the space with the CSS. For now, the space has the value 10px. I can reduce it or make it bigger if necessary. 
The idents are also handle with CSS. 

Let me know if the alignment is conform to your expectations.

**Comment by manufrancis** [comment]
Fine with me!
Thank you, Axelle.

**Comment by arlogriffiths** [comment]
looks good to me me too! closing this now.
