### ISSUE TITLE
apply color also to <unclear> parentheses inside <orig>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#41]
@ajaniak:

`nimn<orig><unclear>e</unclear></orig>-gābhiś`

currently leads to this display:

<img width="117" alt="Capture d’écran 2020-05-16 à 06 53 44" src="https://user-images.githubusercontent.com/835603/82111009-2dc8ee00-9742-11ea-9c2b-e42decb79547.png">

I'd like the parentheses to also be displayed with the color for `<orig>`.

Of course, the others should first say if they agree or not.

**Comment by AnneSchmiedchen** [comment]
Yes, I agree: same colour for the parentheses as well please.

**Comment by ajaniak** [comment]
@manufrancis asked me to put in black some of the editorial signs: can you clarify together when editorial signs have to be colored and when to kept then in black?

**Comment by manufrancis** [comment]
I guess editorial signs should be coloured
* in `<div type="edition">`
* in `<lem>` in `<div type="apparatus">`

and editorial signs should not be coloured
* in  `<rdg>` in `<div type="apparatus">` (one colour only)
* in `<div type="translation">`
* in `<div type="commentary">`

**Comment by danbalogh** [comment]
I agree that if `<orig>` is displayed in colour, then the brackets for `<unclear>` within that tag should likewise be in colour. I also agree with what Manu says about not using colour when editorial markup is present in translations and commentaries. I'm not sure about making a difference between lemmas and readings - to my mind, either both should have colour or neither. My preference is for both.

**Comment by manufrancis** [comment]
A single colour for `<rdg>` was, I think, a wish of Arlo, to have a clear distinction between `<lem>` and `<rdg>`.
I am fine with both in colour or neither, as `<lem>` is in Roman and `<rgd>` is in italics and as theyrare separated one from another by a diamond.

**Comment by danbalogh** [comment]
I'm also fine with either solution. But I definitely agree that the italics and diamond are sufficient distinction and want to point out that not all `<lem>`s will have colour in them, so the presence or absence of colour is not a good factor for distinguishing lemma and reading.

**Comment by arlogriffiths** [comment]
@ajaniak: I think you can implement

give editorial signs the same color as what they contain
 *   in `<div type="edition">`

keep light green color on the entire `<rdg>`
 *   in `<div type="apparatus">`

do not apply any color to editorial signs or the readings/lemmas in question
* in `<div type="translation">`
* in `<div type="commentary">`

**Comment by manufrancis** [comment]
I am fine with Arlo's last proposition.

But what about `<lem>` in apparatus?
Black colour only? 
OR with colours, like in edition?

**Comment by arlogriffiths** [comment]
Thanks for spotting that omission, Manu. 

I recap again for @ajaniak 

give editorial signs the same color as what they contain
 *   in `<div type="edition">`
 *   use exactly the same display as inside `<div type="edition">` for  `<lem>` in `<div type="apparatus">`

keep light green color on the entire `<rdg>`
 *   in `<div type="apparatus">`

do not apply any color to editorial signs or the readings/lemmas in question
* in `<div type="translation">`
* in `<div type="commentary">`

**Comment by ajaniak** [comment]
Should be good now.
