### ISSUE TITLE
display of <fw>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#42]
@ajaniak: I fear I don't have the xslt properly functioning yet in this case, but assuming that the following would be the same even after you have helped me configure the scenario properly, let me report that the following code:

```
<lb n="2r3"/>saṅ arya pagəḥ, sira saṅ arya guna, sira patiḥ riṁ pagu<pb n="2v" break="no"/><fw n="2v" rend="tb-rotated" place="left"><num value="2">2</num></fw><lb 
n="2v1" break="no"/>han·, sira patiḥ səR̥g·, sira patiḥ tem·beṁ,</p>
```
leads to display with [fw: 2] both before and after the `<lb>`:

<img width="418" alt="Capture d’écran 2020-05-17 à 14 44 30" src="https://user-images.githubusercontent.com/835603/82147034-4245dd00-984d-11ea-8223-33ac1a2fa5a0.png">

I think we want the display right before the hyphen removed.

**Comment by arlogriffiths** [comment]
see also

```
  <lb n="2v3"/>// <num value="200000">200000</num> // roṁ kəṭi roṁ kəṭi
<pb n="3r"/>
    <fw n="3r" rend="tb-rotated" place="left">
    <num value="3">3</num>
  </fw>
    <lb n="3r1"/>gənəp·, padu kalivon·, tr<subst><del>i</del><add>a</add></subst>ayodasi,<!-- Arlo:
        indeed, why not simply trayodasi? --> suklā<lb n="3r2" break="no"/>-
```

displayed:

<img width="455" alt="Capture d’écran 2020-05-17 à 14 55 24" src="https://user-images.githubusercontent.com/835603/82147230-9e5d3100-984e-11ea-96d4-9003dfee63c4.png">

**Comment by ajaniak** [comment]
Solved.
