### ISSUE TITLE
Dealing with bibliographic sigla

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#46]
Dear all, 

At Arlo's request, the automatic system for sigla implemented so far have been taken done. Now, you need to declare it as the content of`@n` on `<bibl>` in the `<div type="bibliography">`. 
For instance, such an encoding. 
```
<listBibl type="primary">		
		<bibl n="H">
			<ptr target="bib:Hultzsch1913-1914_01"/>
			<citedRange unit="page">225-226</citedRange>
			<citedRange unit="item">B</citedRange>
		</bibl>	
	</listBibl>
```
So far, I have written the code with the idea that `@n`would be mandatory. 

In apparatus, it gives: 
```(4) ṟeṉpāl ◇ ṟeṉp(ā)l H```

In bibliography, it gives: 
```H. Hultzsch, Eugen. 1913. “Two Cave-Inscriptions at Dalavanur. A. Sanskrit Inscription of Narendra Satrumalla.” Epigraphia Indica XII.27: 225–26. 225-226, B.```

In both cases the colors and tooltip from the previous request have been kept. 
Note that the errors dealing with the XSLT is very slight since it depends on the schema. 

Best,

**Comment by danbalogh** [comment]
Thanks, this sounds useful and quite simple. I guess I should add this to the EGD. When you say `@n` would be mandatory, does that mean mandatory for items in the bibliography to which I refer from the apparatus, or all items in the primary bibliography?
I don't understand the statement "the errors dealing with the XSLT is very slight since it depends on the schema."

**Comment by arlogriffiths** [comment]
Thanks Axelle. In display, I suggest placing the siglum at the very end of an entry, inside square brackts, and with explicit word "siglum", and the whole bit in bold, e.g.

Hultzsch, Eugen. 1913. “Two Cave-Inscriptions at Dalavanur. A. Sanskrit Inscription of Narendra Satrumalla.” Epigraphia Indica XII.27: 225–26. 225-226, B. **[siglum H]**

Yes, Dan, my idea was to make a last-minute addition on this point to EGD v1. Indeed, mandatory only for items referred to in apopartatus. I suggest recommending all initials of an author as siglum, so EH for Eugen Hultzsch.

**Comment by manufrancis** [comment]
Thanks, indeed, Axelle.
I have made my daily pull and it works already nicely ;-)

* OK for 

> all initials of an author as siglum

It will make the distinction between authors bearing same name.

* OK for, like in the example, 

> placing the siglum at the very end of an entry, inside square brackets, and with explicit word "siglum"

Thus:

Hultzsch, Eugen. 1913. "Two Cave-Inscriptions at Dalavanur. A. Sanskrit Inscription of Narendra Satrumalla." Epigraphia Indica XII.27: 225–26. 225-226, B. [siglum **EH**]
"siglum" not bold!

Axelle, there is presently a error message for any `<bibl>` missing its @n, which is very useful, but thus also for a `<bibl>` (in secondary bibliography) which is not referred to in the apparatus.

**Comment by ajaniak** [comment]
I put it at the beginning because the issue #31 where the possibility to use a tooltip for the bibliographic content was been evoked. 

@manufrancis , I will be moving the error message to the apparatus then and not set it on the bibliography part. Since my assomption you would give a siglum to every entry was wrong. 

In this case, @danbalogh it means the `@n` is mandatory for items in the bibliography to which I refer from the apparatus. (The primary bibliography was just part of the example.)

**Comment by danbalogh** [comment]
Thanks for the clarifications and added detail. I've added EGD §9.4/Bibliographic sigla to cover this. Please have a look and comment.

**Comment by arlogriffiths** [comment]
@ajaniak : can you explain what you mean by "I put it at the beginning because the issue #31 where the possibility to use a tooltip for the bibliographic content was been evoked"? 

if indeed we could have a tooltip when moving over a siglum in the apparatus, that might make any explicit marker in the bibliography, such as "[siglum EH]" redundant, or maybe it woulb be good to have have both.

so please make it clear what encoding requirements you have for being able to display a tooltip.

**Comment by ajaniak** [comment]
The apparatus already works with a tooltip. For now the content is made thanks to the short title, but I plan to add a query for Zotero API in citation mode, at a later stage. I made the test on tfa-pallava-epigraphy, and it only works there for now since some updates have to be made on our Zotero for efficiency. See the screenshot for the current result. 

<img width="572" alt="Capture d’écran 2020-05-19 à 14 54 23" src="https://user-images.githubusercontent.com/33328906/82329055-03489080-99e1-11ea-833f-aa5cb79e52b7.png">


From what I have understand of #31, is related to the rendering of the bibliography. The wanted display would be working as the secondary bibliography in EIAD, but the question hasn't been answered yet, so the code was made to handle it with the siglum as base for the tooltip for the all citation. I think @manufrancis was the author, maybe he can correct me, if I haven't understand it correctly.

**Comment by danbalogh** [comment]
In connection to the new EGD section, @manufrancis has asked:

> As per the current EGD about what is primary and secondary bibliography, some items in the secondary bibliography (partial readings or translations; descriptions/discussions of the inscription’s content) could also be mentioned in the apparatus.
> Maybe define primary bibliography as "independent integral editions" and any other publications susceptible to be referred to in the apparatus?? Thus the n=initials should be applied only in primary bibliography and Axelle could setup an error message that concerns only primary bibliography?

I think this raises two separate issues that need attention from @ajaniak and @arlogriffiths .

1. items in the secondary bibliography may indeed, in some cases, need to be cited in the apparatus. I think the straightforward solution to that is simply for me to rewrite the current EGD's reference to "primary bibliography" in this connection to "primary or secondary bibliography". @ajaniak - is that right? Does your current solution for apparatus display care whether the item cited with `@source` is in the primary or secondary bibliography? I assume that is not a problem.

2. Arlo, are you interested in revising the definition of "primary bibliography" as suggested by Manu above? I think that is not necessary, unless drawing apparatus sigla from both bibliographies (as in 1 above) poses a technical problem, in which case it may become necessary.

**Comment by danbalogh** [comment]
@arlogriffiths , I don't understand what you mean above when you say "if indeed we could have a tooltip when moving over a siglum in the apparatus, that might make any explicit marker in the bibliography, such as "[siglum EH]" redundant". Do you mean that if tooltips for sigla can be implemented then you may want to revoke the idea of explicitly encoding sigla (`<bibl n="EH">`) and make do with auto-generated sigla?

**Comment by arlogriffiths** [comment]
@danbalogh : 

1. I agree, no need tro redfine what "primary bibliography" is, but rather allow use of @n also in `<listApp>` for secondary bibliography.
2. no, I meant that in that case it is perhaps no longer necessary to explain the bibliography what the siglum for a given `<bibl>` is, because the tooltip in the apparatus shows the identity of the `<bibl>` referred to with a given siglum. So in any case it is necessary to use `@n` for defining sigla.

@ajaniak: 

please let us know whether we can allow use of @n in  the `<listApp>` for secondary bibliography.

**Comment by ajaniak** [comment]
@danbalogh, I don't distinguish primary or secondary bibliography, I compare the content of `@source`in the apparatus and the content of `@targat`and retrieve the `@n` when they match. So if sometimes I have a `@n`in the secondary, those sigla will be display. 

So you can allow the `@n`in ` <listBibl type="secondary">`.

**Comment by danbalogh** [comment]
Axelle, thanks for the confirmation. Arlo: I understand now.
I'll edit the EGD accordingly and resolve pertaining comments.
