### ISSUE TITLE
@source on <lem> and more than one @source on <rdg>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#47]
@ajaniak:

the following code:

```
              <listApp><!-- one <app> for each apparatus entry -->
	<app loc="1v1">
<lem source="bib:Boechari1985-1986_01">vuĀ<gap reason="lost" extent="unknown" unit="character"/></lem>
<rdg source="bib:CohenStuart1875_01">vuĀ<supplied reason="lost" cert="low">ra</supplied><gap reason="lost" extent="unknown" unit="character"/></rdg>
<note>Cohen Stuart's restitution is not confirmed by any occurrence of <term>vuāra</term> in any inscription that I am aware of, although <term>vuara</term> is common.</note>
</app>
 <app loc="1v2">
                     <lem>Ikanaṁ</lem>
                     <rdg source="bib:CohenStuart1875_01 bib:Boechari1985-1986_01">Ikana</rdg>
<note>The anusvāra is clear enough on the estampage.</note>
                  </app>
                  <app loc="1v3">
                     <lem source="bib:CohenStuart1875_01">saṁ ḍuryyan· muAṁ saṁ siṅgaḥ</lem>
                     <rdg source="bib:Boechari1985-1986_01">san daryyan muan singah</rdg>
<note>Besides omitting all diacritics on every one of these words, Boechari entirely omits the second <term>saṁ</term>.</note>
                  </app>
               </listApp>         
```

is displayed like this:

<img width="1142" alt="Capture d’écran 2020-05-19 à 12 53 53" src="https://user-images.githubusercontent.com/835603/82318274-dcce2980-99cf-11ea-8810-88f3d252a85b.png">

It seems that 
1. when `@source` has more than one value, no sigla is displayed
2. when there is a `@source` on `<lem>`, no siglum is displayed: please display it before the diamond sign
3. The 'smartification' of apostrophes is not yet implemented or not yet working (see display of "Cohen Stuart's")

**Comment by manufrancis** [comment]
Dear Arlo, one question: why do you encode some readings by others as `<lem>` and not just as `<rdg>`? 
Is it because you edit this inscription without visual documentation and reproduce an edition which mixes readings by Boechari and Cohen Stuart?

**Comment by arlogriffiths** [comment]
Maybe such questions, which don't concern Axelle, are better asked outside of github issues. Anyhow, the answer is that I am following the EGD. Please see p. 113: "`<lem>` may take the attribute @source (§10.7/) to show that a previous edition agrees with the reading adopted in your edition, ..."

@ajaniak : please implement the enhancements requested above.
