### ISSUE TITLE
XSLT: two small tweaks inside <app>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#48]
@ajaniak:

1. if an `<app>` contains only a `<note>` (and no `<lem>`) then do not print • before the text of the `<note>` — see A11 in example below.
2. always print a space before the ◇ that marks transition between `<lem>` and the first `<rdg>`

<img width="736" alt="Capture d’écran 2020-05-21 à 07 59 18" src="https://user-images.githubusercontent.com/835603/82528629-81b84600-9b39-11ea-9d74-96e242b820a0.png">

**Comment by ajaniak** [comment]
Done

**Comment by arlogriffiths** [comment]
now we have some color problems:

<img width="623" alt="Capture d’écran 2020-05-25 à 17 47 07" src="https://user-images.githubusercontent.com/835603/82827825-101d2680-9eb0-11ea-97ce-16330a0efe3d.png">


- ◇ and  • should always be black
- contents of `<note>` should alwways be black
- the contents of `<lem>` should not become blue

**Comment by ajaniak** [comment]
In this case, the problem is from the xml: `<app loc="S31">
                      <lem source="Mertens2005_01">-karaṅkāṅka-</lem>` the prefix `bib:`is missing. I can't move the `<span>`to avoid the mistake made on `@source`otherwise I won't be able to create the tooltip.

**Comment by arlogriffiths** [comment]
thanks for spotting the error. problem solved.
