### ISSUE TITLE
XSLT: display of <g> (and bug with <g type="xyz">.</g>)

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#50]
@ajaniak: please update the XLST to take into account the recent rewrites to EGD 4.2 (Overview, Symbol tokens, Punctuation marks, Space filler signs, Misc. symbols)?

1. if `<g>` wraps "." then please print "pc" inside a black box
2. if `<g>` wraps one or more signs "§" then just print the contents of the elements
3. if `<g>` is an empty element, then please print "symbol" inside a black box

At this time, I notice an inconsistent behavior that I cannot explain. Compare the display for thge two cases of `<g type="dDandaOrn">.</g>` in the following code and screenshot, where a hyphen is printed at the end of IV but not of III:

```
<lg n="3" met="vasantatilakā" xml:lang="san-Latn">
<l n="a"><lb n="A5"/>śrī<orig>b</orig>ajra-pāṇir ajito jita-jambha-vairī</l>
<!--  est. n. 545 shows jita-jambha; the pdf of Coedes 1908 seems to show jīta-jambha but it is probably an imperfection of the scan-->
<l n="b"><orig>b</orig>ajrañ jvalaj-jvalana-dīpti-nibhaṁ bibhartti</l>
<l n="3" enjamb="yes"><lb n="A6"/>Uddāma-dr̥pta-kali-dānava-doṣa-ṣaṇ<orig>d</orig>a</l>
<l n="d">niṣyaṇda-saṁkṣubhita-vighna-vighāṭa-dakṣaḥ <g type="dDandaOrn">.</g></l>    
</lg>
   <lg n="4" met="vasantatilakā" xml:lang="san-Latn">
<l n="1" enjamb="yes"><lb n="A7"/>Āsīt samasta-bhuvanākara-ratna-sāra</l>
 <l n="b">tārā-sphura-kiraṇa-rañjita-pāda-pī<orig>th</orig>aḥ</l>
<l n="3" enjamb="yes"><lb n="A8"/>somānvayo 'ri-rasa-maṅgala-bhū-dharaś śrī</l>
 <l n="d">rājendravarmma-nr̥-patir vvitatāṅga-dīptiḥ <g type="dDandaOrn">.</g></l>
</lg>
```

<img width="370" alt="Capture d’écran 2020-05-21 à 08 36 53" src="https://user-images.githubusercontent.com/835603/82530732-3fddce80-9b3e-11ea-8cd9-9b71b1106fb2.png">

**Comment by ajaniak** [comment]
The trailing hyphen is the result of the `@enjamb` on the first `<l>`of the `<lg n="4">`.

**Comment by arlogriffiths** [comment]
The hyphen should be placed at the end of the `<l>`which bears @enjamb, not after the next `<l>`.

**Comment by ajaniak** [comment]
I moved it.

**Comment by ajaniak** [comment]
Reponed since `<g>` treatment not the same between issues #50 et  #51

**Comment by arlogriffiths** [comment]
@arlogriffiths moving @danbalogh's comments on `<g> from #51 to here:

We are at the moment working on the basic type values permitted for symbols. If you need to devise a display solution right now, I would suggest the following:

- when `<g>` contains a . (full stop), display it as a placeholder character | ; when `<g>`  contains .. (two full stops), display as ||
- when `<g>` is an empty element, display a placeholder character depending on `@type` as follows:
  - if type="filler", display §
  - if type is anything else, display @ or any other provisional placeholder

Sometime soon, we'll want to replace this with a more nuanced display depending on `@type`, but we don't have the details of that. See the working document at https://docs.google.com/document/d/1glfyQnFqPrbVOYzegfjKIOVrc-vMgznEQ1iNsFf7DE8/edit?usp=sharing for some preliminary notes. Once these are finalised (for the present), we'll want display depending on `@type` for all g elements that are not numerals, regardless of whether they are empty or contain a full stop. And in the long run, as you know, we'll replace the provisional values of `@type` with a constrained list of values, plus a set of subtypes.

**Comment by arlogriffiths** [comment]
@ajaniak : please follow @danbalogh's recommendation for "display solution right now", instead of mine.
