### ISSUE TITLE
unclear in choice

### ISSUE THREAD

**Issue by danbalogh** [erc-dharma/project-documentation#52]
With the current transformation, if the code has a choice with unclear in it (ambiguous reading), the alternative readings get displayed with the legacy EpiDoc underdots. The underdots should be removed from the display of unclear in all circumstances. E.g. `<choice><unclear>ph</unclear><unclear>p</unclear></choice>alam` is rendered in transformation as `(p̣ḥ/p̣)alam` - but should appear as `(ph/p)alam`.

**Comment by ajaniak** [comment]
That's normal, I am currently redoing the code.

**Comment by danbalogh** [comment]
Thanks. Sorry about the false alarm.
