### ISSUE TITLE
schema: <note> in <div type="translation">

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#53]
@ajaniak :

je sais que le schéma n’est pas encore prêt — pardonne-moi d’avoir commencé à utiliser le template v3!

En ce moment, le schéma interdit encore l’emploi de `<note>` dans la traduction, ce qui doit être autorisé (EGD 10.4.1). Peux-tu modifier cela, de sorte que mon fichier DHARMA_INSBengalCharters00007.xml ne soit plus invalidé?

Merci!

**Comment by ajaniak** [comment]
J'ai supprimé toutes les contraintes sur les notes.

**Comment by arlogriffiths** [comment]
Since EGD 10.4.1 writes "notes may be used in the apparatus, the translation and the commentary", I suggest to allow it only the three mentioned `<div>` types. I have just proposed a rewrite to the next line of the EGD, to become: "it is strongly discouraged that you add notes to any other part of your document (and indeed it is rendered impossible by our TEI schema)".

@ajaniak: can you modify the schema again to correspond to exactly the following constraints?

 - `<note>` allowed in  apparatus, the translation and the commentary
- `<note>` not allowed in  any other part of an xml file

Thanks!

**Comment by ajaniak** [comment]
C'est déjà aplliqué
