### ISSUE TITLE
Display of <space/>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#54]
Had a decision been tyaken yet (in the Cheatsheet?) on how to display this?

I see that current display is _vac._, which is not satisfactory.

In EAID, we use the diamond character ◊ to mark punctuation space. If there are no strong alternative preferences, I'd be happy to continue using that convention. And if there is @unit="character", then a number of such signs corresponding to the value of @quantity. (Are there any other, more complicated scenarios to discuss?)

**Comment by danbalogh** [comment]
I am not aware of a decision and see nothing in the online cheatsheet on it. My preference remains _ for `<space/>` without unit and quantity and _n_ for `<space quantity="n" unit="character"/>`. I have no strong objection to the solution proposed by Arlo, but I believe that the underscore is an intuitively understood representation of a deliberate space and is thus better for our purpose. Symbols such as diamonds could be better used for specific kinds of spaces, which I think we did discuss at some point somewhere and I made suggestions along the following lines:

- ◯ U+25EF Large Circle: @type="binding-hole"
- □ U+25A1 White Square or  ◊ U+25CA Lozenge: @type="defect"
- ⊔ U+2294 Square Cup for @type="descender"
- ⊓ U+2293 Square Cap for @type="ascender"

If we go for ◊ instead of _, the above list (with square for defect) can still be used for spaces with type.

**Comment by ajaniak** [comment]
I don't think the cheatsheet has really been updated.

But indeed, no DHARMA display have been added for `<space>`, the exchange on the transformation have been stopped since the discussion on `<gap>` is still unresolved.

**Comment by arlogriffiths** [comment]
@danbalogh : could you recapitulate your proposal by offering a list that includes what you propose to do with `<space/>` (lacking any attribute) and what you propose to do with quantification as in `<space quantity="n" unit="character"/>`? 

I think in our discussion of `<gap>` we have decided against the idea of repeating the relevant symbols as many times as the value of `@n`, so I presume we need an analogous solution for `<space quantity="n" unit="character"/>`, regardless of the `@type`.

**Comment by danbalogh** [comment]
My proposal is (and was even in the earliest stylesheet) the same as in my comment from 2 days ago, except that markdown had obscured that one (now corrected):

- `<space/>` without attributes: `_`
- `<space quantity="n" unit="character"/>`: `_n_`

And for typed spaces, the figural shapes suggested ny me above could work.

**Comment by arlogriffiths** [comment]
That is all fine with me. Let me try to recap for Axelle's and the other PIs' convenience:

- ◯ U+25EF Large Circle for `<space type="binding-hole"/>`
- □ U+25A1 White Square for `<space type="defect"/>`
- ⊔ U+2294 Square Cup for `<space type="descender"/>`
- ⊓ U+2293 Square Cap for `<space type="ascender"/>`
-  _ (underscore) for `<space/>` without any attributes
-  \_n\_ for `<space quantity="n" unit="character"/>` without @type
- □n□ `<space quantity="n" unit="character" type="defect"/>` and analogously for other `@type`s 
- create error message if `@type="binding-hole"` is found combined with any other attributes.

**Comment by danbalogh** [comment]
Thanks for the recap. A small correction to the following point:

- □n□ `<space quantity="n" unit="character" type="defect"/>` and analogously for other `@type`s 

Other `@type`s of `<space>` will never have `@unit` and `@quantity`. Indeed, `@type="defect"` can take those attributes as per the EG, and I missed that above; but the others will always be without them, so delete the part beginning with "analogously"

And thus, if an error message is desired, it should also come up if `@type="ascender"` or `@type="descender"` is combined with any other attributes.

**Comment by arlogriffiths** [comment]
OK, so I recap again

- ◯ U+25EF Large Circle for `<space type="binding-hole"/>`
- □ U+25A1 White Square for `<space type="defect"/>`
- ⊔ U+2294 Square Cup for `<space type="descender"/>`
- ⊓ U+2293 Square Cap for `<space type="ascender"/>`
-  _ (underscore) for `<space/>` without any attributes
-  \_n\_ for `<space quantity="n" unit="character"/>` without @type
- □n□ for `<space quantity="n" unit="character" type="defect"/>`
- create error messages if `@type="binding-hole"`, `@type="descender"` or `@type="ascender"` are found combined with any other attributes.

**Comment by danbalogh** [comment]
Perfect!

**Comment by manufrancis** [comment]
I am strongly against the multiplication of various displays.
This obscures the reading of the edition. For further details, the user will have to look at the xml. Moreover, info will be given in the metadata about some of the `<space>` while visual documentation will be usually available for the editions where `<space>` is encoded.
My suggestion is thus:
* diamond character ◊ for any `<space>` whatever the value of `@n`
* ◯ for `<space type="binding-hole"/>`

**Comment by danbalogh** [comment]
I'm happy to leave the decision in the PIs' hands, but I think it is not a good idea to display the spaces with `@type` (i.e. those forced on the engraver by physical necessity, viz. hole, defect, ascender and descender) in the same way as deliberate spaces left blank for punctuation or subsequent filling.

**Comment by arlogriffiths** [comment]
I caste my vote in favor of testing the system proposed by Daniel. If we collectively decide we don't like it, we can always revert to a simpler system like that proposed by Manu.

**Comment by manufrancis** [comment]
OK for me for testing the system proposed by Daniel.
Note that, as most markup for `<space>` is optional (if I am correct in my memory of EGD), TFA will use `<space>` only for true vacat. Other `<space>`s TFA will just be recorded in the metadata.
Dear Dan, could you confirm that in doing so, I am still correctly following the EGD?

**Comment by danbalogh** [comment]
Dear Manu, encoding `<space>` for areas skipped by the engraver out of physical necessity (binding hole, surface defect, encroaching characters from other lines) is indeed optional, you are correctly following the EGD if you choose not to do so. Apart from true vacat, according to the EGD as it now stands, simple spaces (used at semantic breaks in the text) that are two or more characters wide should also be encoded explicitly. Using width as a criterion is perhaps not the most fortunate choice (but I could never come up with a better one that is simple and quite objective). The idea is that any conspicuous spaces used between words, sentences, stanzas or paragraphs should preferably be encoded, unless you are working from an edition without access to a facsimile.

**Comment by manufrancis** [comment]
Thanks, Dan! Noted. I will thus encode them explicitly. But I have still reservation about displaying them, as I find there is an inflation of display marks that renders editions less easy to read.
