### ISSUE TITLE
transformation problem

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#57]
@ajaniak — When trying to transform the file Guntur.xml, I get the following error message:

<img width="1645" alt="Capture d’écran 2020-09-05 à 07 46 19" src="https://user-images.githubusercontent.com/835603/92298714-1cebf480-ef4c-11ea-8992-6d92ed068afc.png">

Can you solve this?

**Comment by ajaniak** [comment]
It is related to the fact Daniel and you wanted to declutter the code in the <lem>, so the code to handle the presence of an  `<lb/>` element inside a `<lem>` is dealt with a sum function, which cannot be performed one a structure organized paginated with recto and verso.

**Comment by arlogriffiths** [comment]
Sorry, I don't understand your response. 

- What is a "sum function"? 
- What do the words "which cannot be performed one a structure organized paginated with recto and verso" mean? 
- Does your response contain a proposal for solving the problem? If not, please formulate a proposal for
 -- either modifying the EGD or
 -- modifying the way I encode this situation

**Comment by arlogriffiths** [comment]
I'd be very grateful if I could get help solving this problem which apparently affects all files that contain bibliography.

I have prepared a number of editions to read in my EPHE séminaire this year, and I want to send the html displays to the participants a.s.a.p.

**Comment by arlogriffiths** [comment]
correction, the problem does not seem to be bibliography-related after all. it must be related to the use of `<lb/>` in apparatus, as Axelle suggested.

I await instructions for how to solve it in my xml files, if the solution doesn't lie in changing the xslt code.

**Comment by manufrancis** [comment]
<lb> issue solved.
Axelle reverted to the ancient code in the XSLT.
Thus you need to pull "project documentation".

Important: keep in `<lem>` the text as it is in the edition, with all its markup; do not declutter <lb> (keep all @).

NB @arlogriffiths : the remaining transformation issues in some of your Nusantara XMLs pertain to Zotero Short Titles:
EITHER two publications have same ST
OR ST in the field ST does not correspond to ST in Tags
OR one an the same publication has several ST in Tags

**Comment by arlogriffiths** [comment]
Thanks @ajaniak  and @manufrancis . I am closing this issue now and have already opened a few new ones concerning problems with display of bibliography.
