### ISSUE TITLE
encoding/displaying journal-volume references in epigraphic lemma

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#62]
Salomé and I have just redacted the following lemma:

`<p>First mentioned in the <foreign>Chronique</foreign> section of <bibl><ptr target="bib:BEFEO36_1936"/><citedRange unit="page">634</citedRange></bibl>, then edited by George Cœdès without any translation (<bibl rend="omitname"><ptr target="bib:Coedes1937_1966_01"/><citedRange unit="volume">6</citedRange><citedRange unit="page">170-172</citedRange></bibl>). The text of this inscription is very similar to the text of <ref target="K0444.xml">K. 444</ref>. It is re-edited here by Salomé Pichon based on EFEO estampage n. 1120.</p>`

I wasn't sure how to integrate the short title "BEFEO36_1936" here because I am not sure how such a reference could be displayed. (In the case of normal short titles, I suppose Axelle will build the display using the author surname and year corresponding to a given zotero entry, but this will not be possible  for journal short titles.)

**Comment by danbalogh** [comment]
I'm not sure I understand the situation, or the question, fully. Is it the case that BEFEO mostly consists of authored articles which are in our Zotero base singly and separately, but in this particular case you need to refer to an authorless "chronique" in that particular issue? I guess this would then have to be treated in the same way as serial publications like the ARIE, but I don't know anything about what sort of display is planned for those. If that is not desired, perhaps an article-type Zotero entry could be created for the Chronique, with anonymous author if there is no information on who wrote it.

**Comment by ajaniak** [comment]
When no author is filled in Zotero, the field title is displayed. For your BEFEO entry, it gives this `Bulletin de l’École française d’Extrême-Orient, tome XXXVI, 1936 (1937), 634`.

**Comment by arlogriffiths** [comment]
@danbalogh : indeed, it is the case that BEFEO mostly consists of authored articles which are in our Zotero base singly and separately, but in this particular case I need to refer to an authorless "chronique" in that particular issue.

@ajaniak : thanks. I don't think that display is satisfactory, but the other PIs should confirm my judgment, and unfortunately I don't see how something significantly more satisfactory could be generated from the elements we have in such zotero entries. Maybe you can discuss with Manu and come up with an alternative display? Ideally, I'd like it to be `BEFEO 36 (1936): 634` in this case but doubt that can be genenrated as long as itemType is "book". (What if we cheat and use "journal article", which would make the field "journal abbr" available, as well as "volume" and "date"?)
