### ISSUE TITLE
reference to EGD 7.5 in template (v2)

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#63]
`<!-- If you need to identify individual hands (EG §7.5/) in addition to one or more paragraphs of general palaeographic description, wrap <summary> around the <p> or <p>s above, and, outside <summary>, create <handNote> elements for each hand as follows: -->`

Should the reference not be 11.2.1?

**Comment by danbalogh** [comment]
I think not. §11.2.1 is about the hand description in general, so we can include a reference to that in the template, but the bit you cite is about individual hands. These are presently discussed in EGD §4.4, but I'm planning to move it to §7.5, and it may also have been §7.5 in an earlier version of the EGD. Best to leave the template as it is for now.
