### ISSUE TITLE
bibliography display 2: a problem related to short titles and tags?

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#67]
In the file Guntur.xml, the following code

` <div type="commentary">
            <p n="1v4-1v5">Stutterheim (<bibl rend="omitname"><ptr target="Stutterheim1935_01"/></bibl>) observed that the words <foreign>tamān paṅujara muvaḥ</foreign> (which he still quoted in Brandes' reading with <foreign>tatān</foreign>) find a parallel in the word <foreign>tan punaruktā</foreign> at the end of the <ref target="Palebuhan.xml">Palebuhan inscription</ref>. The correspondence of this while closing paragraph with the final words preserved of the <ref target="Laguna.xml">Laguna plate</ref> are even more remarkable.</p>
         </div>`

Currently leads to this display:

<img width="1009" alt="Capture d’écran 2020-09-23 à 06 44 59" src="https://user-images.githubusercontent.com/835603/93967831-6029ce00-fd68-11ea-9406-46af3ce372fb.png">

We would want "Stutterheim (1935) observed ..." in display and only the date 1935 as hyperlink. 

Manu explained to me the need for zotero Short Titles and tags to be consistent, which (after some manual fixes last night) seems to be the case:

<img width="1034" alt="Capture d’écran 2020-09-23 à 06 48 49" src="https://user-images.githubusercontent.com/835603/93968045-e6461480-fd68-11ea-82cd-d01e57c7ab0a.png">

<img width="1036" alt="Capture d’écran 2020-09-23 à 06 49 02" src="https://user-images.githubusercontent.com/835603/93968047-e8a86e80-fd68-11ea-994c-f62f88e645c0.png">

Can you fix this bug?

**Comment by ajaniak** [comment]
The prefix `bib:` is missing in `<bibl rend="omitname"><ptr target="Stutterheim1935_01"/></bibl>` . 

<img width="982" alt="Capture d’écran 2020-09-23 à 14 37 02" src="https://user-images.githubusercontent.com/33328906/94013441-5e80fa00-fdaa-11ea-8fb4-a0916e76a828.png">
