### ISSUE TITLE
bibliography display 3: vanishing "Primary bibliography" and further problems with short titles

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#68]
If I try to transform my file Guntur.xml with start-edition-with-bibliography

1. the part "Primary" of the structure bibliography is not displayed at all, and 
2. a total of only three entries of the type `<bibl><ptr target="bib:NBG14_1877"/><citedRange unit="page">136-137</citedRange></bibl>` in secondary bibliography cause the display of what seems to be dozens of zotero items with "NBG" in their short titles

See screenshot.

<img width="1018" alt="Capture d’écran 2020-09-23 à 06 55 10" src="https://user-images.githubusercontent.com/835603/93968593-4093a500-fd6a-11ea-8568-53c309b5cc10.png">

**Comment by ajaniak** [comment]
There are several issues in this file: 

- NBG14_1877 doesn't exist in Zotero. I find only a NBG14_1876. 
- All the data in the collection NGB were attributed a NBG24_1886 tag, so the API was sending them all back. I cleaned it. 
- Krom1911_01 is matching to 2 entries. Still need to be cleaned up. 
- Bosch1915_01 was given to 3 different entries. 
- Bosch1926_02 wasn't matching a real data. 
- JVMMR1919 didn't have its tag. 

The issue regarding your primary bibliography 
<bibl n="H"><ptr target="bib:Holle1880_02"/><citedRange unit="part">1 <q>Koperen platen uit de collectie van den heer J.A. Dieduksman</q></citedRange><citedRange unit="page">1-2</citedRange></bibl>
The `<q>` element isn't modeled in DHARMA to be allowed into `<citedRange>`. It needs to be extracted and a `<note>` need to be wrapped around. However, the `<note>`isn't recommended by EGD 10.4.1. 
I can only make a dirty result for now.

**Comment by arlogriffiths** [comment]
Thanks for identifying all these problems and solving several of them. I have now dealt with the remaining problems. Closing this issue.
