### ISSUE TITLE
bibliography 4:  transformation error and another vanishing part of bibliography

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#69]
If I try to transform my file WuruduKidul.xml using start-edition-with-bibliography, I get this error message:

<img width="1506" alt="Capture d’écran 2020-09-23 à 07 02 30" src="https://user-images.githubusercontent.com/835603/93968992-21494780-fd6b-11ea-9582-4ee6669d2dbe.png">

If I then comment out the narrative `<p>` in `<div type="bibliography">`, the transformation problem vanishes but only the "Primary" section of the structured bibliography is displayed:

<img width="1026" alt="Capture d’écran 2020-09-23 à 07 03 53" src="https://user-images.githubusercontent.com/835603/93968997-26a69200-fd6b-11ea-91b1-5a8386e6e5fa.png">

The fact that the initial error disappears if I comment out the `<p>` suggests there is an error inside that `<p>`, but I cannot detect it.

**Comment by ajaniak** [comment]
- Stutterheim1925_04 wasn't declare.
- TBG1926_66 wasn't properly declared
- SukartoAtmodjo1975 matches 2 entries in Zotero

**Comment by arlogriffiths** [comment]
Thanks for catching those problems. The file now transforms without error message, but the secondary bibliography isn't displayed yet. I hope you can find the cause of that problem!

**Comment by ajaniak** [comment]
I cleared the position of your comments node compare to the text node. 

<img width="974" alt="Capture d’écran 2020-09-25 à 11 16 54" src="https://user-images.githubusercontent.com/33328906/94249770-a6299200-ff20-11ea-90d4-a92d27bc596c.png">

**Comment by arlogriffiths** [comment]
Thanks.

I am sorry I don't really understand what "clearing the position of my comments node compared to the text node" means.

Could you explain 

1. what the problem is and how I can avoid it
2. how I can repeat your trick in other files

Thanks again.

**Comment by arlogriffiths** [comment]
My file Munduan.xml, for instance, still seems to suffer from the same problem. If you tell me how, I can try to trouble shoot myself.

**Comment by ajaniak** [comment]
Commentary nodes are not well parsed and can be confused, if not treated carefully. When you have a node text, it tends to fusion with it, usually adding a space before your comment makes the trick. 
I don't see any trouble while launching Munduan.xml

**Comment by arlogriffiths** [comment]
Indeed, Munduan now seems no longer to pose any problem. I do see these messages:

<img width="1636" alt="Capture d’écran 2020-10-05 à 15 34 52" src="https://user-images.githubusercontent.com/835603/95086122-659bf680-0720-11eb-9ded-049ed8fa68da.png">

1. Do team members (such as myself) have a need to know what such messages mean, esp. the second one?
2. Please confirm that your advice is to insert a space/hard return before any XML comment. 
3. After that, this issue can be closed, I think.

**Comment by ajaniak** [comment]
1. I left the message for the issue regarding `<ref>` but no once the code works I turn them off (I have forgotten to turn it off for the first line) but be careful about them sometimes it indicates not well-formedness in the XML or explain issues. 
2. Yes, I recommend adding a space because it is easier to normalize space when necessary than adding one to avoid the fusion of text nodes () like the issue you have open a few days ago. 
3. OK. I am closing then.
