### ISSUE TITLE
remove spaces around / representing <lb/> in <rdg>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#73]
Code:

`<app loc="1r6">
	<lem source="bib:Damais1970_01">tgu<lb n="1r7" break="no"/>hān</lem>
	<rdg source="bib:Brandes1913_01">tgu<lb/>hhan</rdg>
	<note>I adopt the reading recorded by <bibl><ptr target="bib:Damais1970_01"/><citedRange unit="page">455</citedRange></bibl>.</note>
</app>`

Display:

<img width="567" alt="Capture d’écran 2020-09-24 à 06 10 17" src="https://user-images.githubusercontent.com/835603/94100016-aba5b000-fe2c-11ea-8833-7138405f5232.png">

I think we want to see the same behavior for `<lb/>` in `<rdg>` as in `<lem>`: no insertion of spaces around the slash.

**Comment by arlogriffiths** [comment]
See also #79.

**Comment by ajaniak** [comment]
As discussed with @manufrancis at the implementation of such a feature, if your `<lb>` has a `@break="no"`, there is no space. But in absence of `@break`, spaces are expecting around the `/`.

**Comment by arlogriffiths** [comment]
Thanks. So I have removed the difference between lem and rdg by inserting break="no" into the lb inside rdg.
