### ISSUE TITLE
define basic behavior of <q>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#75]
May we start testing the use of `<q>` by defining its behavior as follows?

`<q>abc</q>` to be displayed, in any context (`<div>`), and regardless if presence/absence of any @xml:lang, as ‘abc’ (NB: smart quotes)

**Comment by ajaniak** [comment]
It has been added when the element was inserted in the EGD. My previous remark on `<q>`wasn't related to the lack of behaviour but because you have chosen to use somewhere it can't be used regarding Epidoc XSLT
