### ISSUE TITLE
closing ) of <unclear> lost in display

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#77]
code:

`<lb n="2r3"/><unclear>pa</unclear><choice><sic>ṇḍāka</sic><corr>ṇḍak·</corr></choice><!-- what looks like tarung might be misplaced virāma, so read paṇḍāka and correct paṇḍak·? --> Er baraṅan·`

display:

<img width="241" alt="Capture d’écran 2020-09-24 à 19 11 46" src="https://user-images.githubusercontent.com/835603/94177443-d1b56980-fe99-11ea-8fdc-59ceebf5350f.png">

**Comment by ajaniak** [comment]
I am reworking the code but haven't been able to solve this yet. I will let you know once it is done.
