### ISSUE TITLE
<p> in <handDesc>

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#85]
Axelle needs our consensus about the encoding and displaying of `<handDesc>`.
Do we allow only one `<p>` in it or as many `<p>` as the encoder wants?
NB: as for display, whether there is one or several `<p>`, the whole can be displayed as one `<p>` only.

**Comment by danbalogh** [comment]
I definitely prefer several `<p>`s. In most of my files I already have multiple paragraphs in the hand description, for "original punctuation", "halanta consonants" and "other palaeographic remarks". I would also prefer if multiple `<p>`s would remain multiple paragraphs in display.

**Comment by danbalogh** [comment]
To expand on the above, the EGD (§11.2.1) already says, "to record your observations, use the element <p> within <handDesc>, filing it with free prose / you may create additional <p> elements for a longer description"
I think we should keep it that way unless there is a strong reason to change it.

**Comment by arlogriffiths** [comment]
I second @danbalogh's response.
