### ISSUE TITLE
Review new XML Template

### ISSUE THREAD

**Issue by ajaniak** [erc-dharma/project-documentation#9]
Dear all, 

I have edited the new template with `<handDesc>` for @arlogriffiths  and `<summary>` for @manufrancis . Please take a look. 

For `<handDesc>`, I add to develop a little the `<msIdentifier>` to prevent validation issues. @alevivier has validated the solution applied in the file. 

@manufrancis, can you confirm me that you want the possibility to give a summary of the intellectual content ? If you want something closer to an abstract, I will change the element for `<abstract>`and put it in the `<profileDesc>` rather than `<summary>` in the `<msContents>`. 

Thanks

**Comment by arlogriffiths** [comment]
looks good. I've made some slight edits and pushed the revised version to the repo.

should we not number the version 2 now?
should you not add a line to revDesc?

**Comment by manufrancis** [comment]
Looking at examples provided in www.tei-c.org '<summary>' is fine.

**Comment by ajaniak** [comment]
Thank you for your feedbacks. I made it version 2.
