### ISSUE TITLE
on siglum

### ISSUE THREAD

**Issue by manufrancis** [erc-dharma/project-documentation#90]
Here are my suggestions and desiderata about siglum (cf. discussion started before Summer vacation ;-)
Besides the presently prescribed way of coining sigla in the EGD, I would like to add the following deviation(s), instead of initials of the author:
* SII_2.1 [= South Indian Inscriptions, volume 2, inscription n° 1]
* IP_20 [= T.V. Mahalingam, Inscriptions of the Pallavas n° 1]
* SOCI_20 [= Fleet, Sanskrit and Old Canarese Inscriptions n° 20]
* EI_2.25 [= Epigraphia Indica, volume 2, inscription/article n° 25] 
* ARIE_1899/A/26
* etc.
* Also for NBG? So that in epigraphical lemma the full name of the publication is displayed while the usual abbreviation is recorded and displayed as siglum.

The underscore is kept in coining siglum, but there is no difficulty for Axelle to not display it.

Such sigla, I would like to use anywhere in our XMLs (apparatus, commentary, epigraphical lemma, …) with or without other reference.
I find more convenient, clear and straightforward to refer in apparatus to “IP 20” rather than to “TVM” or to refer to "SII 12.42" instead of "VVA" (= Venkatasubba Ayyar 1943, by mouse tool-tip, which is an obscure and unpractical reference anyway, which compels the user to look at the bibliography).

Example of apparatus:
 
![image](https://user-images.githubusercontent.com/905870/95965901-c86d4c00-0e0a-11eb-8f1f-18386e4230d9.png)

I prefer “SII 12.42” instead of “VVA”. With mouse tool-tip indicating “Venkatasubba Ayyar 1943”

Example of epigraphical lemma as presently displayed:

![image](https://user-images.githubusercontent.com/905870/95965949-d91dc200-0e0a-11eb-84ea-0a20f7ecf847.png)

I would like something like Venkatasubba Ayyar 1943 (SII 12.42),
where both “Venkatasubba Ayya 1943” and “(SII 12.42)” are generated in the transfo [(SII 12.42) is presently plain text].

**Comment by manufrancis** [comment]
Alternatively, we could simply use SII, IP, EI, ARIE, etc. (without reference to volume and inscription number) but I would leave it open to the encoder.

**Comment by arlogriffiths** [comment]
Yes, it would be good to modify EGD so that the option of such alternative sigla, not based on author name but on abbreviation of the containing publication, be explicitly offered. Since the volume etc. are already specified with `<citedRange>`, I'd prefer keeping the sigla limited to the abbreviations SII, IP, EI, ARIE, etc. (without reference to volume and inscription number), while leaving open the possibilkity of more complex sigla should the encoder feel it is necessary. (One can imagine that the existence of multiple editions published in different volumes of the same journal indeed makes such further specification necessary.) I would personally not recommend aiming for display with space (and encoding the expected space with underscore) to separate letters from numbers in such complex sigla, as this may create the false impressioin that two different @sources gave the `<lem>` or `<rdg>` in question.

**Comment by danbalogh** [comment]
Any solution you can agree on will be fine for me. My personal preference is, as usual, for simplicity and consistency as far as possible, so I would prefer to stick to author-date references (and apparatus sigla based on author initials) in all circumstances where that is feasible, avoiding all custom references such as SOCI and SII, as well as reference to EI articles by number in the volume. These can always be mentioned in plain text in the primary bibliography, commentary, notes, if the need for that is felt. I'm of course fine with ARIE and NBG etc. where the author-date system does not work.

**Comment by danbalogh** [comment]
I concur with Arlo in preferring simple ARIE etc. without a volume or other number, unless that is necessary for disambiguation. (I in fact proposed just this in an EGD comment dated 10 August, under §9.4.3.) With or without space is fine for me.
The present EGD does already say, 

> when our Zotero short title for the publication does not include an author name (as is the case with certain journal-type publications, for which see ZG §4.4.2), use the Zotero short title as a siglum, adding a space between the journal abbreviation and the year

I don't recall every detail of the discussion leading up to this, but there was discussion, and I'm pretty sure we had explicit confirmation from Axelle that using a space was OK.

Before making any further changes to the EGD I need one of you to tell me where, how and for what purpose the sigla are meant to be used. At present, the only context in which the EGD mentions sigla is the apparatus, but it seems to me that at least some of you are considering being able to use them elsewhere (commentary, notes). This is also something I proposed in an EGD comment back in the summer (14 Aug, under §9.4.2).

**Comment by manufrancis** [comment]
I prefer, as Arlo suggested, leaving open the possibility of more complex sigla should the encoder feel it is necessary. After all, he might want his online edition to conform to his wish. And whatever is the siglum adopted (I mean, with or without volume and inscription number), I guess it has no implication for the transformation scenario.
Axelle, can you confirm this?
Furthermore, encoding volume and inscription number in the siglum makes them more easily machine-actionable (e.g. to extract them to create a key-word [best for google results]), and, either from the siglum or the key-word, create concordances between SII and DHARMA. 
Axelle, can you confirm this?
Axelle will also be able to create automatically the reference to SII volume and inscription in the epigraphical lemma from the siglum in bibliography. Thus no extra-work of recording it in plain text in the epigraphical lemma.
Axelle, can you confirm this?
As for allowing space in siglum, after discussion with Axelle, it seems not advisable to allow it (let people just understand that it is not allowed in siglum), as Axelle can for the display of siglum, wherever we want it (apparatus, epigraphical lemma, commentary), write a code that replaces the underscore by a space.

**Comment by danbalogh** [comment]
I do not understand why we would want to create keywords and concordances on the basis of sigla when the file already includes the full and accurate, rigorously encoded <bibl> reference for those items. But as I said above, I'll accept any solution the PIs can agree on.

**Comment by manufrancis** [comment]
Thanks all!
Will discuss that with Axelle during our next weekly skype and will come with updated proposal.

**Comment by manufrancis** [comment]
I stick to my wishes for 

siglum for IP: IP1
siglum for SII: SII1.1
siglum for SOCI: SOCI1
siglum for EI: EI1.1
siglum for ARIE: ARIE2000/B/1

which should be optional to the more concise options (IP, SII, SOCI, EI, ARIE), themselves optional to the standard rule for sigla (initials of the author of the edition).

Thus no space nor underscore in sigla.
Thus no risk of creating the false impression that two different @sources gave the `<rdg>` in question.
Thus when two @sources give the same reading, a space separate them.

I am in favour of using rend="siglum" provided the editor uses it consistently in the edition concerned, at the exception of the epigraphical lemma.
I am thus fine with plain text in the epigraphical lemma (e.g. "SII 1, n° 1" between parentheses after the `<bibl>`)

**Comment by manufrancis** [comment]
Trying to close this issue and revising my stand.

OK for EGD 9.4.3 as it stands now (with the comments to be solved; to which I will also answer in the EGD googledoc).
The current display with the mouse over tool-tip providing author's name and date is fine with me.

As for @rend="siglum" I am in favour of allowing it, to optionally use siglum in apparatus notes, etc.
