### ISSUE TITLE
question about DHARMA_INSCIC00171

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#93]
I seem to get a html without problem.

But I get the following messages in Oxygen:

<img width="1640" alt="Capture d’écran 2020-10-22 à 14 55 51" src="https://user-images.githubusercontent.com/835603/96875276-55ea1500-1477-11eb-928e-b1d412ef5c7d.png">
<img width="1642" alt="Capture d’écran 2020-10-22 à 14 56 03" src="https://user-images.githubusercontent.com/835603/96875279-571b4200-1477-11eb-9707-ac74a8e9b8b8.png">
<img width="744" alt="Capture d’écran 2020-10-22 à 14 56 16" src="https://user-images.githubusercontent.com/835603/96875281-571b4200-1477-11eb-9ba0-b9ab3b1ee0e9.png">

I don't understand why Oxygen is complaining about 

"ptr with a @target in the bibl element `<xsl:copy-of select="."/>`. A target equal to a tag in your zotero bibliography is  necessary"

As far as I can see, there is a ptr with @target in my code and in Zotero I do find a tag define for the entry in question.

Can you explain? Thanks!

**Comment by ajaniak** [comment]
```
	<listBibl type="primary">
	<bibl n="FG"/>
        <bibl><ptr target="bib:Finot+Goloubew1925_01"/><citedRange unit="page">472-474</citedRange>
	</bibl>
```
You have two `<bibl>` elements for only one entry. The first contains the siglum of the second one. So you have the error message telling you a primary bibliography entry should have a siglum associated. 
Your XML should be : 

```
<listBibl type="primary">
	<bibl n="FG"><ptr target="bib:Finot+Goloubew1925_01"/><citedRange unit="page">472-474</citedRange></bibl>
```

**Comment by arlogriffiths** [comment]
oops! thanks!

why did Oxygen not flag my code as invalid?

**Comment by ajaniak** [comment]
because strictly speaking, it is not badly-formed XML and it is conformant to Epidoc schema.

**Comment by arlogriffiths** [comment]
ok, thanks!
