### ISSUE TITLE
suggest value "note" for @unit on <citedRange>

### ISSUE THREAD

**Issue by arlogriffiths** [erc-dharma/project-documentation#99]
The schema currently does not yet suggest all values admitted in EGD for @unit on `<citedRange>`. At least I see that "note" isn't yet offered. See screenshot.

<img width="1354" alt="Capture d’écran 2020-11-21 à 15 17 14" src="https://user-images.githubusercontent.com/835603/99879356-da61bc00-2c0c-11eb-8ee5-a06ff7a3fc1e.png">

**Comment by ajaniak** [comment]
I can't do anything since we are using the Epidoc schema as requested. 
Note is already added in the XSLT.

**Comment by manufrancis** [comment]
will be dealt with the implementation of the DHARMA schema.

**Comment by ajaniak** [comment]
it has already been added in the schema
